import type { Peptide, PeptideArea, RegulatoryBadge } from "./types";

type Kind = "cosmetic" | "approved" | "investigational" | "research";

const kindBadges: Record<Kind, RegulatoryBadge[]> = {
  cosmetic: ["COSMETIC"],
  approved: ["APPROVED_MEDICINE"],
  investigational: ["INVESTIGATIONAL", "NOT_APPROVED_FOR_HUMAN_USE"],
  research: ["RESEARCH_ONLY", "NOT_APPROVED_FOR_HUMAN_USE"],
};

function entry(opts: {
  slug: string;
  name: string;
  aliases?: string[];
  kind: Kind;
  peptideClass: string;
  structure: string;
  what: string;
  how: string;
  body: string;
  studied: string[];
  benefits: string[];
  notFor: string[];
  human: string;
  pre: string;
  sides: string;
  contra: string;
  reg: string;
  au: string;
  areas: PeptideArea[];
  terms?: string[];
  sell?: boolean;
  productHref?: string;
}): Peptide {
  const sell = opts.sell ?? false;
  return {
    slug: opts.slug,
    name: opts.name,
    alternativeNames: opts.aliases ?? [],
    peptideClass: opts.peptideClass,
    structure: opts.structure,
    whatItIs: opts.what,
    howItWorks: opts.how,
    whatItDoesInBody: opts.body,
    studiedFor: opts.studied,
    potentialBenefits: opts.benefits,
    mayNotBeUsefulFor: opts.notFor,
    humanEvidence: opts.human,
    preclinicalEvidence: opts.pre,
    sideEffects: opts.sides,
    contraindications: opts.contra,
    regulatoryStatus: opts.reg,
    australianRegulatoryStatus: opts.au,
    badges: kindBadges[opts.kind],
    areas: opts.areas,
    availableToPurchase: sell,
    productHref: opts.productHref ?? (sell ? "/shop/peptide-serums" : undefined),
    searchTerms: opts.terms ?? [],
    references: [
      {
        title: "Encyclopaedia note",
        citation:
          "Educational summary compiled for Cellular Sequence. Not a product COA, not medical advice, and not an offer to sell unapproved medicines.",
      },
    ],
  };
}

const cosmeticStd = {
  human:
    "Evidence is mainly cosmetic or ingredient-supplier studies, not pharmaceutical Phase 3 programmes.",
  pre: "In-vitro and small dermal models are commonly cited by manufacturers.",
  sides: "Topical irritation is possible. Do not inject cosmetic ingredients.",
  contra: "Hypersensitivity to the ingredient or formulation. Not for broken skin unless a clinician directs.",
  reg: "Cosmetic ingredient / branded cosmetic active. Not an approved systemic medicine.",
  au: "Permitted in cosmetics when formulated and advertised within cosmetic rules. Cellular Sequence does not sell research-chemical injectables of these actives.",
};

/** Cosmetic / hair-skin proteins and peptides from typical Australian raw-material catalogues (educational INCI names). */
export const cataloguePeptides: Peptide[] = [
  entry({
    slug: "acetyl-hexapeptide-51-amide",
    name: "Acetyl hexapeptide-51 amide",
    kind: "cosmetic",
    peptideClass: "Cosmetic signal peptide",
    structure: "Acetylated hexapeptide amide used in topical anti-ageing systems.",
    what: "A cosmetic peptide ingredient, not a prescription wrinkle medicine.",
    how: "Marketed for DNA-repair-adjacent gene-expression stories in skin cells — interpret as cosmetic, not oncology.",
    body: "Leave-on skin exposure only in finished cosmetics.",
    studied: ["Appearance of photoaged skin (cosmetic)"],
    benefits: ["Cosmetic support for the look of resilient skin"],
    notFor: ["Treating skin cancer or medical photodamage"],
    areas: ["skin-hair"],
    terms: ["hexapeptide-51"],
    ...cosmeticStd,
  }),
  entry({
    slug: "acetyl-octapeptide-3",
    name: "Acetyl octapeptide-3",
    aliases: ["SNAP-8", "Snap-8"],
    kind: "cosmetic",
    peptideClass: "Cosmetic SNAP-25 analogue (topical)",
    structure: "Acetylated octapeptide related to SNAP-25 fragments; longer analogue of acetyl hexapeptide-8.",
    what: "A topical cosmetic peptide for the look of expression lines. Supplier ‘Snap-8 vials’ for injection are not the same as a leave-on cosmetic and are not sold here.",
    how: "Proposed SNARE-related topical mechanism; clinical effect sizes are modest versus prescription neuromodulators.",
    body: "Intended for intact skin as a cosmetic.",
    studied: ["Appearance of expression lines"],
    benefits: ["Possible softening in the look of fine lines"],
    notFor: ["Replacing botulinum toxin medicines", "Injectable ‘Botox in a vial’ protocols"],
    areas: ["skin-hair"],
    terms: ["snap-8", "snap8", "argireline analogue"],
    sell: true,
    ...cosmeticStd,
  }),
  entry({
    slug: "acetyl-tetrapeptide-3",
    name: "Acetyl tetrapeptide-3",
    aliases: ["Follicle-related cosmetic tetrapeptide"],
    kind: "cosmetic",
    peptideClass: "Cosmetic tetrapeptide (hair/skin appearance)",
    structure: "Acetylated tetrapeptide used in scalp and lash-appearance formulas.",
    what: "Cosmetic peptide for the look of hair density — not an approved hair-loss drug.",
    how: "Marketed around extracellular-matrix signalling in the follicle environment.",
    body: "Topical cosmetic use.",
    studied: ["Appearance of thinning hair (cosmetic)"],
    benefits: ["Cosmetic hair-look support"],
    notFor: ["Androgenetic alopecia as a TGA-evaluated medicine"],
    areas: ["skin-hair"],
    terms: ["capixyl", "hair peptide"],
    ...cosmeticStd,
  }),
  entry({
    slug: "acetyl-tetrapeptide-15",
    name: "Acetyl tetrapeptide-15",
    kind: "cosmetic",
    peptideClass: "Cosmetic soothing tetrapeptide",
    structure: "Acetylated tetrapeptide used in sensitive-skin cosmetics.",
    what: "Topical cosmetic peptide explored for the look of reactive skin.",
    how: "Marketed for neurosensory soothing narratives in cosmetics.",
    body: "Skin-surface cosmetic exposure.",
    studied: ["Appearance of sensitive, tightness-prone skin"],
    benefits: ["Cosmetic comfort of the skin look"],
    notFor: ["Treating rosacea or allergy as a medicine"],
    areas: ["skin-hair"],
    ...cosmeticStd,
  }),
  entry({
    slug: "palmitoyl-tripeptide-5",
    name: "Palmitoyl tripeptide-5",
    aliases: ["Syn-Coll", "Pal-KVK"],
    kind: "cosmetic",
    peptideClass: "Cosmetic matrikine (palmitoylated tripeptide)",
    structure: "Palmitoyl-lysyl-valyl-lysine related sequences used as collagen-appearance actives.",
    what: "Widely used cosmetic peptide for the look of firmness.",
    how: "Claimed TGF-β-related signalling in fibroblasts — cosmetic evidence grade.",
    body: "Topical cosmetic.",
    studied: ["Wrinkle appearance"],
    benefits: ["Look of firmer skin"],
    notFor: ["Medical collagen disorders"],
    areas: ["skin-hair"],
    terms: ["syncoll"],
    sell: true,
    ...cosmeticStd,
  }),
  entry({
    slug: "palmitoyl-tripeptide-38",
    name: "Palmitoyl tripeptide-38",
    aliases: ["Matrixyl Synthe’6", "Matrixyl Synthe 6"],
    kind: "cosmetic",
    peptideClass: "Cosmetic matrikine",
    structure: "Palmitoylated tripeptide used in Matrixyl Synthe’6 systems.",
    what: "Cosmetic peptide blend component for wrinkle appearance.",
    how: "Marketed for multiple matrix-protein appearance pathways.",
    body: "Topical cosmetic.",
    studied: ["Forehead and wrinkle appearance"],
    benefits: ["Cosmetic smoothness look"],
    notFor: ["Injectable biostimulation as a drug"],
    areas: ["skin-hair"],
    terms: ["synthe6", "matrixyl"],
    sell: true,
    ...cosmeticStd,
  }),
  entry({
    slug: "matrixyl-3000",
    name: "Matrixyl 3000",
    aliases: ["Palmitoyl tripeptide-1 + palmitoyl tetrapeptide-7"],
    kind: "cosmetic",
    peptideClass: "Branded cosmetic peptide pair",
    structure: "Combination of Pal-GHK and palmitoyl tetrapeptide-7.",
    what: "A trade-name cosmetic system, not a medicine.",
    how: "Matrikine signalling narrative in topical products.",
    body: "Leave-on cosmetics.",
    studied: ["Wrinkle appearance in combination formulas"],
    benefits: ["Look of smoother skin"],
    notFor: ["Treating disease"],
    areas: ["skin-hair"],
    sell: true,
    ...cosmeticStd,
  }),
  entry({
    slug: "dipeptide-diaminobutyroyl-benzylamide-diacetate",
    name: "Dipeptide diaminobutyroyl benzylamide diacetate",
    aliases: ["Syn-Ake", "Snake venom peptide (cosmetic)"],
    kind: "cosmetic",
    peptideClass: "Cosmetic Waglerin-1 mimetic",
    structure: "Tripeptide-related mimetic of temple-viper Waglerin-1 fragment, used topically.",
    what: "A cosmetic ‘snake peptide’ for expression-line appearance. It is not venom and not a medicine.",
    how: "Proposed muscle-relaxation-look mechanism at the skin surface.",
    body: "Topical cosmetic only.",
    studied: ["Appearance of expression lines"],
    benefits: ["Cosmetic softening look"],
    notFor: ["Equivalent to botulinum toxin"],
    areas: ["skin-hair"],
    terms: ["syn-ake", "snake venom peptide"],
    ...cosmeticStd,
  }),
  entry({
    slug: "ahk-cu",
    name: "AHK-Cu",
    aliases: ["Copper tripeptide AHK", "Ala-His-Lys copper"],
    kind: "cosmetic",
    peptideClass: "Copper-binding tripeptide (cosmetic)",
    structure: "Alanyl-histidyl-lysine copper complex, related to GHK-Cu chemistry.",
    what: "Cosmetic copper peptide explored for hair- and skin-appearance formulas. Not an injectable medicine.",
    how: "Copper delivery / signalling hypotheses in dermal and follicle models.",
    body: "Topical cosmetic context.",
    studied: ["Hair-appearance and skin-look cosmetics"],
    benefits: ["Cosmetic copper-peptide support"],
    notFor: ["Systemic copper therapy"],
    areas: ["skin-hair"],
    terms: ["ahk"],
    ...cosmeticStd,
  }),
  entry({
    slug: "hydrolyzed-keratin",
    name: "Hydrolyzed keratin",
    kind: "cosmetic",
    peptideClass: "Hydrolyzed protein (not a discrete therapeutic peptide)",
    structure: "Mixture of keratin-derived peptides and amino acids.",
    what: "Hair- and nail-care protein hydrolysate.",
    how: "Film-forming and moisture-binding on hair fibre.",
    body: "Cosmetic hair surface.",
    studied: ["Hair feel and breakage appearance"],
    benefits: ["Hair-conditioning look"],
    notFor: ["Medical keratin disorders"],
    areas: ["skin-hair"],
    ...cosmeticStd,
  }),
  entry({
    slug: "hydrolyzed-silk-protein",
    name: "Hydrolyzed silk protein",
    kind: "cosmetic",
    peptideClass: "Hydrolyzed structural protein",
    structure: "Silk-derived peptide mixture.",
    what: "Cosmetic hair/skin protein hydrolysate.",
    how: "Surface conditioning.",
    body: "Topical cosmetic.",
    studied: ["Hair shine and feel"],
    benefits: ["Cosmetic silk-protein feel"],
    notFor: ["Wound medicine"],
    areas: ["skin-hair"],
    ...cosmeticStd,
  }),
  entry({
    slug: "hydrolyzed-wheat-protein",
    name: "Hydrolyzed wheat protein",
    kind: "cosmetic",
    peptideClass: "Hydrolyzed plant protein",
    structure: "Wheat-protein hydrolysate.",
    what: "Cosmetic conditioning protein. Gluten-allergic users should read labels.",
    how: "Film forming on hair/skin.",
    body: "Topical cosmetic.",
    studied: ["Hair body and moisture look"],
    benefits: ["Conditioning"],
    notFor: ["Coeliac treatment"],
    areas: ["skin-hair"],
    ...cosmeticStd,
  }),
  entry({
    slug: "collagen-amino-acids",
    name: "Collagen amino acids",
    kind: "cosmetic",
    peptideClass: "Amino-acid mixture from collagen hydrolysis",
    structure: "Free amino acids, not intact collagen protein.",
    what: "Moisturising cosmetic ingredient. Not the same as eating collagen or injecting collagen.",
    how: "Humectant / NMF-like contribution.",
    body: "Skin surface hydration look.",
    studied: ["Skin feel"],
    benefits: ["Moisture look"],
    notFor: ["Rebuilding dermal collagen as a drug"],
    areas: ["skin-hair"],
    ...cosmeticStd,
  }),
  entry({
    slug: "rigin",
    name: "Palmitoyl tetrapeptide-7 (Rigin)",
    aliases: ["Rigin"],
    kind: "cosmetic",
    peptideClass: "Cosmetic tetrapeptide",
    structure: "Palmitoyl tetrapeptide-7, often paired in Matrixyl 3000.",
    what: "Cosmetic peptide for the look of calmer, denser-looking skin.",
    how: "Interleukin-related marketing narratives — cosmetic grade.",
    body: "Topical.",
    studied: ["Skin appearance"],
    benefits: ["Look of soothed, denser skin"],
    notFor: ["Treating inflammatory skin disease"],
    areas: ["skin-hair"],
    ...cosmeticStd,
  }),
  entry({
    slug: "eyeliss",
    name: "Eyeliss",
    aliases: ["Dipeptide-2 + hesperidin + palmitoyl tetrapeptide-7 blend"],
    kind: "cosmetic",
    peptideClass: "Branded cosmetic peptide blend (eye area)",
    structure: "Trade blend, not a single sequence.",
    what: "Cosmetic eye-area appearance system.",
    how: "Puffiness-look marketing; not a drug for periorbital disease.",
    body: "Topical periocular cosmetic.",
    studied: ["Look of under-eye puffiness"],
    benefits: ["Cosmetic eye-area look"],
    notFor: ["Thyroid eye disease or true oedema"],
    areas: ["skin-hair"],
    ...cosmeticStd,
  }),
  entry({
    slug: "beautifeye",
    name: "Beautifeye",
    kind: "cosmetic",
    peptideClass: "Branded cosmetic active blend",
    structure: "Supplier trade blend (peptide/botanical system).",
    what: "Cosmetic eye-contour appearance ingredient.",
    how: "Manufacturer cosmetic claims.",
    body: "Topical.",
    studied: ["Eye-contour appearance"],
    benefits: ["Cosmetic eye look"],
    notFor: ["Medical ptosis"],
    areas: ["skin-hair"],
    ...cosmeticStd,
  }),
  entry({
    slug: "dermaxyl",
    name: "Dermaxyl",
    aliases: ["Palmitoyl hexapeptide-12 blend"],
    kind: "cosmetic",
    peptideClass: "Branded cosmetic ceramide/peptide system",
    structure: "Trade mixture including palmitoyl oligopeptide.",
    what: "Cosmetic wrinkle-appearance active.",
    how: "Lipid + peptide cosmetic narrative.",
    body: "Topical.",
    studied: ["Wrinkle look"],
    benefits: ["Smoothness look"],
    notFor: ["Medical resurfacing"],
    areas: ["skin-hair"],
    ...cosmeticStd,
  }),
  entry({
    slug: "idealift",
    name: "Idealift",
    aliases: ["N-acetyl-tyrosyl-arginyl-hexadecyl ester"],
    kind: "cosmetic",
    peptideClass: "Lipopeptide cosmetic active",
    structure: "Lipidated dipeptide ester (trade: Idealift).",
    what: "Cosmetic for the look of sagging skin.",
    how: "Elastin-related marketing.",
    body: "Topical.",
    studied: ["Jawline/firmness appearance"],
    benefits: ["Look of lift"],
    notFor: ["Surgical laxity"],
    areas: ["skin-hair", "healthy-ageing"],
    ...cosmeticStd,
  }),
  entry({
    slug: "sepiwhite-msh",
    name: "Undecylenoyl phenylalanine (Sepiwhite MSH)",
    aliases: ["Sepiwhite MSH"],
    kind: "cosmetic",
    peptideClass: "Amino-acid derivative (MSH-pathway cosmetic) — not a classic peptide drug",
    structure: "Lipidated phenylalanine derivative.",
    what: "Cosmetic brightening ingredient acting on melanogenesis pathways. Not a peptide medicine.",
    how: "Proposed MSH-receptor antagonism in melanocytes — cosmetic use.",
    body: "Topical pigment-appearance.",
    studied: ["Look of uneven tone"],
    benefits: ["Cosmetic brightness look"],
    notFor: ["Melasma as unsupervised drug therapy"],
    areas: ["skin-hair"],
    terms: ["sepiwhite", "brightening"],
    ...cosmeticStd,
  }),
  entry({
    slug: "tesamorelin",
    name: "Tesamorelin",
    aliases: ["Egrifta"],
    kind: "approved",
    peptideClass: "GHRH analogue (prescription medicine in labelled indications)",
    structure: "Stabilised 44-amino-acid GHRH analogue.",
    what: "A prescription peptide medicine for HIV-associated lipodystrophy in some markets. Grey-market ‘tesamorelin 5 mg vials’ are not that product. Cellular Sequence does not sell tesamorelin.",
    how: "Stimulates pituitary GH release via GHRH receptors.",
    body: "Raises GH/IGF-1 under medical supervision in labelled disease.",
    studied: ["HIV-associated visceral adiposity (labelled)"],
    benefits: ["Labelled reduction of excess abdominal fat in indicated patients"],
    notFor: ["Cosmetic body recomposition", "Anti-ageing clinics without an approved product"],
    human: "Registration-quality trials exist for the labelled indication.",
    pre: "GHRH pharmacology is established.",
    sides: "GH-axis effects: oedema, glucose changes, injection-site reactions. Unregulated vials add contamination risk.",
    contra: "Not for self-administration. Malignancy history is a clinical concern for GH-axis drugs.",
    reg: "Approved in some jurisdictions (e.g. FDA Egrifta) for a specific indication.",
    au: "Not offered here. Check ARTG before assuming Australian availability. Not a shop SKU.",
    areas: ["metabolic", "healthy-ageing"],
    terms: ["egrifta", "ghrh"],
    sell: false,
  }),
  entry({
    slug: "retatrutide",
    name: "Retatrutide",
    aliases: ["LY3437943"],
    kind: "investigational",
    peptideClass: "Triple GIP/GLP-1/glucagon receptor agonist (investigational)",
    structure: "Engineered peptide with activity at three metabolic receptors; fatty-acid modification for duration.",
    what: "An investigational obesity/diabetes peptide — not an approved Australian medicine and not sold by this shop.",
    how: "Agonism at GIP, GLP-1 and glucagon receptors.",
    body: "Would be expected to affect appetite, glycaemia and energy expenditure if used as a registered drug — it is not one here.",
    studied: ["Obesity and type 2 diabetes clinical development"],
    benefits: ["Being researched; not an approved consumer benefit"],
    notFor: ["DIY compounding from research vials"],
    human: "Phase 2/3 programmes are underway or reported; not a basis for grey-market use.",
    pre: "Triple-agonist animal models exist.",
    sides: "GI class effects likely; unregulated products are unsafe by default.",
    contra: "Not for human use outside trials / licensed products.",
    reg: "Not approved as of this encyclopaedia entry.",
    au: "Not ARTG-registered as a consumer or listed medicine. Educational only.",
    areas: ["metabolic"],
    terms: ["ly3437943", "triple agonist"],
    sell: false,
  }),
  entry({
    slug: "cagrilintide",
    name: "Cagrilintide",
    kind: "investigational",
    peptideClass: "Long-acting amylin analogue (investigational)",
    structure: "Acylated amylin analogue designed for once-weekly development programmes.",
    what: "Investigational metabolic peptide, often studied with semaglutide. Not sold here.",
    how: "Amylin-receptor agonism affecting satiety and gastric emptying.",
    body: "Experimental metabolic pharmacology.",
    studied: ["Obesity (with/without incretins)"],
    benefits: ["Research only"],
    notFor: ["Home stacking with research semaglutide"],
    human: "Clinical development exists; not an approved stand-alone shop product.",
    pre: "Amylin biology is established.",
    sides: "Nausea and GI effects expected in class.",
    contra: "Not for unapproved human use.",
    reg: "Investigational.",
    au: "Not an ARTG weight-loss medicine. Educational only.",
    areas: ["metabolic"],
    sell: false,
  }),
  entry({
    slug: "mazdutide",
    name: "Mazdutide",
    kind: "investigational",
    peptideClass: "GLP-1/glucagon dual agonist (investigational)",
    structure: "Oxyntomodulin-inspired dual agonist in clinical development.",
    what: "Investigational metabolic peptide. Not sold.",
    how: "GLP-1 and glucagon receptor activity.",
    body: "Experimental.",
    studied: ["Obesity, diabetes (development)"],
    benefits: ["None approved here"],
    notFor: ["Grey-market vials"],
    human: "Development-stage human data.",
    pre: "Dual-agonist models.",
    sides: "GI and metabolic class effects.",
    contra: "Not for unapproved use.",
    reg: "Investigational / regionally developing.",
    au: "Not sold. Educational.",
    areas: ["metabolic"],
    sell: false,
  }),
  entry({
    slug: "survodutide",
    name: "Survodutide",
    kind: "investigational",
    peptideClass: "GLP-1/glucagon dual agonist (investigational)",
    structure: "Peptide dual agonist in metabolic/NASH development.",
    what: "Investigational. Not a shop product.",
    how: "Incretin + glucagon receptor activity.",
    body: "Experimental.",
    studied: ["Obesity, liver-fat programmes"],
    benefits: ["None approved here"],
    notFor: ["Self-experimentation"],
    human: "Clinical development.",
    pre: "Animal metabolic models.",
    sides: "GI class effects.",
    contra: "Not for unapproved human use.",
    reg: "Investigational.",
    au: "Educational only.",
    areas: ["metabolic"],
    sell: false,
  }),
  entry({
    slug: "bremelanotide",
    name: "Bremelanotide (PT-141)",
    aliases: ["PT-141", "Vyleesi"],
    kind: "approved",
    peptideClass: "Melanocortin receptor agonist",
    structure: "Cyclic heptapeptide related to melanotan chemistry, developed as a sexual-dysfunction medicine in some markets.",
    what: "A prescription melanocortin peptide in some countries for hypoactive sexual desire disorder. It is not a tanning product. Melanotan-II is a different, unapproved tanning peptide. Not sold here.",
    how: "Central melanocortin receptor agonism.",
    body: "Affects sexual-response pathways in labelled use; also causes nausea and blood-pressure changes.",
    studied: ["HSDD (labelled in some markets)"],
    benefits: ["Labelled sexual-desire indication where approved"],
    notFor: ["Tanning", "Performance enhancement"],
    human: "Registration data exist for branded bremelanotide in specific markets.",
    pre: "Melanocortin biology.",
    sides: "Nausea, flushing, transient hypertension. Unregulated PT-141 vials are not the licensed product.",
    contra: "Cardiovascular cautions as per Product Information. Not for grey-market use.",
    reg: "Approved in some jurisdictions as Vyleesi; PT-141 research vials are unapproved.",
    au: "Not sold. Confirm ARTG before assuming availability. Distinct from Melanotan II.",
    areas: ["performance"],
    terms: ["pt-141", "pt141", "vyleesi"],
    sell: false,
  }),
  entry({
    slug: "mots-c",
    name: "MOTS-c",
    kind: "research",
    peptideClass: "Mitochondrial-derived peptide (research only)",
    structure: "16-amino-acid peptide encoded in mitochondrial 12S rRNA (MOTS-c).",
    what: "A research peptide in metabolic and exercise biology. Not an approved medicine. Not sold.",
    how: "Proposed effects on folate-methionine metabolism and AMPK-related pathways in models.",
    body: "Human pharmacology as a drug is not established to registration standard.",
    studied: ["Exercise and insulin-sensitivity models (mostly preclinical)"],
    benefits: ["Being researched — no approved benefit"],
    notFor: ["DIY metabolic enhancement"],
    human: "Limited high-quality clinical data.",
    pre: "Growing rodent literature; do not over-translate.",
    sides: "Unknown long-term; unregulated injectables are unsafe.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Not ARTG. Educational only. COAs from grey-market vendors do not make a product lawful to supply as a medicine.",
    areas: ["metabolic", "healthy-ageing", "performance"],
    terms: ["motsc", "mitochondrial peptide"],
    sell: false,
  }),
  entry({
    slug: "dsip",
    name: "DSIP",
    aliases: ["Delta sleep-inducing peptide"],
    kind: "research",
    peptideClass: "Nonapeptide (research only)",
    structure: "Trp-Ala-Gly-Gly-Asp-Ala-Ser-Gly-Glu.",
    what: "A historically studied sleep-related peptide. Not an approved hypnotic. Not sold.",
    how: "Proposed neuromodulatory effects; mechanism remains unsettled.",
    body: "Not a registered sleep medicine.",
    studied: ["Experimental sleep research"],
    benefits: ["None approved"],
    notFor: ["Insomnia self-treatment"],
    human: "Older, limited clinical literature; not practice-changing.",
    pre: "Animal sleep models.",
    sides: "Poorly characterised in unregulated use.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational only.",
    areas: ["cognitive"],
    sell: false,
  }),
  entry({
    slug: "kpv",
    name: "KPV",
    aliases: ["Lys-Pro-Val", "α-MSH fragment"],
    kind: "research",
    peptideClass: "Tripeptide MSH fragment (research / some topical cosmetics elsewhere)",
    structure: "Lys-Pro-Val, C-terminal fragment of α-MSH.",
    what: "A short melanocortin fragment studied for inflammation models. Injectable research KPV is not an approved medicine and is not sold here. Topical cosmetic use, if any, would be a separate finished product with cosmetic claims only.",
    how: "Proposed melanocortin anti-inflammatory signalling in models.",
    body: "Not characterised as a registered anti-inflammatory drug.",
    studied: ["Experimental gut and skin inflammation models"],
    benefits: ["Research interest only"],
    notFor: ["Treating IBD or eczema with grey-market vials"],
    human: "Inadequate registration-quality data for drug use.",
    pre: "Preclinical inflammation models.",
    sides: "Unknown for unregulated injectables.",
    contra: "Not for unapproved injection.",
    reg: "Not approved as a medicine.",
    au: "Not sold as a research vial. Educational.",
    areas: ["recovery", "skin-hair"],
    sell: false,
  }),
  entry({
    slug: "5-amino-1mq",
    name: "5-Amino-1MQ",
    aliases: ["5-amino-1-methylquinolinium"],
    kind: "research",
    peptideClass: "Small-molecule NNMT inhibitor — not a peptide",
    structure: "Methylquinolinium derivative (non-peptide).",
    what: "A research small molecule appearing on peptide vendor lists. It is not a peptide and not an approved fat-loss drug. Not sold.",
    how: "Proposed nicotinamide N-methyltransferase (NNMT) inhibition in models.",
    body: "Not a registered medicine.",
    studied: ["Experimental adiposity models"],
    benefits: ["None approved"],
    notFor: ["Weight-loss self-experimentation"],
    human: "Lacks approved-drug evidence.",
    pre: "NNMT literature in animals/cells.",
    sides: "Unknown; quality of grey-market powder/vials is a risk.",
    contra: "Not for human use.",
    reg: "Not an approved medicine.",
    au: "Educational listing because it appears on peptide price lists. Not sold.",
    areas: ["metabolic"],
    terms: ["5amino", "nnmt"],
    sell: false,
  }),
  entry({
    slug: "ss-31",
    name: "Elamipretide (SS-31)",
    aliases: ["SS-31", "Bendavia"],
    kind: "investigational",
    peptideClass: "Mitochondria-targeted tetrapeptide (investigational)",
    structure: "D-Arg-Dmt-Lys-Phe-NH2 (SS-31 / elamipretide).",
    what: "Investigational mitochondria-targeted peptide. Not sold.",
    how: "Associates with cardiolipin; studied for bioenergetic effects.",
    body: "Not an approved Australian mitochondrial medicine.",
    studied: ["Mitochondrial myopathy and cardiac programmes (development)"],
    benefits: ["Being researched"],
    notFor: ["Wellness injections"],
    human: "Clinical development with mixed/ongoing programmes.",
    pre: "Extensive mitochondrial-model literature.",
    sides: "As per trial literature; unregulated vials unsafe.",
    contra: "Not for unapproved use.",
    reg: "Investigational in most settings.",
    au: "Educational only.",
    areas: ["healthy-ageing", "recovery"],
    terms: ["elamipretide", "ss31"],
    sell: false,
  }),
  entry({
    slug: "ghrp-2",
    name: "GHRP-2",
    aliases: ["Pralmorelin", "GHRP2"],
    kind: "research",
    peptideClass: "Ghrelin-receptor agonist / GH secretagogue (research only)",
    structure: "Hexapeptide GH secretagogue.",
    what: "Unapproved GH secretagogue. Not sold. Banned in sport.",
    how: "GHS-R1a agonism.",
    body: "Would raise GH pulses if bioactive — inappropriate without specialist care and not approved.",
    studied: ["Diagnostic/experimental GH secretion"],
    benefits: ["None approved for wellness"],
    notFor: ["Bodybuilding"],
    human: "Some clinical/diagnostic history; not an anti-ageing registration.",
    pre: "Classic GHRP pharmacology.",
    sides: "GH-axis effects; cortisol/appetite class effects.",
    contra: "Not for human wellness use. Malignancy caution for GH axis.",
    reg: "Not approved as an anti-ageing drug.",
    au: "Not ARTG for this use. Educational.",
    areas: ["performance", "healthy-ageing"],
    sell: false,
  }),
  entry({
    slug: "ghrp-6",
    name: "GHRP-6",
    kind: "research",
    peptideClass: "Ghrelin-receptor agonist (research only)",
    structure: "Hexapeptide GH secretagogue with strong orexigenic effect.",
    what: "Unapproved secretagogue. Not sold.",
    how: "GHS-R1a agonism; notable hunger signalling.",
    body: "Experimental GH/appetite pharmacology.",
    studied: ["Experimental GH release"],
    benefits: ["None approved"],
    notFor: ["Appetite hacking or physique use"],
    human: "Limited; not a registered wellness drug.",
    pre: "Established GHRP class.",
    sides: "Hunger, GH-axis effects, unregulated product risk.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational only.",
    areas: ["performance"],
    sell: false,
  }),
  entry({
    slug: "sermorelin",
    name: "Sermorelin",
    aliases: ["GRF 1-29"],
    kind: "research",
    peptideClass: "GHRH (1–29) analogue",
    structure: "GHRH fragment 1–29.",
    what: "Formerly used diagnostically/therapeutically in some settings; not a current consumer anti-ageing medicine here. Not sold.",
    how: "GHRH receptor agonism.",
    body: "GH pulse stimulation if bioactive.",
    studied: ["GH deficiency diagnostics historically"],
    benefits: ["None as a shop wellness product"],
    notFor: ["Anti-ageing vials"],
    human: "Historical clinical use; not a licence to grey-market compound.",
    pre: "GHRH fragment pharmacology.",
    sides: "GH-axis effects.",
    contra: "Not for unapproved use.",
    reg: "Not offered as a consumer peptide.",
    au: "Educational only.",
    areas: ["healthy-ageing"],
    sell: false,
  }),
  entry({
    slug: "hexarelin",
    name: "Hexarelin",
    kind: "research",
    peptideClass: "GH secretagogue (research only)",
    structure: "Hexapeptide GHRP analogue.",
    what: "Unapproved secretagogue. Not sold.",
    how: "GHS-R1a.",
    body: "Experimental.",
    studied: ["Experimental cardioprotection/GH papers"],
    benefits: ["None approved"],
    notFor: ["Heart disease self-treatment"],
    human: "Limited.",
    pre: "GHRP class plus cardiac models.",
    sides: "GH-axis and unknown impurities.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational.",
    areas: ["performance"],
    sell: false,
  }),
  entry({
    slug: "igf-1-lr3",
    name: "IGF-1 LR3",
    kind: "research",
    peptideClass: "Long-acting IGF-1 analogue (research only)",
    structure: "IGF-1 with Arg3 substitution and N-terminal extension (LR3).",
    what: "Potent growth-factor analogue. Not approved for physique or anti-ageing. Not sold. High medical risk.",
    how: "IGF-1 receptor agonism with altered binding proteins.",
    body: "Would affect growth, glucose and potentially tumours — exactly why unregulated use is inappropriate.",
    studied: ["Experimental growth-factor biology"],
    benefits: ["None approved for consumers"],
    notFor: ["Bodybuilding", "‘Healing IGF’ protocols"],
    human: "Not a registered lifestyle medicine.",
    pre: "IGF-1 receptor biology is real and serious.",
    sides: "Hypoglycaemia, oedema, theoretical tumour-promotion. WADA prohibited.",
    contra: "Not for human use. Malignancy.",
    reg: "Not approved for these grey-market uses.",
    au: "Educational warning entry.",
    areas: ["performance"],
    terms: ["igf1", "long r3"],
    sell: false,
  }),
  entry({
    slug: "igf-des",
    name: "IGF-1 DES",
    kind: "research",
    peptideClass: "Truncated IGF-1 analogue (research only)",
    structure: "Des(1-3) IGF-1.",
    what: "Research growth-factor analogue. Not sold.",
    how: "IGF-1 receptor; reduced IGFBP binding.",
    body: "Experimental. High risk class.",
    studied: ["Experimental local tissue models"],
    benefits: ["None approved"],
    notFor: ["Site enhancement"],
    human: "Not an approved drug for this use.",
    pre: "IGF literature.",
    sides: "Growth-factor risks; unregulated products.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational warning.",
    areas: ["performance"],
    sell: false,
  }),
  entry({
    slug: "peg-mgf",
    name: "PEG-MGF",
    aliases: ["Pegylated mechano growth factor"],
    kind: "research",
    peptideClass: "Pegylated IGF-1 splice analogue (research only)",
    structure: "Pegylated MGF / IGF-1 Ec related sequence.",
    what: "Research compound. Not sold.",
    how: "Proposed muscle-repair signalling; evidence quality is poor for practice.",
    body: "Unknown as a quality-controlled human drug.",
    studied: ["Experimental muscle biology"],
    benefits: ["None approved"],
    notFor: ["Injury shortcuts"],
    human: "Lacking.",
    pre: "MGF hypotheses.",
    sides: "Unknown + contamination.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational.",
    areas: ["recovery", "performance"],
    sell: false,
  }),
  entry({
    slug: "follistatin",
    name: "Follistatin (research preparations)",
    kind: "research",
    peptideClass: "Activin/myostatin-binding glycoprotein (research only)",
    structure: "Not a simple short peptide; recombinant follistatin preparations appear on vendor lists.",
    what: "Myostatin-pathway research agent. Not an approved muscle drug. Not sold.",
    how: "Binds activin/myostatin family ligands.",
    body: "Would affect muscle regulation if bioactive — high theoretical risk.",
    studied: ["Experimental myostatin biology"],
    benefits: ["None approved"],
    notFor: ["Muscle enhancement"],
    human: "Not a registered athletic medicine.",
    pre: "Myostatin pathway is real.",
    sides: "Unknown; prohibited in sport.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational warning.",
    areas: ["performance"],
    sell: false,
  }),
  entry({
    slug: "foxo4-dri",
    name: "FOXO4-DRI",
    kind: "research",
    peptideClass: "D-retro-inverso peptide (senolytic research)",
    structure: "Synthetic D-peptide designed to perturb FOXO4–p53 interaction in research.",
    what: "Experimental senolytic-concept peptide. Not an approved longevity drug. Not sold.",
    how: "Proposed disruption of FOXO4-p53 in senescent-cell models.",
    body: "Not a human-registered senolytic.",
    studied: ["Cellular senescence models"],
    benefits: ["None approved"],
    notFor: ["Longevity injections"],
    human: "Inadequate.",
    pre: "High-profile but limited-replication space — treat cautiously.",
    sides: "Unknown; theoretically significant.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational warning.",
    areas: ["healthy-ageing"],
    terms: ["foxo4"],
    sell: false,
  }),
  entry({
    slug: "thymosin-alpha-1",
    name: "Thymosin alpha-1",
    aliases: ["Thymalfasin", "Zadaxin"],
    kind: "approved",
    peptideClass: "Immunomodulatory peptide (registered in some countries, not a wellness SKU here)",
    structure: "28-amino-acid N-acetylated peptide from prothymosin α.",
    what: "A peptide medicine in some jurisdictions for specific indications. Grey-market TA1 vials are not those products. Not sold here.",
    how: "T-cell and innate-immune signalling hypotheses.",
    body: "Immunomodulatory — not a gym supplement.",
    studied: ["Labelled infectious/immune indications where registered"],
    benefits: ["Only as labelled medicines"],
    notFor: ["Immune ‘boosting’ without a prescriber"],
    human: "Registered in some countries; not a licence for unapproved compounding.",
    pre: "Thymic peptide literature.",
    sides: "As per labelled product; unregulated vials unsafe.",
    contra: "Not for self-injection.",
    reg: "Approved in some markets (e.g. thymalfasin) for specified uses.",
    au: "Not a Cellular Sequence shop product. Check ARTG.",
    areas: ["recovery"],
    terms: ["zadaxin", "thymalfasin"],
    sell: false,
  }),
  entry({
    slug: "thymalin",
    name: "Thymalin",
    kind: "research",
    peptideClass: "Thymic peptide preparation (research / regional literature)",
    structure: "Thymic peptide complex / related sequences in Russian gerontology literature.",
    what: "Not an ICH-standard approved longevity medicine. Not sold.",
    how: "Proposed immune-ageing effects — evidence grade is limited.",
    body: "Unproven as consumer therapy.",
    studied: ["Experimental immunogerontology"],
    benefits: ["None approved here"],
    notFor: ["DIY immune peptides"],
    human: "Regional literature; not TGA-evaluated.",
    pre: "Thymic peptide models.",
    sides: "Unknown unregulated quality.",
    contra: "Not for human use here.",
    reg: "Not a global approved wellness drug.",
    au: "Educational.",
    areas: ["healthy-ageing"],
    sell: false,
  }),
  entry({
    slug: "ll-37",
    name: "LL-37",
    aliases: ["Cathelicidin antimicrobial peptide"],
    kind: "research",
    peptideClass: "Host-defence peptide (research only)",
    structure: "37-amino-acid human cathelicidin peptide.",
    what: "Endogenous antimicrobial peptide studied as a drug candidate. Not approved for injection. Not sold.",
    how: "Membrane disruption of microbes; immunomodulation — also cytotoxic risk.",
    body: "Not a registered antibiotic substitute.",
    studied: ["Infection and inflammation research"],
    benefits: ["None approved for consumers"],
    notFor: ["DIY infection treatment"],
    human: "Not an approved consumer medicine.",
    pre: "Extensive AMP literature.",
    sides: "Potential cytotoxicity; unregulated vials dangerous.",
    contra: "Not for human use.",
    reg: "Not approved for this supply channel.",
    au: "Educational warning.",
    areas: ["recovery"],
    sell: false,
  }),
  entry({
    slug: "kisspeptin-10",
    name: "Kisspeptin-10",
    kind: "research",
    peptideClass: "Kp-10 fragment (research / specialist endocrine research)",
    structure: "C-terminal 10-amino-acid kisspeptin fragment.",
    what: "Reproductive-axis research peptide. Not an approved fertility consumer product. Not sold.",
    how: "GPR54 / KISS1R agonism affecting GnRH.",
    body: "Would perturb HPG axis if bioactive.",
    studied: ["Reproductive endocrinology research"],
    benefits: ["None as a shop SKU"],
    notFor: ["DIY testosterone or fertility hacks"],
    human: "Specialist research; not grey-market appropriate.",
    pre: "Kisspeptin biology is established.",
    sides: "Hormonal axis disruption.",
    contra: "Not for unapproved use. Pregnancy-related cautions.",
    reg: "Not approved as a wellness peptide.",
    au: "Educational.",
    areas: ["performance"],
    sell: false,
  }),
  entry({
    slug: "melanotan-i",
    name: "Melanotan I",
    aliases: ["Afamelanotide related chemistry / MT-1", "NDP-MSH analogue"],
    kind: "research",
    peptideClass: "Linear α-MSH analogue (research / distinct from approved afamelanotide implants)",
    structure: "[Nle4, D-Phe7]-α-MSH related analogue (MT-1).",
    what: "Unapproved tanning analogue. Licensed afamelanotide (Scenesse) is a different, restricted medicine for EPP — not a tanning vial. Not sold.",
    how: "MC1R agonism increases eumelanin.",
    body: "Pigmentation pharmacology with systemic melanocortin risks.",
    studied: ["Pigmentation biology; EPP medicine is a separate product"],
    benefits: ["None that justify illicit tanning"],
    notFor: ["Safe tanning"],
    human: "Afamelanotide is a specialised approved implant in some markets; MT-1 vials are not that product.",
    pre: "MSH pigmentation biology.",
    sides: "Nausea, mole changes, blood-pressure effects.",
    contra: "Not for tanning. Melanoma-risk caution.",
    reg: "Grey-market MT-1 not approved.",
    au: "Educational warning. TGA has warned on melanotan-type products.",
    areas: ["skin-hair"],
    terms: ["mt-1", "mt1", "afamelanotide"],
    sell: false,
  }),
  entry({
    slug: "ara-290",
    name: "Cibinetide (ARA-290)",
    aliases: ["ARA-290"],
    kind: "investigational",
    peptideClass: "Innate-repair receptor peptide (investigational)",
    structure: "11-amino-acid EPO-derived peptide without erythropoietic activity in design intent.",
    what: "Investigational neuropathy/repair peptide. Not EPO. Not sold.",
    how: "Proposed IRAK/innate repair receptor signalling.",
    body: "Not an approved EPO substitute.",
    studied: ["Sarcoid neuropathy and other programmes"],
    benefits: ["Being researched"],
    notFor: ["Blood doping"],
    human: "Clinical development; not a shop medicine.",
    pre: "Tissue-repair models.",
    sides: "As per trials; unregulated vials unsafe.",
    contra: "Not for unapproved use.",
    reg: "Investigational.",
    au: "Educational.",
    areas: ["recovery"],
    sell: false,
  }),
  entry({
    slug: "aicar",
    name: "AICAR (acadesine)",
    kind: "research",
    peptideClass: "AMPK-activating nucleoside analogue — not a peptide",
    structure: "5-Aminoimidazole-4-carboxamide ribonucleotide.",
    what: "Appears on peptide vendor lists. It is not a peptide. WADA-prohibited metabolic modulator. Not sold.",
    how: "AMPK activation in models.",
    body: "Not an exercise mimetic medicine.",
    studied: ["Experimental metabolism and ischaemia"],
    benefits: ["None approved for athletes"],
    notFor: ["Endurance doping"],
    human: "Not approved for this use.",
    pre: "AMPK literature.",
    sides: "Metabolic perturbation; prohibited in sport.",
    contra: "Not for human enhancement.",
    reg: "Not an approved lifestyle drug.",
    au: "Educational because it is on peptide invoices. Not sold.",
    areas: ["performance"],
    terms: ["acadesine"],
    sell: false,
  }),
  entry({
    slug: "slu-pp-332",
    name: "SLU-PP-332",
    kind: "research",
    peptideClass: "ERR agonist small molecule — not a peptide",
    structure: "Synthetic ERR pan-agonist (research chemical).",
    what: "Exercise-mimetic research small molecule on some peptide lists. Not a peptide. Not sold.",
    how: "Estrogen-related receptor agonism in models.",
    body: "Not an approved drug.",
    studied: ["Experimental metabolic/exercise biology"],
    benefits: ["None approved"],
    notFor: ["Fat-loss research chemicals"],
    human: "Lacking approved evidence.",
    pre: "Emerging ERR literature.",
    sides: "Unknown.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational only.",
    areas: ["metabolic", "performance"],
    terms: ["slupp332", "pp332"],
    sell: false,
  }),
  entry({
    slug: "pnc-27",
    name: "PNC-27",
    kind: "research",
    peptideClass: "p53-derived chimeric peptide (research only)",
    structure: "p53 HDM-2 binding region fused to a membrane-penetrating sequence in research descriptions.",
    what: "Experimental anticancer-concept peptide. Not an approved oncology drug. Not sold. Extremely inappropriate as a wellness vial.",
    how: "Proposed membrane effects on HDM-2-expressing cells in models.",
    body: "Not a cancer treatment you can buy online.",
    studied: ["Experimental oncology models"],
    benefits: ["None approved"],
    notFor: ["Cancer self-treatment"],
    human: "Not an approved therapy.",
    pre: "Controversial/limited literature — not a treatment protocol.",
    sides: "Unknown; delay of real oncology care is itself harm.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational warning.",
    areas: ["recovery"],
    sell: false,
  }),
  entry({
    slug: "adipotide",
    name: "Adipotide (prohibitin-targeting peptide)",
    aliases: ["FTPP", "CKGGRAKDC-GG-D(KLAKLAK)2"],
    kind: "research",
    peptideClass: "Targeted pro-apoptotic peptidomimetic (research only)",
    structure: "Chimeric peptide designed to target white-fat vasculature in animal work.",
    what: "Experimental fat-loss research agent with serious toxicity signals in animals. Not sold.",
    how: "Proposed targeting of prohibitin in adipose vessels.",
    body: "Renal toxicity reported in animal studies — not a cosmetic.",
    studied: ["Experimental adipose ablation in animals"],
    benefits: ["None that justify human use"],
    notFor: ["Weight loss"],
    human: "Not an approved drug; safety concerns.",
    pre: "Animal obesity models with toxicity.",
    sides: "Kidney injury signals in animals.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational warning.",
    areas: ["metabolic"],
    sell: false,
  }),
  entry({
    slug: "vip",
    name: "Vasoactive intestinal peptide (VIP)",
    kind: "research",
    peptideClass: "Neuropeptide (research / specialised medicine elsewhere)",
    structure: "28-amino-acid amidated peptide.",
    what: "Endogenous neuropeptide. Not a wellness inhaler/vial from this shop.",
    how: "VPAC receptor signalling (vasodilation, immune, circadian).",
    body: "Potent physiology — not DIY.",
    studied: ["Pulmonary and neuroimmune research"],
    benefits: ["None as a consumer SKU"],
    notFor: ["Unsupervised immune protocols"],
    human: "Specialist contexts only.",
    pre: "Classic neuropeptide biology.",
    sides: "Hypotension, flushing possible in class.",
    contra: "Not for unapproved use.",
    reg: "Not a shop product.",
    au: "Educational.",
    areas: ["cognitive", "recovery"],
    sell: false,
  }),
  entry({
    slug: "dermorphin",
    name: "Dermorphin",
    kind: "research",
    peptideClass: "Opioid heptapeptide (research only)",
    structure: "Tyr-D-Ala-Phe-Gly-Tyr-Pro-Ser-NH2 from amphibian skin.",
    what: "Extremely potent μ-opioid peptide. Not an approved analgesic here. Not sold. High harm potential.",
    how: "μ-opioid receptor agonism.",
    body: "Opioid pharmacology — respiratory depression risk.",
    studied: ["Experimental analgesia"],
    benefits: ["None that belong on a consumer peptide menu"],
    notFor: ["Pain self-treatment"],
    human: "Not an approved product in this channel.",
    pre: "Opioid peptide literature.",
    sides: "Opioid toxicities including respiratory depression.",
    contra: "Not for human use. Controlled-substance risk depending on jurisdiction.",
    reg: "Not approved for this supply.",
    au: "Educational warning. Not sold.",
    areas: ["recovery"],
    sell: false,
  }),
  entry({
    slug: "pinealon",
    name: "Pinealon",
    aliases: ["Glu-Asp-Arg"],
    kind: "research",
    peptideClass: "Synthetic tripeptide (gerontology research literature)",
    structure: "Glu-Asp-Arg.",
    what: "Short peptide from pineal/gerontology research lines. Not approved. Not sold.",
    how: "Proposed CNS/pineal signalling — weak evidence grade.",
    body: "Unproven.",
    studied: ["Experimental neurogerontology"],
    benefits: ["None approved"],
    notFor: ["Nootropic self-injection"],
    human: "Limited non-ICH literature.",
    pre: "Small-peptide ageing papers — caution.",
    sides: "Unknown.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational.",
    areas: ["cognitive", "healthy-ageing"],
    sell: false,
  }),
  entry({
    slug: "cartalax",
    name: "Cartalax",
    kind: "research",
    peptideClass: "Short bioregulatory peptide (research literature)",
    structure: "Ala-Glu-Asp claimed cartilage-bioregulator sequence in supplier lists.",
    what: "Not an approved osteoarthritis medicine. Not sold.",
    how: "Unproven bioregulator claims.",
    body: "Unproven.",
    studied: ["Experimental connective-tissue marketing literature"],
    benefits: ["None approved"],
    notFor: ["Joint disease self-treatment"],
    human: "Inadequate.",
    pre: "Weak/limited.",
    sides: "Unknown.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational.",
    areas: ["recovery"],
    sell: false,
  }),
  entry({
    slug: "adamax",
    name: "Adamax",
    kind: "research",
    peptideClass: "Semax analogue (research only)",
    structure: "N-acetyl / adamantane-modified Semax analogue in grey-market naming.",
    what: "Unapproved nootropic analogue. Not sold.",
    how: "Putative ACTH-fragment / BDNF narratives — not established as a medicine.",
    body: "Unknown quality.",
    studied: ["Experimental nootropic forums — not evidence"],
    benefits: ["None approved"],
    notFor: ["Cognitive enhancement injections"],
    human: "Lacking.",
    pre: "Semax-related speculation.",
    sides: "Unknown.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational.",
    areas: ["cognitive"],
    sell: false,
  }),
  entry({
    slug: "pe-22-28",
    name: "PE-22-28",
    aliases: ["Mini-spadin"],
    kind: "research",
    peptideClass: "TREK-1 related peptide fragment (research only)",
    structure: "Short spadin-related peptide in research-chemical catalogues.",
    what: "Experimental CNS peptide. Not an approved antidepressant. Not sold.",
    how: "Proposed TREK-1 potassium-channel modulation.",
    body: "Not a registered psychotropic.",
    studied: ["Experimental depression models"],
    benefits: ["None approved"],
    notFor: ["Mental-health self-treatment"],
    human: "Lacking.",
    pre: "Limited.",
    sides: "Unknown.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational.",
    areas: ["cognitive"],
    sell: false,
  }),
  entry({
    slug: "somatropin",
    name: "Somatropin (hGH 191AA)",
    aliases: ["Human growth hormone", "rhGH"],
    kind: "approved",
    peptideClass: "Recombinant GH (prescription medicine)",
    structure: "191-amino-acid human GH protein.",
    what: "A prescription protein hormone for documented GH deficiency and other labelled indications. Grey-market ‘HGH 191AA’ vials are illicit in ordinary wellness commerce. Not sold.",
    how: "GH receptor agonism; IGF-1 generation.",
    body: "Anabolic/metabolic hormone — specialist endocrinology only.",
    studied: ["Paediatric and adult GHD, other labelled uses"],
    benefits: ["Only as labelled, prescribed medicine"],
    notFor: ["Anti-ageing clinics using unregulated vials", "Sport"],
    human: "Extensive for registered products.",
    pre: "Classic GH biology.",
    sides: "Oedema, carpal tunnel, glucose intolerance, intracranial hypertension, malignancy cautions.",
    contra: "Active malignancy; as per Product Information.",
    reg: "Approved prescription medicine in branded products.",
    au: "S8/prescription controls apply to legitimate GH. Not a shop SKU.",
    areas: ["healthy-ageing", "performance"],
    terms: ["hgh", "191aa"],
    sell: false,
  }),
  entry({
    slug: "nad-plus",
    name: "NAD+",
    aliases: ["Nicotinamide adenine dinucleotide"],
    kind: "investigational",
    peptideClass: "Dinucleotide cofactor — not a peptide",
    structure: "NAD+ cofactor, not an amino-acid chain.",
    what: "Listed on peptide invoices as injectable NAD+. IV/IM NAD+ is not an approved general wellness medicine in the way it is marketed. Not sold as a peptide vial here.",
    how: "Redox cofactor and sirtuin/PARP substrate.",
    body: "Essential biochemistry; that does not validate unregulated injections.",
    studied: ["Infusion clinics (low-quality evidence), precursor trials"],
    benefits: ["Education, not an injection SKU"],
    notFor: ["Unsupervised IV NAD+ from peptide vendors"],
    human: "Oral precursors have more trial data than boutique NAD+ drips.",
    pre: "Foundational biochemistry.",
    sides: "Infusion reactions reported anecdotally; product quality varies.",
    contra: "Not a peptide-shop product.",
    reg: "Not approved as a compounded anti-ageing injection in this model.",
    au: "Educational for injectable NAD+. The shop sells transdermal NAD+ patches — not NAD+ injections.",
    areas: ["healthy-ageing", "metabolic"],
    terms: ["nadh", "nad", "nmn"],
    sell: false,
    productHref: "/shop/nad-plus-patches",
  }),
  entry({
    slug: "oxytocin",
    name: "Oxytocin",
    aliases: ["Pitocin", "Syntocinon"],
    kind: "approved",
    peptideClass: "Nonapeptide hormone (prescription)",
    structure: "Cys-Tyr-Ile-Gln-Asn-Cys-Pro-Leu-Gly-NH2 (disulfide).",
    what: "A registered obstetric/lactation hormone in licensed products. Grey-market ‘oxytocin acetate’ vials are not those medicines. Not sold.",
    how: "Oxytocin receptor agonism (uterine, mammary, central).",
    body: "Potent physiology — not a bonding supplement.",
    studied: ["Labour, postpartum haemorrhage, lactation (labelled)"],
    benefits: ["Only as labelled medicines"],
    notFor: ["Wellness nasal sprays from peptide vendors"],
    human: "Long clinical history for licensed products.",
    pre: "Classic peptide hormone.",
    sides: "Cardiovascular and obstetric risks as per Product Information.",
    contra: "As per labelled product. Not for unapproved compounding.",
    reg: "Approved prescription hormone.",
    au: "Prescription-only in licensed presentations. Not a shop SKU.",
    areas: ["recovery"],
    sell: false,
  }),
  entry({
    slug: "chorionic-gonadotropin",
    name: "Human chorionic gonadotropin (hCG)",
    aliases: ["HCG"],
    kind: "approved",
    peptideClass: "Glycoprotein hormone (prescription) — not a short peptide",
    structure: "Heterodimeric glycoprotein.",
    what: "A prescription fertility/endocrine medicine. Peptide-shop hCG is not a lawful consumer product here. Not sold.",
    how: "LH-receptor agonism.",
    body: "Reproductive endocrine axis — specialist only.",
    studied: ["Assisted reproduction, selected hypogonadism (labelled)"],
    benefits: ["Only as labelled"],
    notFor: ["Weight-loss ‘hCG diet’", "PCT from grey-market vials"],
    human: "Registered products exist.",
    pre: "Classic gonadotropin biology.",
    sides: "OHSS, thromboembolism risk in fertility use; unregulated vials add contamination.",
    contra: "As per Product Information. Not for unapproved use.",
    reg: "Approved prescription medicine in branded products.",
    au: "Not a shop SKU. Educational because it appears on peptide price lists.",
    areas: ["performance"],
    terms: ["hcg"],
    sell: false,
  }),
  entry({
    slug: "bpc-tb-blend",
    name: "BPC-157 / TB-500 blends",
    aliases: ["BPC 5mg + TB 5mg", "Wolverine stack"],
    kind: "research",
    peptideClass: "Unapproved peptide mixture (research only)",
    structure: "Combination vials of BPC-157 and thymosin-β4 fragments as sold on grey-market lists.",
    what: "A marketing blend of two unapproved research peptides. A COA does not make a combination lawful to supply as a medicine. Not sold.",
    how: "See individual BPC-157 and TB-500 entries — mixing does not create an approved product.",
    body: "Not characterised as a registered combination medicine.",
    studied: ["None as an approved combination"],
    benefits: ["None approved"],
    notFor: ["Injury recovery kits"],
    human: "Inadequate.",
    pre: "See parent peptides.",
    sides: "Unknown interactions plus vial-quality risk.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational only. Not in the shop.",
    areas: ["recovery"],
    terms: ["glow", "wolverine", "bb10"],
    sell: false,
  }),
  entry({
    slug: "glow-klow-blends",
    name: "GLOW / KLOW blends",
    aliases: ["BPC + TB-500 + GHK-Cu", "KLOW (adds KPV)"],
    kind: "research",
    peptideClass: "Unapproved multi-peptide mixture (research only)",
    structure: "Typical grey-market ‘GLOW’ is BPC-157 + TB-500 + GHK-Cu; ‘KLOW’ adds KPV. These are catalogue names, not pharmacopoeial products.",
    what: "Research-chemical cocktails. Injectable GHK-Cu in a blend is not a cosmetic serum. Not sold.",
    how: "No approved combined pharmacology.",
    body: "Uncharacterised mixture.",
    studied: ["None as registered medicines"],
    benefits: ["None approved"],
    notFor: ["Skin ‘glow’ injections"],
    human: "None of registration quality.",
    pre: "See parent entries.",
    sides: "Copper load, unknown impurities, unapproved actives.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational listing of vendor blend names only.",
    areas: ["skin-hair", "recovery"],
    terms: ["glow70", "klow80", "gglow"],
    sell: false,
  }),
  entry({
    slug: "cjc-ipamorelin-blend",
    name: "CJC-1295 (no DAC) + ipamorelin blends",
    aliases: ["CJC + IPA"],
    kind: "research",
    peptideClass: "Unapproved secretagogue mixture (research only)",
    structure: "Common grey-market pairing of a GHRH analogue with ipamorelin.",
    what: "Two unapproved GH-axis peptides in one vial. Not an anti-ageing medicine. Not sold. Banned in sport.",
    how: "See CJC-1295 and ipamorelin.",
    body: "Would perturb GH/IGF-1 if bioactive — inappropriate without specialist care and not approved.",
    studied: ["None as an approved combination"],
    benefits: ["None approved"],
    notFor: ["Sleep + recovery stacks"],
    human: "Inadequate as a consumer product.",
    pre: "Class pharmacology only.",
    sides: "GH-axis effects plus quality risk.",
    contra: "Not for human use. Malignancy caution.",
    reg: "Not approved.",
    au: "Educational only.",
    areas: ["healthy-ageing", "performance"],
    terms: ["cp10", "cjc ipa"],
    sell: false,
  }),
  entry({
    slug: "ace-031",
    name: "ACE-031",
    aliases: ["Ramatercept-related ActRIIB decoy"],
    kind: "research",
    peptideClass: "Activin-receptor decoy (research / halted development)",
    structure: "Soluble ActRIIB fusion protein — not a short cosmetic peptide.",
    what: "Myostatin-pathway research biologic whose development was discontinued amid safety concerns. Not sold.",
    how: "Ligand trap for myostatin/activin family.",
    body: "Would affect muscle and other TGF-β ligands if bioactive — high risk class.",
    studied: ["Experimental muscular dystrophy programmes (halted)"],
    benefits: ["None approved"],
    notFor: ["Muscle enhancement"],
    human: "Development stopped; not a consumer product.",
    pre: "Myostatin biology.",
    sides: "Bleeding and other signals reported in development.",
    contra: "Not for human use.",
    reg: "Not approved.",
    au: "Educational warning.",
    areas: ["performance"],
    sell: false,
  }),
];
