import type { Peptide } from "./types";

const notSold = {
  availableToPurchase: false as const,
  searchTerms: [] as string[],
};

export const encyclopaediaAdditions: Peptide[] = [
  {
    slug: "octreotide",
    name: "Octreotide",
    alternativeNames: ["Sandostatin"],
    peptideClass: "Somatostatin analogue",
    structure: "Cyclic octapeptide somatostatin analogue.",
    whatItIs:
      "A synthetic analogue of somatostatin used as a prescription medicine for hormone-secreting tumours and related labelled indications.",
    howItWorks:
      "Agonist at somatostatin receptors (notably sst2/sst5), suppressing GH, glucagon, insulin and various GI peptides depending on tissue.",
    whatItDoesInBody:
      "Reduces pathological hormone secretion in labelled neuroendocrine and acromegaly settings as described in product information.",
    studiedFor: ["Acromegaly", "Neuroendocrine tumours", "Variceal bleeding (product-specific)"],
    potentialBenefits: ["Labelled control of hormone syndromes — not a wellness peptide"],
    mayNotBeUsefulFor: ["Anti-ageing", "Body composition"],
    humanEvidence: "Extensive labelled clinical use; see PI and oncology/endocrinology guidelines.",
    preclinicalEvidence: "Somatostatin receptor pharmacology is well characterised.",
    sideEffects: "GI symptoms, gallstones, glucose dysregulation, injection-site reactions — see PI.",
    contraindications: "See product information (hypersensitivity; caution in diabetes and biliary disease).",
    regulatoryStatus: "Approved prescription medicine, brand- and indication-specific (FDA/EMA).",
    australianRegulatoryStatus: "ARTG-registered presentations exist; verify current PI. Not sold by Longevity Protocol.",
    badges: ["APPROVED_MEDICINE"],
    areas: ["metabolic", "healthy-ageing"],
    ...notSold,
    primaryTarget: "Somatostatin receptors (sst2/sst5 predominant)",
    routesInvestigated: ["Subcutaneous", "Intramuscular depot", "Intravenous"],
    humanEvidenceLevel: "A",
    mechanismCertainty: "established",
    references: [
      {
        title: "Octreotide prescribing information",
        citation: "FDA / TGA Product Information for octreotide (Sandostatin and generics).",
        url: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
    ],
  },
  {
    slug: "linaclotide",
    name: "Linaclotide",
    alternativeNames: ["Linzess", "Constella"],
    peptideClass: "Guanylate cyclase-C agonist (14-amino-acid peptide)",
    structure: "Oral peptide that acts locally in the intestine with minimal systemic absorption as labelled.",
    whatItIs: "An approved oral peptide medicine for irritable bowel syndrome with constipation and chronic idiopathic constipation, as labelled.",
    howItWorks:
      "Binds guanylate cyclase-C on intestinal epithelium, increasing cGMP, chloride/bicarbonate secretion (CFTR) and reducing visceral pain signalling in labelled pharmacology.",
    whatItDoesInBody: "Increases intestinal fluid and accelerates transit in labelled CIC/IBS-C populations.",
    studiedFor: ["IBS-C", "Chronic idiopathic constipation"],
    potentialBenefits: ["Labelled GI indications only"],
    mayNotBeUsefulFor: ["Systemic peptide bodybuilding use", "Parenteral research-chemical use"],
    humanEvidence: "Phase 3 programmes support labelled GI indications.",
    preclinicalEvidence: "GC-C / cGMP pathway characterised in intestinal models.",
    sideEffects: "Diarrhoea is the principal labelled adverse effect; dehydration risk.",
    contraindications: "Paediatric boxed warning in USPI for children under 6; see PI.",
    regulatoryStatus: "Approved (FDA/EMA) for specified constipation disorders.",
    australianRegulatoryStatus: "Verify ARTG for linaclotide. Not sold here.",
    badges: ["APPROVED_MEDICINE"],
    areas: ["metabolic"],
    ...notSold,
    primaryTarget: "Guanylate cyclase-C",
    routesInvestigated: ["Oral"],
    humanEvidenceLevel: "A",
    mechanismCertainty: "established",
    searchTerms: ["ibs", "gc-c", "constipation"],
    references: [
      {
        title: "Linaclotide prescribing information",
        citation: "FDA USPI — Linzess (linaclotide).",
        url: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
    ],
  },
  {
    slug: "pramlintide",
    name: "Pramlintide",
    alternativeNames: ["Symlin"],
    peptideClass: "Amylin analogue",
    structure: "Synthetic analogue of human amylin (islet amyloid polypeptide).",
    whatItIs: "An approved adjunct peptide injection for selected insulin-treated diabetes, as labelled.",
    howItWorks:
      "Amylin-receptor agonism slows gastric emptying, suppresses post-prandial glucagon and promotes satiety.",
    whatItDoesInBody: "Reduces post-prandial glucose excursions when used as labelled with insulin — hypoglycaemia risk requires insulin down-titration per PI.",
    studiedFor: ["Type 1 diabetes adjunct", "Insulin-treated type 2 diabetes"],
    potentialBenefits: ["Labelled prandial glucose control adjunct"],
    mayNotBeUsefulFor: ["Unsupervised weight-loss injections"],
    humanEvidence: "Labelled clinical programme for Symlin.",
    preclinicalEvidence: "Amylin physiology is established.",
    sideEffects: "Nausea; severe hypoglycaemia when insulin is not reduced as labelled.",
    contraindications: "Gastroparesis, hypoglycaemia unawareness — see PI.",
    regulatoryStatus: "FDA-approved (Symlin). Confirm other agencies.",
    australianRegulatoryStatus: "Verify ARTG; not sold here.",
    badges: ["APPROVED_MEDICINE"],
    areas: ["metabolic"],
    ...notSold,
    primaryTarget: "Amylin receptors (calcitonin-receptor complexes)",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "A",
    mechanismCertainty: "established",
    references: [
      {
        title: "Symlin (pramlintide) prescribing information",
        citation: "FDA USPI.",
        url: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
    ],
  },
  {
    slug: "setmelanotide",
    name: "Setmelanotide",
    alternativeNames: ["Imcivree"],
    peptideClass: "MC4 receptor agonist",
    structure: "Cyclic peptide melanocortin-4 receptor agonist.",
    whatItIs:
      "An approved medicine for rare genetic obesity disorders (POMC, PCSK1, LEPR deficiencies and other labelled genotypes), not general obesity.",
    howItWorks: "MC4R agonism in hypothalamic energy-balance circuits, as labelled.",
    whatItDoesInBody: "Reduces hunger and body weight in the labelled rare-disease populations.",
    studiedFor: ["Rare monogenic obesity"],
    potentialBenefits: ["Labelled genetic obesity indications only"],
    mayNotBeUsefulFor: ["General cosmetic weight loss", "Unselected polygenic obesity"],
    humanEvidence: "Pivotal rare-disease trials support labelled genotypes.",
    preclinicalEvidence: "MC4R energy-balance biology is established.",
    sideEffects: "Skin darkening, sexual-arousal effects, GI symptoms — see PI.",
    contraindications: "See PI.",
    regulatoryStatus: "FDA/EMA approved for specified genetic obesities.",
    australianRegulatoryStatus: "Verify ARTG. Not sold here.",
    badges: ["APPROVED_MEDICINE"],
    areas: ["metabolic"],
    ...notSold,
    primaryTarget: "Melanocortin-4 receptor",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "A",
    mechanismCertainty: "established",
    references: [
      {
        title: "Setmelanotide in POMC deficiency obesity",
        citation: "Clément K et al. Lancet Diabetes Endocrinol. 2020.",
        url: "https://pubmed.ncbi.nlm.nih.gov/33137281/",
      },
    ],
  },
  {
    slug: "desmopressin",
    name: "Desmopressin",
    alternativeNames: ["DDAVP", "Minirin"],
    peptideClass: "Vasopressin analogue (V2-selective)",
    structure: "Synthetic analogue of arginine vasopressin with D-amino acid and deamination modifications.",
    whatItIs: "Approved peptide analogue for diabetes insipidus, nocturnal enuresis and selected bleeding disorders, as labelled per product.",
    howItWorks: "V2-receptor agonism increases aquaporin-2 mediated water reabsorption; extra-renal effects on haemostasis at higher labelled uses.",
    whatItDoesInBody: "Antidiuretic and, in some products, haemostatic effects.",
    studiedFor: ["Central diabetes insipidus", "Nocturnal enuresis", "von Willebrand / haemophilia adjuncts (product-specific)"],
    potentialBenefits: ["Labelled endocrine/haematology uses"],
    mayNotBeUsefulFor: ["Unsupervised water-retention or sports use"],
    humanEvidence: "Long-standing labelled use.",
    preclinicalEvidence: "V2 receptor pharmacology is established.",
    sideEffects: "Hyponatraemia is the principal serious risk if fluid intake is not managed.",
    contraindications: "Habitual or psychogenic polydipsia, hyponatraemia — see PI.",
    regulatoryStatus: "Approved widely (FDA/EMA/TGA product-specific).",
    australianRegulatoryStatus: "ARTG-registered. Not sold here.",
    badges: ["APPROVED_MEDICINE"],
    areas: ["metabolic"],
    ...notSold,
    primaryTarget: "Vasopressin V2 receptor",
    routesInvestigated: ["Oral", "Sublingual", "Intranasal", "Injection"],
    humanEvidenceLevel: "A",
    mechanismCertainty: "established",
    references: [
      {
        title: "Desmopressin product information",
        citation: "TGA / FDA PI for desmopressin.",
        url: "https://www.tga.gov.au/",
      },
    ],
  },
  {
    slug: "leuprorelin",
    name: "Leuprorelin",
    alternativeNames: ["Leuprolide", "Lupron", "Eligard", "Lucrin"],
    peptideClass: "GnRH receptor agonist (depot peptide)",
    structure: "Nonapeptide GnRH analogue used as depot injections or implants.",
    whatItIs: "Approved medicine for androgen-deprivation in prostate cancer and other labelled hormone-dependent conditions, including some paediatric central precocious puberty products.",
    howItWorks:
      "Continuous GnRH-receptor stimulation down-regulates pituitary gonadotrophin release after an initial flare, lowering sex steroids.",
    whatItDoesInBody: "Medical castration / suppression of gonadal steroids as labelled.",
    studiedFor: ["Prostate cancer", "Endometriosis (product-specific)", "Central precocious puberty"],
    potentialBenefits: ["Labelled oncology and endocrine indications"],
    mayNotBeUsefulFor: ["Fitness testosterone ‘reset’ folklore"],
    humanEvidence: "Oncology-standard androgen-deprivation evidence.",
    preclinicalEvidence: "GnRH axis pharmacology is established.",
    sideEffects: "Hot flushes, bone loss, metabolic changes, flare of symptoms at initiation — see PI.",
    contraindications: "Pregnancy for many GnRH agonists; see PI.",
    regulatoryStatus: "Approved (FDA/EMA/TGA) brand-specific.",
    australianRegulatoryStatus: "ARTG-registered. Not sold here.",
    badges: ["APPROVED_MEDICINE"],
    areas: ["metabolic"],
    ...notSold,
    primaryTarget: "Gonadotropin-releasing hormone receptor",
    routesInvestigated: ["Intramuscular depot", "Subcutaneous depot"],
    humanEvidenceLevel: "A",
    mechanismCertainty: "established",
    references: [
      {
        title: "Leuprorelin prescribing information",
        citation: "FDA / TGA PI for leuprorelin/leuprolide depots.",
        url: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
    ],
  },
  {
    slug: "teduglutide",
    name: "Teduglutide",
    alternativeNames: ["Gattex", "Revestive"],
    peptideClass: "GLP-2 analogue",
    structure: "Recombinant GLP-2 analogue with substitution for DPP-4 resistance.",
    whatItIs: "Approved for short-bowel syndrome in eligible patients dependent on parenteral support, as labelled.",
    howItWorks: "GLP-2 receptor agonism promotes intestinal mucosal growth and absorption in labelled SBS care.",
    whatItDoesInBody: "May reduce parenteral nutrition volume in labelled SBS — specialist use.",
    studiedFor: ["Short bowel syndrome"],
    potentialBenefits: ["Labelled intestinal-failure indication"],
    mayNotBeUsefulFor: ["General gut ‘healing’ peptide use"],
    humanEvidence: "Pivotal SBS trials support labelling.",
    preclinicalEvidence: "GLP-2 intestinotrophic biology is established.",
    sideEffects: "GI symptoms; neoplastic risk discussions in PI (colon surveillance).",
    contraindications: "See PI (active GI malignancy considerations).",
    regulatoryStatus: "FDA/EMA approved for SBS.",
    australianRegulatoryStatus: "Verify ARTG. Not sold here.",
    badges: ["APPROVED_MEDICINE"],
    areas: ["metabolic"],
    ...notSold,
    primaryTarget: "Glucagon-like peptide-2 receptor",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "A",
    mechanismCertainty: "established",
    references: [
      {
        title: "Teduglutide for short bowel syndrome",
        citation: "Jeppesen PB et al. Gastroenterology. 2012.",
        url: "https://pubmed.ncbi.nlm.nih.gov/22683216/",
      },
    ],
  },
  {
    slug: "abaloparatide",
    name: "Abaloparatide",
    alternativeNames: ["Tymlos"],
    peptideClass: "PTHrP analogue (anabolic bone agent)",
    structure: "Synthetic analogue of parathyroid hormone-related peptide 1–34 region.",
    whatItIs: "Approved anabolic injection for osteoporosis in postmenopausal women at high fracture risk, as labelled (US).",
    howItWorks: "Agonist at PTH1 receptor with anabolic bone-formation signalling, as labelled.",
    whatItDoesInBody: "Increases bone mineral density and reduces fractures in labelled osteoporosis trials.",
    studiedFor: ["Postmenopausal osteoporosis"],
    potentialBenefits: ["Labelled fracture-risk reduction"],
    mayNotBeUsefulFor: ["Athletic bone ‘stacking’"],
    humanEvidence: "ACTIVE trial programme.",
    preclinicalEvidence: "PTH1R anabolic biology is established.",
    sideEffects: "Hypercalcaemia, dizziness, palpitations; osteosarcoma boxed warning in rodents (USPI).",
    contraindications: "See PI (pre-existing hypercalcaemia; duration limits).",
    regulatoryStatus: "FDA-approved (Tymlos). Confirm EMA/TGA.",
    australianRegulatoryStatus: "Verify ARTG. Not sold here.",
    badges: ["APPROVED_MEDICINE"],
    areas: ["recovery", "healthy-ageing"],
    ...notSold,
    primaryTarget: "PTH1 receptor",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "A",
    mechanismCertainty: "established",
    references: [
      citeAbalo(),
    ],
  },
];

function citeAbalo(): Peptide["references"][number] {
  return {
    title: "Abaloparatide versus placebo in postmenopausal osteoporosis (ACTIVE)",
    citation: "Miller PD et al. JAMA. 2016;316:722–733.",
    url: "https://pubmed.ncbi.nlm.nih.gov/27533157/",
  };
}
