import type { EncCitation, Peptide } from "./types";
import { pubmedUrl } from "./encyclopaedia";

function cite(
  key: string,
  title: string,
  opts: Partial<Omit<EncCitation, "key" | "title">> = {},
): EncCitation {
  const pmid = opts.pmid;
  return {
    key,
    title,
    authors: opts.authors,
    journal: opts.journal,
    year: opts.year,
    doi: opts.doi,
    pmid,
    nct: opts.nct,
    url: opts.url ?? (pmid ? pubmedUrl(pmid) : opts.doi ? `https://doi.org/${opts.doi}` : undefined),
  };
}

export const encyclopaediaOverlaysMore: Record<string, Partial<Peptide>> = {
  liraglutide: {
    lastReviewed: "2026-09-13",
    molecularFormula: "C172H265N43O51",
    molecularWeight: "3751.2 g·mol⁻¹",
    sequence: "Acylated GLP-1 analogue (Arg34, Lys26-palmitoyl); see PI for residue map.",
    primaryTarget: "GLP-1 receptor",
    halfLife: "Approximately 13 hours after subcutaneous injection (once-daily labelled products)",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "A",
    researchStatus: "Approved GLP-1 receptor agonist for type 2 diabetes and, at a higher-dose brand, chronic weight management.",
    origin: "Synthetic fatty-acid-acylated analogue of human GLP-1 developed for once-daily injection.",
    mechanismCertainty: "established",
    mechanismDetail:
      "Liraglutide activates the GLP-1 receptor, enhancing glucose-dependent insulin secretion, lowering glucagon, slowing gastric emptying and reducing appetite. Class mechanism is established in product information.",
    researchAreasDetail: [
      {
        label: "Type 2 diabetes",
        topic: "metabolic",
        evidence: "A",
        summary: "Has been investigated and approved for glycaemic control in type 2 diabetes (brand-specific).",
        citationKeys: ["leader"],
      },
      {
        label: "Weight management",
        topic: "body-composition",
        evidence: "A",
        summary: "SCALE programme investigated 3.0 mg once daily for chronic weight management in eligible adults.",
        citationKeys: ["scale"],
      },
      {
        label: "Cardiovascular outcomes",
        topic: "cardiovascular",
        evidence: "A",
        summary: "LEADER examined major adverse cardiovascular events in high-risk type 2 diabetes.",
        citationKeys: ["leader"],
      },
    ],
    humanStudies: [
      {
        id: "leader",
        population: "Type 2 diabetes with high cardiovascular risk",
        n: "9340",
        studyType: "Randomised, double-blind, placebo-controlled CVOT",
        compound: "Liraglutide up to 1.8 mg",
        dose: "1.8 mg once daily (diabetes)",
        route: "Subcutaneous",
        duration: "Median 3.8 years",
        primaryOutcome: "Major adverse cardiovascular events",
        findings: "Primary composite was lower with liraglutide than placebo in this population.",
        limitations: "Diabetes CVOT doses, not the 3 mg obesity brand automatically.",
        citationKey: "leader",
      },
    ],
    researchDosesHuman: [
      {
        study: "LEADER",
        model: "High-risk type 2 diabetes",
        dose: "1.8",
        unit: "mg",
        route: "Subcutaneous",
        frequency: "Once daily",
        duration: "Median 3.8 years",
        purpose: "Cardiovascular outcomes",
        citationKey: "leader",
      },
      {
        study: "SCALE Obesity and Prediabetes",
        model: "Adults with obesity or overweight plus comorbidity",
        dose: "3.0",
        unit: "mg",
        route: "Subcutaneous",
        frequency: "Once daily",
        duration: "56 weeks",
        purpose: "Weight-management efficacy",
        citationKey: "scale",
      },
    ],
    approvedDoses: [
      {
        authority: "FDA",
        country: "United States",
        product: "Victoza / Saxenda (liraglutide) — brand depends on indication",
        indication: "Type 2 diabetes (Victoza) and chronic weight management (Saxenda) as labelled",
        regimen: "Once-daily subcutaneous injection; diabetes maximum typically 1.8 mg and obesity brand 3.0 mg after escalation (verify USPI).",
        sourceTitle: "FDA Prescribing Information — liraglutide products",
        sourceUrl: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
      {
        authority: "TGA",
        country: "Australia",
        product: "ARTG-registered liraglutide",
        indication: "As per Australian PI",
        regimen: "Follow the current Australian Product Information.",
        sourceTitle: "TGA Product Information",
        sourceUrl: "https://www.tga.gov.au/",
      },
    ],
    pharmacokinetics: { halfLife: "~13 hours", notes: "Once-daily labelled products." },
    safetyDetail: {
      adverseEffects: "Gastrointestinal events are common.",
      seriousEvents: "Pancreatitis, gallbladder disease, and thyroid C-cell tumour warning in US labels (rodent).",
      pregnancy: "Not recommended; see PI.",
    },
    regulatoryDetail: {
      tga: "Registered prescription medicine, brand- and indication-specific.",
      fda: "Approved (separate brands/indications).",
      ema: "Authorised; see SmPC.",
    },
    citations: [
      cite("leader", "Liraglutide and Cardiovascular Outcomes in Type 2 Diabetes", {
        authors: "Marso SP et al.",
        journal: "N Engl J Med",
        year: 2016,
        doi: "10.1056/NEJMoa1603827",
        pmid: "27295427",
      }),
      cite("scale", "A Randomized, Controlled Trial of 3.0 mg of Liraglutide in Weight Management", {
        authors: "Pi-Sunyer X et al.",
        journal: "N Engl J Med",
        year: 2015,
        doi: "10.1056/NEJMoa1411892",
        pmid: "26132939",
      }),
    ],
  },
  tesamorelin: {
    lastReviewed: "2026-09-13",
    molecularFormula: "C221H366N72O67S (approximate; salt/form specific)",
    molecularWeight: "~5136 g·mol⁻¹ (tesamorelin acetate; confirm PI)",
    sequence: "Stabilised GHRH analogue (44 amino acids with trans-3-hexenoyl modification).",
    primaryTarget: "Growth-hormone-releasing hormone receptor (GHRHR) on pituitary somatotrophs",
    halfLife: "Short plasma half-life relative to downstream IGF-1 effect; see EGRIFTA PI for PK tables",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "A",
    researchStatus: "Approved in the United States to reduce excess abdominal fat in adults with HIV-associated lipodystrophy (EGRIFTA). Not a general anti-ageing approval.",
    origin: "Synthetic growth-hormone-releasing hormone analogue.",
    mechanismCertainty: "established",
    mechanismDetail:
      "Tesamorelin binds pituitary GHRH receptors, increasing endogenous GH pulsatility and circulating IGF-1. The labelled indication is reduction of excess visceral abdominal fat in a defined HIV-associated lipodystrophy population, not unrestricted body-composition use.",
    researchAreasDetail: [
      {
        label: "HIV-associated lipodystrophy (visceral fat)",
        topic: "body-composition",
        evidence: "A",
        summary: "Pivotal trials investigated abdominal visceral adipose tissue in adults with HIV and lipodystrophy.",
        citationKeys: ["falutz2010"],
      },
      {
        label: "Growth-hormone axis",
        topic: "growth-hormone-axis",
        evidence: "A",
        summary: "GH and IGF-1 rise is part of the labelled pharmacology.",
        citationKeys: ["egrifta-pi"],
      },
    ],
    humanStudies: [
      {
        id: "falutz",
        population: "Adults with HIV-associated lipodystrophy",
        n: "Pivotal programme hundreds of participants (see papers)",
        studyType: "Phase 3 randomised, placebo-controlled",
        compound: "Tesamorelin 2 mg",
        dose: "2 mg once daily",
        route: "Subcutaneous",
        duration: "26 weeks with extension data",
        primaryOutcome: "Visceral adipose tissue",
        findings: "Visceral fat decreased versus placebo; IGF-1 increased. Glucose should be monitored per label.",
        limitations: "HIV lipodystrophy population; not a licence for sports GH use.",
        citationKey: "falutz2010",
      },
    ],
    researchDosesHuman: [
      {
        study: "Pivotal HIV lipodystrophy programme",
        model: "Adults with HIV-associated excess abdominal fat",
        dose: "2",
        unit: "mg",
        route: "Subcutaneous",
        frequency: "Once daily",
        duration: "26 weeks (core)",
        purpose: "Visceral adipose tissue reduction",
        citationKey: "falutz2010",
      },
    ],
    approvedDoses: [
      {
        authority: "FDA",
        country: "United States",
        product: "EGRIFTA SV (tesamorelin)",
        indication: "Reduction of excess abdominal fat in HIV-infected adults with lipodystrophy",
        regimen: "2 mg subcutaneously once daily as labelled (confirm current USPI for reconstitution and dose).",
        sourceTitle: "FDA Prescribing Information — EGRIFTA",
        sourceUrl: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
      {
        authority: "TGA",
        country: "Australia",
        product: "Check ARTG for tesamorelin; may not match US HIV-lipodystrophy registration",
        indication: "Insufficient reliable evidence identified that a matching Australian registered product is universally available — verify ARTG.",
        regimen: "Do not substitute research-chemical GHRH analogues for EGRIFTA.",
        sourceTitle: "TGA ARTG search",
        sourceUrl: "https://www.tga.gov.au/",
      },
    ],
    pharmacokinetics: {
      notes: "See EGRIFTA USPI for absorption and IGF-1 pharmacodynamic timing.",
    },
    safetyDetail: {
      adverseEffects: "Injection-site reactions, arthralgia, oedema and glucose changes are discussed in the PI.",
      seriousEvents: "IGF-1 elevation; contraindicated with active malignancy per label.",
      pregnancy: "See PI.",
    },
    regulatoryDetail: {
      tga: "Verify ARTG; US approval does not automatically equal Australian registration.",
      fda: "Approved (EGRIFTA) for a specific HIV lipodystrophy indication.",
      ema: "Confirm whether a tesamorelin product is authorised; do not assume US label applies.",
    },
    citations: [
      cite("falutz2010", "Effects of tesamorelin (TH9507) on visceral fat and metabolic profile in HIV", {
        authors: "Falutz J et al.",
        journal: "N Engl J Med / related HIV lipodystrophy programme papers",
        year: 2010,
        pmid: "21083385",
      }),
      cite("egrifta-pi", "EGRIFTA (tesamorelin) prescribing information", {
        authors: "FDA / manufacturer",
        url: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      }),
    ],
  },
  retatrutide: {
    lastReviewed: "2026-09-13",
    primaryTarget: "GLP-1, GIP and glucagon receptors (triple agonist)",
    halfLife: "Supports once-weekly subcutaneous dosing in published Phase 2 protocols",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "B",
    researchStatus: "Investigational triple agonist. Not an approved medicine at last review of this encyclopaedia page.",
    origin: "Synthetic peptide designed for simultaneous GLP-1, GIP and glucagon receptor activity.",
    mechanismCertainty: "proposed",
    mechanismDetail:
      "Proposed mechanism: retatrutide is described in clinical literature as a triple agonist at GLP-1, GIP and glucagon receptors. Downstream effects on appetite, glycaemia and energy expenditure are inferred from this pharmacology and from Phase 2 weight and metabolic endpoints. Mechanism not yet fully established as a labelled drug, because no approved PI existed at last review.",
    researchAreasDetail: [
      {
        label: "Obesity",
        topic: "body-composition",
        evidence: "B",
        summary: "A Phase 2 randomised trial has investigated once-weekly retatrutide for obesity.",
        citationKeys: ["jastreboff2023"],
      },
      {
        label: "Type 2 diabetes",
        topic: "metabolic",
        evidence: "B",
        summary: "Early human research has examined glycaemic and weight endpoints in type 2 diabetes.",
        citationKeys: ["jastreboff2023"],
      },
    ],
    humanStudies: [
      {
        id: "phase2-obesity",
        population: "Adults with obesity",
        n: "338",
        studyType: "Phase 2 randomised, double-blind, placebo-controlled",
        compound: "Retatrutide",
        dose: "Dose-ranging once weekly (see paper for escalation to 1–12 mg groups)",
        route: "Subcutaneous",
        duration: "48 weeks",
        primaryOutcome: "Percentage change in body weight",
        findings: "Greater mean weight reduction versus placebo at higher doses, with gastrointestinal adverse events.",
        limitations: "Phase 2; not a substitute for approved labelling. Investigational product only.",
        citationKey: "jastreboff2023",
      },
    ],
    researchDosesHuman: [
      {
        study: "Jastreboff et al. Phase 2 obesity trial",
        model: "Adults with obesity",
        dose: "1–12 (dose-ranging groups)",
        unit: "mg",
        route: "Subcutaneous",
        frequency: "Once weekly",
        duration: "48 weeks",
        purpose: "Efficacy and safety in obesity",
        citationKey: "jastreboff2023",
      },
    ],
    pharmacokinetics: {
      notes: "Published Phase 2 protocols used once-weekly injection; full PK tables belong in the primary paper and any future PI.",
    },
    safetyDetail: {
      adverseEffects: "Gastrointestinal events similar to other incretin agonists were reported.",
      unknowns: "Long-term and regulatory-review safety package is not equivalent to an approved product.",
    },
    regulatoryDetail: {
      tga: "Not approved.",
      fda: "Investigational (not approved at last encyclopaedia review).",
      ema: "Not approved.",
    },
    citations: [
      cite("jastreboff2023", "Triple-Hormone-Receptor Agonist Retatrutide for Obesity — A Phase 2 Trial", {
        authors: "Jastreboff AM et al.",
        journal: "N Engl J Med",
        year: 2023,
        doi: "10.1056/NEJMoa2301972",
        pmid: "37366315",
      }),
    ],
  },
  ipamorelin: {
    lastReviewed: "2026-09-13",
    sequence: "Aib-His-D-2-Nal-D-Phe-Lys-NH2 (pentapeptide ghrelin-mimetic secretagogue)",
    primaryTarget: "Ghrelin receptor (GHSR-1a) — proposed selective GH secretagogue",
    halfLife: "Short (minutes to a few hours range in limited PK reports); insufficient standardised human PI data",
    routesInvestigated: ["Intravenous (clinical pharmacology)", "Subcutaneous (research use reports)"],
    humanEvidenceLevel: "C",
    researchStatus: "Investigational growth-hormone secretagogue. Not an approved chronic GH-axis medicine.",
    origin: "Synthetic pentapeptide developed as a ghrelin-receptor agonist with relative GH selectivity in early pharmacology.",
    mechanismCertainty: "proposed",
    mechanismDetail:
      "Proposed mechanism: ipamorelin stimulates the ghrelin receptor on pituitary somatotrophs, increasing GH release with less ACTH/cortisol and prolactin stimulation than some older GHRPs in experimental comparisons. Mechanism not yet fully established as a labelled therapy. Human programmes did not produce a registered product for anti-ageing or bodybuilding use.",
    researchAreasDetail: [
      {
        label: "Growth-hormone secretion",
        topic: "growth-hormone-axis",
        evidence: "C",
        summary: "Early human research has examined GH release after parenteral ipamorelin in clinical pharmacology settings.",
        citationKeys: ["raun1998"],
      },
    ],
    humanStudies: [
      {
        id: "gh-release",
        population: "Clinical pharmacology / limited patient cohorts",
        n: "Small",
        studyType: "Clinical pharmacology",
        compound: "Ipamorelin",
        dose: "Study-specific µg/kg intravenous or bolus regimens in published pharmacology papers",
        route: "Intravenous in early papers",
        duration: "Acute / short protocols",
        primaryOutcome: "GH concentration",
        findings: "GH rises have been observed in experimental settings. This is not an approved treatment regimen.",
        limitations: "No modern Phase 3 anti-ageing programme.",
        citationKey: "raun1998",
      },
    ],
    researchDosesHuman: [
      {
        study: "Early ipamorelin GH-release pharmacology",
        model: "Human volunteers / limited clinical pharmacology",
        dose: "µg/kg range (paper-specific)",
        unit: "µg/kg",
        route: "Intravenous in foundational papers",
        frequency: "Single or short repeated doses in experiments",
        duration: "Acute",
        purpose: "Characterise GH secretagogue activity",
        citationKey: "raun1998",
      },
    ],
    pharmacokinetics: {
      notes: "Reliable population PK comparable to a registered weekly incretin was not identified.",
    },
    safetyDetail: {
      adverseEffects: "Flushing, glucose or GH-axis effects are theoretically possible; a labelled AE table does not exist.",
      unknowns: "Grey-market vials are not pharmaceutical-grade evidence.",
    },
    regulatoryDetail: {
      tga: "Not approved as a GH secretagogue medicine.",
      fda: "Not approved.",
      ema: "Not approved.",
    },
    citations: [
      cite("raun1998", "Ipamorelin, the first selective growth hormone secretagogue", {
        authors: "Raun K et al.",
        journal: "Eur J Endocrinol",
        year: 1998,
        pmid: "9849822",
      }),
    ],
  },
  "cjc-1295": {
    lastReviewed: "2026-09-13",
    primaryTarget: "GHRH receptor (DAC-modified GHRH analogue in the original CJC-1295 construct)",
    halfLife: "Original Drug-Affinity-Complex (DAC) construct was designed for multi-day GH-axis stimulation; ‘no DAC’ research fragments are pharmacokinetically different",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "C",
    researchStatus: "Investigational GHRH analogue family. Not an approved medicine. Name collision: DAC vs non-DAC research products are not interchangeable.",
    origin: "Synthetic GHRH analogue; the published CJC-1295 construct used albumin-binding (DAC) chemistry.",
    mechanismCertainty: "proposed",
    mechanismDetail:
      "Proposed mechanism: GHRH-receptor agonism increases pituitary GH. The albumin-binding DAC form prolongs exposure in published clinical pharmacology. Mechanism not yet fully established as therapy. Unregulated ‘CJC-1295 without DAC’ products should not be assumed to match Teichman et al. PK.",
    researchAreasDetail: [
      {
        label: "Growth-hormone axis",
        topic: "growth-hormone-axis",
        evidence: "C",
        summary: "Early human research has examined GH and IGF-1 after CJC-1295 in clinical pharmacology.",
        citationKeys: ["teichman2006"],
      },
    ],
    humanStudies: [
      {
        id: "teichman",
        population: "Healthy adults in a clinical pharmacology study",
        n: "Small (see paper)",
        studyType: "Randomised clinical pharmacology",
        compound: "CJC-1295 (DAC GHRH analogue)",
        dose: "Dose-ranging subcutaneous (see Teichman et al. for µg/kg groups)",
        route: "Subcutaneous",
        duration: "Weeks (protocol-specific)",
        primaryOutcome: "GH and IGF-1",
        findings: "Sustained GH/IGF-1 elevations were reported for the DAC construct.",
        limitations: "Not an approved product; safety for chronic wellness use was not established as labelling.",
        citationKey: "teichman2006",
      },
    ],
    researchDosesHuman: [
      {
        study: "Teichman et al. 2006",
        model: "Healthy adults",
        dose: "Dose-ranging (see paper)",
        unit: "µg/kg",
        route: "Subcutaneous",
        frequency: "Intermittent in the pharmacology protocol",
        duration: "Study-specific",
        purpose: "GH/IGF-1 pharmacodynamics of DAC CJC-1295",
        citationKey: "teichman2006",
      },
    ],
    pharmacokinetics: {
      halfLife: "Multi-day IGF-1 effect described for DAC CJC-1295; not for unnamed research powders",
      notes: "Insufficient reliable evidence identified that grey-market ‘no DAC’ vials match published DAC PK.",
    },
    safetyDetail: {
      adverseEffects: "Injection-site reactions and GH-axis effects possible; labelled AE table absent.",
      unknowns: "Long-term safety unknown. Development of related GHRH analogues had cardiovascular safety questions in other programmes — do not assume safety.",
    },
    regulatoryDetail: {
      tga: "Not approved.",
      fda: "Not approved.",
      ema: "Not approved.",
    },
    citations: [
      cite("teichman2006", "Prolonged stimulation of growth hormone (GH) and insulin-like growth factor I secretion by CJC-1295", {
        authors: "Teichman SL et al.",
        journal: "J Clin Endocrinol Metab",
        year: 2006,
        pmid: "16352683",
        doi: "10.1210/jc.2005-1538",
      }),
    ],
  },
  "tb-500": {
    lastReviewed: "2026-09-13",
    sequence: "Often sold as an acetylated fragment related to thymosin beta-4 (Tβ4); commercial ‘TB-500’ is not a single well-controlled pharmaceutical substance.",
    primaryTarget: "Proposed actin-binding / cell-migration pathways of thymosin beta-4. Mechanism not yet fully established for grey-market fragments.",
    halfLife: "Insufficient reliable evidence identified for standardised human PK of research-chemical TB-500.",
    routesInvestigated: ["Parenteral in animal models of Tβ4; grey-market subcutaneous reports are not trials"],
    humanEvidenceLevel: "D",
    researchStatus: "Research fragment / investigational. Thymosin beta-4 itself has been explored clinically in other formulations; TB-500 street products are not those medicines.",
    origin: "Name used in research-chemical markets for Tβ4-related peptides. Endogenous Tβ4 is an actin-sequestering peptide.",
    mechanismCertainty: "not-fully-established",
    mechanismDetail:
      "Proposed mechanism: thymosin beta-4 binds G-actin and has been studied in cell migration and repair models. Mechanism not yet fully established for uncharacterised TB-500 vials. Do not equate a vendor label with pharmaceutical Tβ4.",
    researchAreasDetail: [
      {
        label: "Tissue-repair models",
        topic: "recovery",
        evidence: "D",
        summary: "Preclinical studies suggest roles for Tβ4 in wound and cardiac models. Human grey-market TB-500 use is not that evidence base.",
        citationKeys: ["goldstein2012"],
      },
    ],
    preclinicalStudies: [
      {
        id: "tb4-wound",
        model: "Animal wound / cardiac injury models of thymosin beta-4",
        studyType: "Animal experimental",
        findings: "Preclinical studies suggest repair-related signals. Not a human sports-medicine indication.",
        limitations: "Fragment identity of commercial TB-500 is often unverified.",
        citationKey: "goldstein2012",
      },
    ],
    pharmacokinetics: {
      notes: "Reliable human PK for research-chemical TB-500 were not identified.",
    },
    safetyDetail: {
      adverseEffects: "Insufficient reliable evidence identified for a labelled AE profile.",
      unknowns: "Misidentification and contamination are practical risks of unregulated peptides.",
    },
    regulatoryDetail: {
      tga: "Not approved as TB-500. Not sold here.",
      fda: "Not approved as a TB-500 drug.",
      ema: "Not approved.",
    },
    citations: [
      cite("goldstein2012", "Thymosin β4: a multi-functional regenerative peptide", {
        authors: "Goldstein AL et al.",
        journal: "Expert Opin Biol Ther",
        year: 2012,
        pmid: "22646022",
      }),
    ],
  },
  "ss-31": {
    lastReviewed: "2026-09-13",
    alternativeNames: ["Elamipretide", "Bendavia"],
    sequence: "D-Arg-Dmt-Lys-Phe-NH2 (aromatic-cationic tetrapeptide)",
    primaryTarget: "Proposed: cardiolipin on the inner mitochondrial membrane",
    halfLife: "Short plasma half-life with intracellular mitochondrial targeting described in development literature",
    routesInvestigated: ["Intravenous", "Subcutaneous (development programmes)", "Topical ophthalmic (separate programme)"],
    humanEvidenceLevel: "C",
    researchStatus: "Investigational (elamipretide). Not broadly approved as a mitochondrial medicine at last review; development status should be re-checked against FDA/EMA/TGA registers.",
    origin: "Synthetic mitochondria-targeted tetrapeptide (SS-peptide class).",
    mechanismCertainty: "proposed",
    mechanismDetail:
      "Proposed mechanism: elamipretide associates with cardiolipin, aiming to improve inner-membrane structure and electron-transport efficiency in stressed mitochondria. Mechanism not yet fully established as an approved systemic indication. Clinical programmes in primary mitochondrial disease and Barth syndrome have been mixed or indication-specific — check current regulatory status rather than assuming approval.",
    researchAreasDetail: [
      {
        label: "Mitochondrial disease programmes",
        topic: "mitochondrial",
        evidence: "C",
        summary: "Early human research has examined elamipretide in primary mitochondrial myopathy and related conditions; results and regulatory outcomes are programme-specific.",
        citationKeys: ["karaa2018"],
      },
    ],
    humanStudies: [
      {
        id: "mmpower",
        population: "Adults with primary mitochondrial myopathy (trial-defined)",
        n: "See MMPOWER publications",
        studyType: "Randomised clinical development",
        compound: "Elamipretide (SS-31)",
        dose: "Protocol-specific (often once-daily parenteral in development)",
        route: "Subcutaneous or intravenous depending on trial",
        duration: "Weeks to months (protocol-specific)",
        primaryOutcome: "Function / 6-minute walk and biomarkers (trial-specific)",
        findings: "Some studies reported biomarker or functional signals; not all endpoints were positive. Treat as investigational.",
        limitations: "Not a licence for wellness mitochondrial ‘optimisation’.",
        citationKey: "karaa2018",
      },
    ],
    researchDosesHuman: [
      {
        study: "Elamipretide mitochondrial myopathy development (representative)",
        model: "Primary mitochondrial myopathy",
        dose: "Protocol-specific (see MMPOWER papers)",
        unit: "mg",
        route: "Subcutaneous (typical development route)",
        frequency: "Once daily in several protocols",
        duration: "Study-specific",
        purpose: "Mitochondrial myopathy efficacy/safety",
        citationKey: "karaa2018",
      },
    ],
    pharmacokinetics: {
      notes: "Development PK exists in papers and investigator brochures; not a consumer PI.",
    },
    safetyDetail: {
      adverseEffects: "Injection-site reactions have been reported in development.",
      unknowns: "Long-term unapproved use is not characterised.",
    },
    regulatoryDetail: {
      tga: "Not an established ARTG mitochondrial peptide for general use — verify register.",
      fda: "Development/regulatory status is indication-specific; not a general wellness approval.",
      ema: "Verify register; do not assume approval.",
    },
    citations: [
      cite("karaa2018", "Randomized dose-escalation trial of elamipretide in adults with primary mitochondrial myopathy", {
        authors: "Karaa A et al.",
        journal: "Neurology",
        year: 2018,
        pmid: "29626192",
        doi: "10.1212/WNL.0000000000005255",
      }),
    ],
  },
  "mots-c": {
    lastReviewed: "2026-09-13",
    sequence: "Mitochondrial ORF-derived 16-amino-acid peptide (MRWQEMGYIFYPRKLR)",
    primaryTarget: "Proposed metabolic / folate-purine / AMPK-related pathways in preclinical work. Mechanism not yet fully established in humans.",
    halfLife: "Insufficient reliable evidence identified for a validated human therapeutic half-life.",
    routesInvestigated: ["Intraperitoneal (mice)", "Insufficient standardised human therapeutic route"],
    humanEvidenceLevel: "D",
    researchStatus: "Endogenous mitochondrial-encoded peptide under investigation. Not an approved drug.",
    origin: "Peptide encoded by a mitochondrial open reading frame; studied as a metabolic signal in animals.",
    mechanismCertainty: "not-fully-established",
    mechanismDetail:
      "Proposed mechanism: MOTS-c has been reported to influence AMPK-related metabolic signalling and exercise-like transcriptional programmes in mice. Mechanism not yet fully established as a human drug. Circulating MOTS-c measurements in humans are biomarker research, not dosing instructions.",
    researchAreasDetail: [
      {
        label: "Metabolic stress models",
        topic: "metabolic",
        evidence: "D",
        summary: "Preclinical studies suggest metabolic effects in diet-induced obesity models. Human therapeutic trials of MOTS-c as a drug were not identified as an approved programme.",
        citationKeys: ["lee2015"],
      },
      {
        label: "Longevity / ageing biology",
        topic: "longevity",
        evidence: "E",
        summary: "Mechanistic/theoretical ageing-biology interest exceeds the human interventional evidence base.",
        citationKeys: ["lee2015"],
      },
    ],
    preclinicalStudies: [
      {
        id: "lee-mice",
        model: "Mice, diet-induced metabolic stress",
        studyType: "Animal experimental",
        findings: "Preclinical studies suggest improved metabolic parameters in specific models.",
        limitations: "Do not convert mouse doses to human self-administration.",
        citationKey: "lee2015",
      },
    ],
    researchDosesAnimal: [
      {
        study: "Lee et al. 2015 MOTS-c mouse experiments",
        model: "Mice",
        dose: "Paper-specific mg/kg intraperitoneal",
        unit: "mg/kg (animal)",
        route: "Intraperitoneal",
        frequency: "Study-specific",
        duration: "Study-specific",
        purpose: "Experimental metabolic pharmacology",
        citationKey: "lee2015",
      },
    ],
    pharmacokinetics: {
      notes: "Reliable human PK for therapeutic MOTS-c injections were not identified.",
    },
    safetyDetail: {
      adverseEffects: "Insufficient reliable evidence identified.",
      unknowns: "Unknowns dominate for unregulated injectables.",
    },
    regulatoryDetail: {
      tga: "Not approved.",
      fda: "Not approved as a MOTS-c drug.",
      ema: "Not approved.",
    },
    citations: [
      cite("lee2015", "The mitochondrial-derived peptide MOTS-c promotes metabolic homeostasis and reduces obesity and insulin resistance", {
        authors: "Lee C et al.",
        journal: "Cell Metab",
        year: 2015,
        pmid: "25738459",
        doi: "10.1016/j.cmet.2015.02.009",
      }),
    ],
  },
  semax: {
    lastReviewed: "2026-09-13",
    sequence: "Met-Glu-His-Phe-Pro-Gly-Pro (ACTH(4–10) analogue with Pro-Gly-Pro)",
    primaryTarget: "Proposed melanocortin-related and neurotrophic signalling. Mechanism not yet fully established outside regional product use.",
    routesInvestigated: ["Intranasal (regional clinical use)", "Parenteral in experimental literature"],
    humanEvidenceLevel: "C",
    researchStatus: "Used as a registered product in some jurisdictions outside ICH-aligned TGA/FDA/EMA pathways; not an FDA/TGA approved nootropic. Treat as investigational in Australia.",
    origin: "Synthetic ACTH fragment analogue developed in Russian clinical research programmes.",
    mechanismCertainty: "proposed",
    mechanismDetail:
      "Proposed mechanism: Semax is reported to influence BDNF-related and melanocortin-adjacent pathways in experimental systems. Mechanism not yet fully established by FDA/EMA labelling. Human data are largely regional and not equivalent to a modern Western NDA package.",
    researchAreasDetail: [
      {
        label: "Ischaemic stroke / cognition (regional literature)",
        topic: "neurological",
        evidence: "C",
        summary: "Early human research in regional literature has examined stroke and cognitive settings. Quality and generalisability vary.",
        citationKeys: ["asmarin1997"],
      },
    ],
    pharmacokinetics: {
      notes: "Intranasal regional products exist; ICH-standard PK for Australian registration was not identified.",
    },
    safetyDetail: {
      adverseEffects: "Nasal irritation possible with intranasal use; a complete ICH AE table was not identified.",
      unknowns: "Compounded research sprays are not regional registered products.",
    },
    regulatoryDetail: {
      tga: "Not an established ARTG nootropic peptide.",
      fda: "Not approved.",
      ema: "Not centrally authorised as a cognitive peptide drug.",
    },
    citations: [
      cite("asmarin1997", "A nootropic ACTH(4-10) analogue Semax: studies in healthy volunteers and patients", {
        authors: "Asmarin IP et al. / related Semax clinical reports",
        journal: "Neurosci Res Commun / Russian clinical literature",
        year: 1997,
        pmid: "9448131",
      }),
    ],
  },
  somatropin: {
    lastReviewed: "2026-09-13",
    molecularFormula: "Recombinant 191-amino-acid human GH (product-specific)",
    molecularWeight: "~22 kDa",
    sequence: "Identical primary sequence to pituitary 22-kDa GH in somatropin products (confirm PI).",
    primaryTarget: "Growth hormone receptor (GHR)",
    halfLife: "Hours after subcutaneous injection; IGF-1 pharmacodynamics last longer (see each PI)",
    routesInvestigated: ["Subcutaneous", "Intramuscular (older)"],
    humanEvidenceLevel: "A",
    researchStatus: "Approved recombinant growth hormone for specific deficiency and other labelled paediatric/adult indications.",
    origin: "Recombinant human growth hormone.",
    mechanismCertainty: "established",
    mechanismDetail:
      "Somatropin binds the growth-hormone receptor, activating JAK-STAT signalling and increasing IGF-1 production. Labelled uses are indication-specific (GH deficiency and other registered conditions), not anti-ageing or athletic enhancement.",
    researchAreasDetail: [
      {
        label: "Growth-hormone deficiency",
        topic: "growth-hormone-axis",
        evidence: "A",
        summary: "Approved replacement therapy in documented GH deficiency, product-specific.",
        citationKeys: ["gh-pi"],
      },
    ],
    approvedDoses: [
      {
        authority: "FDA",
        country: "United States",
        product: "Multiple somatropin brands (e.g. Genotropin, Norditropin, Humatrope)",
        indication: "Paediatric and adult GH deficiency and other labelled indications — brand-specific",
        regimen: "Weight- or IGF-1–guided subcutaneous dosing in the PI. Athletic ‘cycles’ are not labelled regimens.",
        sourceTitle: "FDA Prescribing Information — somatropin products",
        sourceUrl: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
      {
        authority: "TGA",
        country: "Australia",
        product: "ARTG-registered somatropin",
        indication: "As per Australian PI",
        regimen: "Specialist endocrinology dosing only.",
        sourceTitle: "TGA Product Information",
        sourceUrl: "https://www.tga.gov.au/",
      },
    ],
    pharmacokinetics: {
      halfLife: "Product-specific; subcutaneous daily or long-acting depot products differ",
      notes: "Long-acting GH products have separate PIs.",
    },
    safetyDetail: {
      adverseEffects: "Oedema, arthralgia, carpal-tunnel symptoms, glucose intolerance, injection-site reactions.",
      seriousEvents: "Contraindicated in active malignancy in many labels; intracranial hypertension and slipped capital femoral epiphysis discussed in paediatric PI.",
      pregnancy: "See PI.",
    },
    regulatoryDetail: {
      tga: "Registered prescription medicine, indication-specific.",
      fda: "Approved, brand-specific.",
      ema: "Authorised, brand-specific.",
    },
    citations: [
      cite("gh-pi", "Somatropin prescribing information (representative class labelling)", {
        authors: "FDA / TGA product information",
        url: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      }),
    ],
  },
  insulin: {
    lastReviewed: "2026-09-13",
    primaryTarget: "Insulin receptor (INSR)",
    halfLife: "Formulation-dependent (rapid analogues minutes–hours; basal analogues many hours)",
    routesInvestigated: ["Subcutaneous", "Intravenous", "Inhaled (specific products)"],
    humanEvidenceLevel: "A",
    researchStatus: "Approved essential peptide hormone medicines for diabetes. Formulation-specific.",
    origin: "Human insulin or analogues produced recombinantly.",
    mechanismCertainty: "established",
    mechanismDetail:
      "Insulin binds the insulin receptor, triggering PI3K–AKT and MAPK signalling that promotes glucose uptake (notably via GLUT4 in muscle and adipose tissue) and metabolic storage. This is established physiology and labelled pharmacology.",
    researchAreasDetail: [
      {
        label: "Diabetes mellitus",
        topic: "metabolic",
        evidence: "A",
        summary: "Approved replacement/pharmacotherapy across type 1 and insulin-requiring type 2 diabetes.",
        citationKeys: ["ada-insulin"],
      },
    ],
    approvedDoses: [
      {
        authority: "TGA",
        country: "Australia",
        product: "ARTG-registered insulin products",
        indication: "Diabetes mellitus as labelled",
        regimen: "Individualised, glucose-monitored units. Never copy research-chemical ‘insulin-like’ peptides.",
        sourceTitle: "Australian Product Information — insulin",
        sourceUrl: "https://www.tga.gov.au/",
      },
      {
        authority: "FDA",
        country: "United States",
        product: "Multiple insulin NDAs/BLAs",
        indication: "Diabetes as labelled per product",
        regimen: "See each USPI.",
        sourceTitle: "FDA insulin labels",
        sourceUrl: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
    ],
    pharmacokinetics: {
      notes: "PK is entirely formulation-specific (aspart, glargine, degludec, regular, NPH, inhaled).",
    },
    safetyDetail: {
      adverseEffects: "Hypoglycaemia is the principal harm. Weight gain, injection-site lipodystrophy.",
      seriousEvents: "Severe hypoglycaemia, hypokalaemia with IV insulin.",
      interactions: "Many drugs alter insulin requirement.",
    },
    regulatoryDetail: {
      tga: "Registered prescription (and some pharmacist-supply) insulins — product-specific.",
      fda: "Approved.",
      ema: "Authorised.",
    },
    citations: [
      cite("ada-insulin", "Pharmacologic Approaches to Glycemic Treatment — Standards of Care in Diabetes", {
        authors: "American Diabetes Association Professional Practice Committee",
        journal: "Diabetes Care",
        year: 2024,
        url: "https://diabetesjournals.org/care",
      }),
    ],
  },
  bremelanotide: {
    lastReviewed: "2026-09-13",
    alternativeNames: ["PT-141", "Vyleesi"],
    primaryTarget: "Melanocortin receptors (MC4R-preferring agonist as labelled)",
    halfLife: "See Vyleesi USPI (hours-range after subcutaneous injection)",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "A",
    researchStatus: "Approved in the US (Vyleesi) for acquired, generalised hypoactive sexual desire disorder in premenopausal women, as labelled. PT-141 research-chemical products are not Vyleesi.",
    origin: "Synthetic cyclic heptapeptide melanocortin agonist; related historically to melanotan chemistry.",
    mechanismCertainty: "established",
    mechanismDetail:
      "Bremelanotide is a melanocortin-receptor agonist; labelled sexual-desire effects are attributed primarily to central MC4R pathways. Peripheral tanning is not the labelled indication (contrast with unapproved melanotan products).",
    researchAreasDetail: [
      {
        label: "Hypoactive sexual desire disorder",
        topic: "sexual-health",
        evidence: "A",
        summary: "Has been investigated and, in the US, approved for a defined premenopausal HSDD population.",
        citationKeys: ["kingsberg2019"],
      },
    ],
    humanStudies: [
      {
        id: "reconnect",
        population: "Premenopausal women with HSDD (trial-defined)",
        n: "RECONNECT programme (see publications)",
        studyType: "Phase 3 randomised, placebo-controlled",
        compound: "Bremelanotide 1.75 mg",
        dose: "1.75 mg as needed",
        route: "Subcutaneous",
        duration: "24-week core trials",
        primaryOutcome: "Sexual desire / distress scores as specified",
        findings: "Statistically significant changes versus placebo on labelled endpoints; nausea is common.",
        limitations: "Population and as-needed labelled use only.",
        citationKey: "kingsberg2019",
      },
    ],
    researchDosesHuman: [
      {
        study: "RECONNECT Phase 3",
        model: "Premenopausal women with HSDD",
        dose: "1.75",
        unit: "mg",
        route: "Subcutaneous",
        frequency: "As needed, with labelled maximum frequency",
        duration: "24 weeks core",
        purpose: "HSDD efficacy and safety",
        citationKey: "kingsberg2019",
      },
    ],
    approvedDoses: [
      {
        authority: "FDA",
        country: "United States",
        product: "Vyleesi (bremelanotide)",
        indication: "Acquired, generalised HSDD in premenopausal women (see USPI limitations)",
        regimen: "1.75 mg subcutaneously as needed, no more than one dose in 24 hours and labelled monthly cap — verify current USPI.",
        sourceTitle: "FDA Prescribing Information — Vyleesi",
        sourceUrl: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
    ],
    safetyDetail: {
      adverseEffects: "Nausea, flushing, injection-site reactions, headache. Transient blood-pressure increase.",
      seriousEvents: "Focal hyperpigmentation reported; contraindicated in uncontrolled hypertension / CVD per label.",
      pregnancy: "Not indicated in pregnancy; see PI.",
    },
    regulatoryDetail: {
      tga: "Verify ARTG; US approval does not automatically confer Australian registration.",
      fda: "Approved (Vyleesi) for a narrow HSDD indication.",
      ema: "Verify SmPC/register.",
    },
    citations: [
      cite("kingsberg2019", "Bremelanotide for the Treatment of Hypoactive Sexual Desire Disorder", {
        authors: "Kingsberg SA et al.",
        journal: "Obstet Gynecol",
        year: 2019,
        pmid: "31599837",
      }),
    ],
  },
  "melanotan-ii": {
    lastReviewed: "2026-09-13",
    primaryTarget: "Melanocortin receptors (non-selective relative to labelled bremelanotide)",
    routesInvestigated: ["Subcutaneous (unapproved / illicit markets)", "Experimental"],
    humanEvidenceLevel: "C",
    researchStatus: "Not approved. TGA has warned consumers about Melanotan products.",
    origin: "Synthetic melanocortin agonist developed experimentally; diverted to unapproved tanning use.",
    mechanismCertainty: "proposed",
    mechanismDetail:
      "Proposed mechanism: MC1R-mediated melanogenesis and broader melanocortin effects (including autonomic and sexual signalling). Mechanism not yet fully established as a legal therapeutic. Unapproved tanning injections have documented harm reports.",
    researchAreasDetail: [
      {
        label: "Pigmentation (unapproved)",
        topic: "skin",
        evidence: "C",
        summary: "Has been investigated experimentally for pigmentation. This is not an approved indication; regulators warn against use.",
        citationKeys: ["tga-melanotan"],
      },
    ],
    safetyDetail: {
      adverseEffects: "Nausea, flushing, appetite change, spontaneous erections, mole darkening.",
      seriousEvents: "Case reports of melanoma concern, rhabdomyolysis and serious systemic reactions in the unapproved-use literature — see regulator warnings.",
      unknowns: "Product contamination is common in illicit supply.",
    },
    regulatoryDetail: {
      tga: "Not approved. Consumer warnings against Melanotan I/II.",
      fda: "Not approved for tanning.",
      ema: "Not approved for tanning.",
    },
    citations: [
      cite("tga-melanotan", "TGA consumer warnings on Melanotan", {
        authors: "Therapeutic Goods Administration",
        url: "https://www.tga.gov.au/",
        year: 2023,
      }),
    ],
  },
  epithalon: {
    lastReviewed: "2026-09-13",
    sequence: "Ala-Glu-Asp-Gly (AEDG tetrapeptide; also spelled epitalon)",
    primaryTarget: "Proposed telomerase / pineal peptide signalling. Mechanism not yet fully established.",
    routesInvestigated: ["Experimental parenteral (Khavinson school literature)"],
    humanEvidenceLevel: "D",
    researchStatus: "Investigational tetrapeptide. Not TGA/FDA/EMA approved as a longevity drug.",
    origin: "Synthetic tetrapeptide associated with pineal peptide research programmes.",
    mechanismCertainty: "not-fully-established",
    mechanismDetail:
      "Proposed mechanism: epitalon has been reported to affect telomerase and geroprotective markers in experimental systems. Mechanism not yet fully established. Independent, modern registrational trials were not identified.",
    researchAreasDetail: [
      {
        label: "Ageing biology",
        topic: "longevity",
        evidence: "E",
        summary: "Mechanistic/theoretical and regional experimental literature exceed the independent Phase 3 evidence base.",
        citationKeys: ["khavinson-review"],
      },
    ],
    pharmacokinetics: { notes: "Reliable ICH-standard human PK were not identified." },
    safetyDetail: {
      adverseEffects: "Insufficient reliable evidence identified.",
      unknowns: "Unknowns dominate.",
    },
    regulatoryDetail: {
      tga: "Not approved.",
      fda: "Not approved.",
      ema: "Not approved.",
    },
    citations: [
      cite("khavinson-review", "Peptide geroprotection literature associated with AEDG / epitalon (regional experimental corpus)", {
        authors: "Khavinson VKh et al.",
        journal: "Various experimental gerontology papers",
        year: 2003,
        pmid: "14518447",
      }),
    ],
  },
  "aod-9604": {
    lastReviewed: "2026-09-13",
    sequence: "hGH 176–191 analogue with tyrosine substitution (AOD9604)",
    primaryTarget: "Proposed lipolytic signalling distinct from full GH receptor activation. Mechanism not yet fully established as a drug.",
    routesInvestigated: ["Oral (development)", "Parenteral (research markets)"],
    humanEvidenceLevel: "C",
    researchStatus: "Investigational GH-fragment analogue. Not an approved obesity medicine.",
    origin: "Synthetic analogue of the C-terminal fragment of human GH.",
    mechanismCertainty: "proposed",
    mechanismDetail:
      "Proposed mechanism: AOD9604 was developed to isolate metabolic/lipolytic actions attributed to the GH C-terminus without full GH-receptor growth effects. Mechanism not yet fully established; development did not yield a registered obesity drug.",
    researchAreasDetail: [
      {
        label: "Obesity (development)",
        topic: "metabolic",
        evidence: "C",
        summary: "Early human research has examined oral AOD9604 in obesity; it is not an approved therapy.",
        citationKeys: ["ng2000"],
      },
    ],
    researchDosesHuman: [
      {
        study: "Early oral AOD9604 obesity development",
        model: "Adults with obesity (development cohorts)",
        dose: "Oral milligram range (paper-specific)",
        unit: "mg",
        route: "Oral in published development",
        frequency: "Daily in development protocols",
        duration: "Study-specific",
        purpose: "Exploratory weight/metabolic endpoints",
        citationKey: "ng2000",
      },
    ],
    pharmacokinetics: { notes: "Development PK is paper-specific; not a PI." },
    safetyDetail: {
      adverseEffects: "Insufficient modern labelled AE table.",
      unknowns: "Injectable research-chemical AOD is not the oral development product.",
    },
    regulatoryDetail: {
      tga: "Not approved as an obesity drug. WADA has separately addressed AOD9604 in sport.",
      fda: "Not approved.",
      ema: "Not approved.",
    },
    citations: [
      cite("ng2000", "Metabolic studies of AOD9604 / hGH fragment analogues in obesity development", {
        authors: "Ng FM / Heffernan M et al. related AOD9604 papers",
        journal: "Obesity research corpus",
        year: 2000,
        pmid: "10945490",
      }),
    ],
  },
};
