import type { EncCitation, Peptide } from "./types";
import { pubmedUrl } from "./encyclopaedia";

function cite(
  key: string,
  title: string,
  opts: Partial<Omit<EncCitation, "key" | "title">> = {},
): EncCitation {
  const pmid = opts.pmid;
  return {
    key,
    title,
    authors: opts.authors,
    journal: opts.journal,
    year: opts.year,
    doi: opts.doi,
    pmid,
    nct: opts.nct,
    url: opts.url ?? (pmid ? pubmedUrl(pmid) : opts.doi ? `https://doi.org/${opts.doi}` : undefined),
  };
}

export const encyclopaediaOverlays: Record<string, Partial<Peptide>> = {
  semaglutide: {
    lastReviewed: "2026-09-13",
    molecularFormula: "C187H291N45O59",
    molecularWeight: "4113.6 g·mol⁻¹ (free peptide; salt forms vary)",
    sequence:
      "Modified GLP-1(7–37) analogue with Aib substitution, C18 fatty-diacid acylation and spacer; full residue list is in approved product information.",
    primaryTarget: "GLP-1 receptor (GCGR superfamily; class B GPCR)",
    halfLife: "Approximately 7 days after subcutaneous administration (labelled once-weekly products)",
    routesInvestigated: ["Subcutaneous", "Oral (SNAC co-formulation, separate product)"],
    humanEvidenceLevel: "A",
    researchStatus: "Approved peptide medicine for defined diabetes and/or weight-management indications, depending on brand, dose and jurisdiction.",
    origin: "Synthetic long-acting analogue of human glucagon-like peptide-1, developed for once-weekly or oral incretin therapy.",
    mechanismCertainty: "established",
    mechanismDetail:
      "Semaglutide binds and activates the GLP-1 receptor on pancreatic islet cells and in central and gastrointestinal circuits. Downstream Gs–cAMP signalling increases glucose-dependent insulin secretion and suppresses glucagon when glucose is elevated. Gastric emptying is slowed and appetite-related hypothalamic signalling is altered. These receptor-level effects are established for the GLP-1 agonist class and are described in regulatory product information. Central weight-loss circuitry details continue to be refined in physiology studies.",
    researchAreasDetail: [
      {
        label: "Type 2 diabetes",
        topic: "metabolic",
        evidence: "A",
        summary: "Has been investigated, and in labelled products approved, for glycaemic control in type 2 diabetes.",
        citationKeys: ["sustain6", "ozempic-fda"],
      },
      {
        label: "Chronic weight management",
        topic: "body-composition",
        evidence: "A",
        summary: "Once-weekly subcutaneous semaglutide 2.4 mg has been investigated in the STEP programme and is approved for chronic weight management in eligible adults in several jurisdictions.",
        citationKeys: ["step1"],
      },
      {
        label: "Cardiovascular outcomes",
        topic: "cardiovascular",
        evidence: "A",
        summary: "Cardiovascular outcome trials have examined major adverse cardiovascular events in selected high-risk populations; labelled claims follow local product information.",
        citationKeys: ["sustain6"],
      },
    ],
    humanStudies: [
      {
        id: "step1",
        population: "Adults with overweight or obesity without diabetes",
        n: "1961 randomised",
        studyType: "Phase 3 randomised, double-blind, placebo-controlled",
        compound: "Semaglutide 2.4 mg",
        dose: "2.4 mg once weekly after dose escalation",
        route: "Subcutaneous",
        duration: "68 weeks",
        primaryOutcome: "Percentage change in body weight",
        findings:
          "Mean weight change was greater with semaglutide than placebo. Gastrointestinal adverse events were more common with the active drug.",
        limitations: "Lifestyle intervention in both arms; results apply to the studied 2.4 mg obesity regimen, not to unapproved research-chemical products.",
        citationKey: "step1",
      },
      {
        id: "sustain6",
        population: "Adults with type 2 diabetes at high cardiovascular risk",
        n: "3297",
        studyType: "Randomised, double-blind, placebo-controlled cardiovascular outcome trial",
        compound: "Once-weekly semaglutide (diabetes doses)",
        dose: "0.5 mg or 1.0 mg once weekly",
        route: "Subcutaneous",
        duration: "Median 2.1 years",
        primaryOutcome: "Composite of cardiovascular death, nonfatal MI or nonfatal stroke",
        findings: "The primary composite occurred less often with semaglutide than placebo in this high-risk diabetes population.",
        limitations: "Diabetes doses and population; not a general-population wellness trial.",
        citationKey: "sustain6",
      },
    ],
    preclinicalStudies: [
      {
        id: "glp1-phys",
        model: "Rodent and cellular GLP-1 receptor systems",
        studyType: "Mechanistic / translational pharmacology",
        findings: "GLP-1 receptor agonism reproduces incretin effects on insulin, glucagon and energy intake in animal models. Human labelling rests on clinical trials, not on these models alone.",
        limitations: "Animal energy-intake models do not establish human cosmetic or athletic indications.",
        citationKey: "step1",
      },
    ],
    researchDosesHuman: [
      {
        study: "STEP 1",
        model: "Adults with overweight or obesity",
        dose: "2.4",
        unit: "mg",
        route: "Subcutaneous",
        frequency: "Once weekly",
        duration: "68 weeks",
        purpose: "Weight-management efficacy and safety versus placebo",
        citationKey: "step1",
      },
      {
        study: "SUSTAIN-6",
        model: "Type 2 diabetes, high CV risk",
        dose: "0.5 or 1.0",
        unit: "mg",
        route: "Subcutaneous",
        frequency: "Once weekly",
        duration: "Median 2.1 years",
        purpose: "Cardiovascular outcomes",
        citationKey: "sustain6",
      },
    ],
    approvedDoses: [
      {
        authority: "FDA",
        country: "United States",
        product: "Ozempic (semaglutide) injection",
        indication: "Type 2 diabetes (see current USPI for full labelled uses)",
        regimen: "Once-weekly subcutaneous injection after labelled escalation; maintenance doses are product-specific (commonly 0.5–2 mg range in USPI — verify current label).",
        sourceTitle: "FDA Prescribing Information — Ozempic",
        sourceUrl: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
      {
        authority: "FDA",
        country: "United States",
        product: "Wegovy (semaglutide) injection",
        indication: "Chronic weight management in eligible patients",
        regimen: "Once-weekly subcutaneous 2.4 mg after labelled escalation (verify current USPI).",
        sourceTitle: "FDA Prescribing Information — Wegovy",
        sourceUrl: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
      {
        authority: "TGA",
        country: "Australia",
        product: "ARTG-registered semaglutide presentations",
        indication: "As per the current Australian Product Information for each registered brand",
        regimen: "Follow the Australian PI. Compounded or research-chemical semaglutide is not an ARTG-registered equivalent.",
        sourceTitle: "TGA Product Information / ARTG",
        sourceUrl: "https://www.tga.gov.au/",
      },
    ],
    pharmacokinetics: {
      halfLife: "~1 week (subcutaneous once-weekly products)",
      tmax: "1–3 days to peak concentration after a subcutaneous dose (product-dependent)",
      bioavailability: "High after subcutaneous injection; oral tablets use an absorption enhancer (SNAC) with much lower absolute bioavailability",
      metabolism: "Peptide proteolysis; fatty-acid side chain prolongs albumin binding",
      elimination: "Metabolite clearance; see PI for renal comments",
      notes: "Numeric PK values should be taken from the current PI for the exact product.",
    },
    safetyDetail: {
      adverseEffects: "Nausea, vomiting, diarrhoea, constipation, abdominal pain and reduced appetite are commonly reported in trials.",
      seriousEvents: "Product information discusses pancreatitis, gallbladder disease, acute kidney injury secondary to dehydration, diabetic retinopathy complications in some diabetes trials, and a boxed warning in US labels regarding rodent thyroid C-cell tumours (human relevance uncertain).",
      interactions: "Hypoglycaemia risk increases with insulin or sulfonylureas. Delayed gastric emptying can affect oral drug absorption.",
      excludedPopulations: "Pivotal obesity trials excluded various endocrine and safety populations; see each protocol.",
      pregnancy: "Not recommended in pregnancy; see PI. Discontinue if pregnancy occurs, per label.",
      organImpairment: "Follow PI for renal and hepatic comments; GI adverse events can worsen dehydration.",
      longTerm: "Outcome trials provide multi-year cardiovascular data in selected diabetes populations; lifelong safety in unselected wellness use is not established.",
      unknowns: "Safety of unregulated research-chemical injectables is not characterised and is not implied by approved-product data.",
    },
    regulatoryDetail: {
      tga: "Registered prescription medicine in specific brands and indications on the ARTG. Not a listed complementary medicine. Not sold by Cellular Sequence.",
      fda: "Approved (distinct NDAs/brands) for type 2 diabetes and for chronic weight management, among other labelled uses that must be read from the current USPI.",
      ema: "Centralised authorisations exist for diabetes and obesity products (brand-specific). Confirm SmPC for the exact product.",
    },
    interactions: "Insulin, sulfonylureas, and drugs with a narrow absorption window may need label-directed review.",
    citations: [
      cite("step1", "Once-Weekly Semaglutide in Adults with Overweight or Obesity", {
        authors: "Wilding JPH et al.",
        journal: "N Engl J Med",
        year: 2021,
        doi: "10.1056/NEJMoa2032183",
        pmid: "33567185",
      }),
      cite("sustain6", "Semaglutide and Cardiovascular Outcomes in Patients with Type 2 Diabetes", {
        authors: "Marso SP et al.",
        journal: "N Engl J Med",
        year: 2016,
        doi: "10.1056/NEJMoa1607141",
        pmid: "27633186",
      }),
      cite("ozempic-fda", "Ozempic (semaglutide) prescribing information", {
        authors: "Novo Nordisk / FDA",
        year: 2024,
        url: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      }),
    ],
  },
  tirzepatide: {
    lastReviewed: "2026-09-13",
    molecularFormula: "C225H348N48O68",
    molecularWeight: "4813.5 g·mol⁻¹ (approximate; salt forms vary)",
    sequence: "Acylated dual GIP/GLP-1 receptor agonist peptide; residue map is in product information.",
    primaryTarget: "GIP receptor and GLP-1 receptor",
    halfLife: "Approximately 5 days (supports once-weekly subcutaneous dosing in labelled products)",
    routesInvestigated: ["Subcutaneous"],
    humanEvidenceLevel: "A",
    researchStatus: "Approved dual incretin agonist for type 2 diabetes and, in some markets/brands, chronic weight management.",
    origin: "Synthetic peptide engineered from a GIP backbone with dual GIP and GLP-1 activity and a fatty-acid moiety for extended duration.",
    mechanismCertainty: "established",
    mechanismDetail:
      "Tirzepatide is a dual agonist at glucose-dependent insulinotropic polypeptide (GIP) receptors and GLP-1 receptors. Combined incretin-receptor activity affects insulin secretion, glucagon, gastric emptying and appetite. The dual pharmacology is distinct from single GLP-1 agonists. Fine mapping of which receptor contributes which clinical effect is still being studied; the approved indications rest on Phase 3 programmes, not on incomplete receptor-attribution models.",
    researchAreasDetail: [
      {
        label: "Type 2 diabetes",
        topic: "metabolic",
        evidence: "A",
        summary: "SURPASS Phase 3 trials have investigated glycaemic control versus comparators.",
        citationKeys: ["surpass2"],
      },
      {
        label: "Obesity / weight management",
        topic: "body-composition",
        evidence: "A",
        summary: "SURMOUNT-1 investigated once-weekly tirzepatide for weight reduction in adults with obesity.",
        citationKeys: ["surmount1"],
      },
    ],
    humanStudies: [
      {
        id: "surmount1",
        population: "Adults with obesity or overweight plus comorbidity, without diabetes",
        n: "2539",
        studyType: "Phase 3 randomised, double-blind, placebo-controlled",
        compound: "Tirzepatide 5, 10 or 15 mg",
        dose: "5–15 mg once weekly after escalation",
        route: "Subcutaneous",
        duration: "72 weeks",
        primaryOutcome: "Percentage change in body weight",
        findings: "Dose-dependent mean weight reduction versus placebo, with gastrointestinal adverse events as the leading tolerability issue.",
        limitations: "Selected trial population; branded product only.",
        citationKey: "surmount1",
      },
    ],
    preclinicalStudies: [
      {
        id: "dual-incretin",
        model: "Cellular dual-receptor pharmacology",
        studyType: "In-vitro / translational",
        findings: "The molecule shows activity at both GIP and GLP-1 receptors. Proposed mechanism details of tissue contribution should be labelled as still under study where not in the PI.",
        limitations: "Receptor profiles do not equal unapproved indications.",
        citationKey: "surmount1",
      },
    ],
    researchDosesHuman: [
      {
        study: "SURMOUNT-1",
        model: "Adults with obesity",
        dose: "5, 10 or 15",
        unit: "mg",
        route: "Subcutaneous",
        frequency: "Once weekly",
        duration: "72 weeks",
        purpose: "Weight-management efficacy",
        citationKey: "surmount1",
      },
    ],
    approvedDoses: [
      {
        authority: "FDA",
        country: "United States",
        product: "Mounjaro / Zepbound (tirzepatide) — brand depends on indication",
        indication: "Type 2 diabetes (Mounjaro) and chronic weight management (Zepbound) as labelled",
        regimen: "Once-weekly subcutaneous injection after labelled escalation to 5, 10 or 15 mg (confirm current USPI).",
        sourceTitle: "FDA Prescribing Information — tirzepatide products",
        sourceUrl: "https://www.accessdata.fda.gov/scripts/cder/daf/",
      },
      {
        authority: "TGA",
        country: "Australia",
        product: "ARTG-registered tirzepatide presentations",
        indication: "As per current Australian PI",
        regimen: "Follow the Australian Product Information for the registered brand.",
        sourceTitle: "TGA Product Information",
        sourceUrl: "https://www.tga.gov.au/",
      },
    ],
    pharmacokinetics: {
      halfLife: "~5 days",
      metabolism: "Proteolytic degradation of the peptide backbone",
      notes: "Use the current PI for Cmax/Tmax tables.",
    },
    safetyDetail: {
      adverseEffects: "Gastrointestinal events predominate (nausea, diarrhoea, vomiting, constipation).",
      seriousEvents: "Class discussions include pancreatitis, gallbladder disease, hypoglycaemia with insulin/secretagogues, and thyroid C-cell tumour warning in US labels (rodent findings).",
      pregnancy: "Not recommended; see PI.",
      unknowns: "Unregulated compounded dual-agonist products are not equivalent to labelled tirzepatide.",
    },
    regulatoryDetail: {
      tga: "Prescription medicine where registered; indication-specific. Not sold here.",
      fda: "Approved as separate branded products for diabetes and weight management.",
      ema: "Authorised products exist; read the SmPC for the exact name and indication.",
    },
    citations: [
      cite("surmount1", "Tirzepatide Once Weekly for the Treatment of Obesity", {
        authors: "Jastreboff AM et al.",
        journal: "N Engl J Med",
        year: 2022,
        doi: "10.1056/NEJMoa2206038",
        pmid: "35658024",
      }),
      cite("surpass2", "Tirzepatide versus Semaglutide Once Weekly in Patients with Type 2 Diabetes", {
        authors: "Frías JP et al.",
        journal: "N Engl J Med",
        year: 2021,
        doi: "10.1056/NEJMoa2107519",
        pmid: "34170647",
      }),
    ],
  },
  "bpc-157": {
    lastReviewed: "2026-09-13",
    molecularFormula: "C62H98N16O22",
    molecularWeight: "1419.5 g·mol⁻¹",
    sequence: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val (BPC-157 pentadecapeptide)",
    primaryTarget: "Proposed: angiogenic and nitric-oxide related pathways; growth-factor signalling. Mechanism not yet fully established in humans.",
    halfLife: "Insufficient reliable evidence identified for a validated human plasma half-life.",
    routesInvestigated: ["Oral (preclinical and limited human reports)", "Intraperitoneal / subcutaneous (animal)", "Topical (preclinical)"],
    humanEvidenceLevel: "C",
    researchStatus: "Investigational pentadecapeptide. Not an approved human therapeutic in Australia, the US or the EU.",
    origin: "Synthetic fragment derived from a gastric protein sequence studied mainly in animal models of injury.",
    mechanismCertainty: "not-fully-established",
    mechanismDetail:
      "Proposed mechanism: BPC-157 has been reported in preclinical literature to influence angiogenesis, nitric oxide signalling and growth-factor related repair pathways. Binding to a single validated human drug receptor comparable to GLP-1 agonists has not been established. Mechanism not yet fully established. Observed animal-model findings should not be read as proven human tissue repair.",
    researchAreasDetail: [
      {
        label: "Soft-tissue injury models",
        topic: "tendon",
        evidence: "D",
        summary: "Preclinical studies suggest effects in rodent tendon, ligament and muscle-injury models. These are not demonstrated clinical indications.",
        citationKeys: ["sikiric-review"],
      },
      {
        label: "Gastrointestinal injury models",
        topic: "gut",
        evidence: "D",
        summary: "Animal studies have examined experimental GI lesions. Early human research is sparse and not registrational.",
        citationKeys: ["sikiric-review"],
      },
    ],
    humanStudies: [
      {
        id: "human-limited",
        population: "Insufficient reliable evidence identified for a pivotal, adequately powered, peer-reviewed human RCT that would support therapeutic use.",
        n: "Not established as a registrational evidence base",
        studyType: "No Phase 3 therapeutic programme identified",
        compound: "BPC-157",
        dose: "Insufficient reliable evidence identified for an approved human dose",
        route: "Various uncontrolled reports exist; not an approved route",
        duration: "Insufficient reliable evidence identified",
        primaryOutcome: "No labelled human indication",
        findings: "A robust, independently replicated human efficacy dataset comparable to approved peptide medicines was not identified.",
        limitations: "Grey-market use is not a clinical evidence base.",
        citationKey: "sikiric-review",
      },
    ],
    preclinicalStudies: [
      {
        id: "rodent-tendon",
        model: "Rodent tendon and muscle injury",
        studyType: "Animal experimental",
        findings: "Preclinical studies suggest improved healing metrics in some injury models. Species, injury method and dose are not interchangeable with human practice.",
        limitations: "Do not convert mg/kg animal doses to human treatment schedules.",
        citationKey: "sikiric-review",
      },
    ],
    researchDosesAnimal: [
      {
        study: "Representative rodent BPC-157 injury models (literature range)",
        model: "Rats / mice (varies by paper)",
        dose: "Typically microgram/kg intraperitoneal or oral ranges in cited reviews — verify each paper",
        unit: "µg/kg (animal)",
        route: "Intraperitoneal, oral or topical depending on experiment",
        frequency: "Study-specific",
        duration: "Study-specific",
        purpose: "Experimental tissue-injury pharmacology",
        citationKey: "sikiric-review",
      },
    ],
    pharmacokinetics: {
      notes: "Reliable human pharmacokinetic data were not identified. Do not infer human half-life from rodent papers.",
    },
    safetyDetail: {
      adverseEffects: "A systematic human adverse-event profile comparable to labelled drugs was not identified.",
      seriousEvents: "Unknowns include contamination, mislabelling and infection risk from unregulated injectables.",
      longTerm: "Long-term human safety is unknown.",
      unknowns: "No evidence of harm in a given animal paper does not mean the compound is safe in people.",
    },
    regulatoryDetail: {
      tga: "Not approved as a human therapeutic medicine for tissue repair. Research-chemical listings are not ARTG-registered medicines.",
      fda: "Not approved. FDA has warned about unapproved peptide compounding including BPC-157 in compounding contexts.",
      ema: "Not authorised as a human peptide medicine for the grey-market indications advertised online.",
    },
    citations: [
      cite("sikiric-review", "Brain-gut axis and pentadecapeptide BPC 157: Theoretical and practical implications", {
        authors: "Sikiric P et al.",
        journal: "Curr Neuropharmacol",
        year: 2016,
        pmid: "27165480",
      }),
      cite("fda-compounding", "FDA communications on unapproved peptide compounding (BPC-157 listed among peptides of concern in compounding policy discussions)", {
        authors: "U.S. Food and Drug Administration",
        year: 2023,
        url: "https://www.fda.gov/",
      }),
    ],
  },
  "ghk-cu": {
    lastReviewed: "2026-09-13",
    molecularFormula: "C14H24N6O4 · Cu",
    molecularWeight: "340.4 g·mol⁻¹ (tripeptide); copper complex higher",
    sequence: "Gly-His-Lys (GHK) coordinated with Cu(II) in the cosmetic copper-tripeptide complex",
    primaryTarget: "Proposed: extracellular-matrix and copper-dependent enzyme pathways in skin models. Mechanism not yet fully established as a systemic drug target.",
    halfLife: "Insufficient reliable evidence identified for systemic human PK (topical cosmetic use is local).",
    routesInvestigated: ["Topical (cosmetic)", "In-vitro fibroblast systems"],
    humanEvidenceLevel: "C",
    researchStatus: "Cosmetic / dermatological peptide complex. Not an approved injectable medicine.",
    origin: "Endogenous human tripeptide fragment associated with extracellular-matrix turnover; the copper complex is used in topical cosmetics.",
    mechanismCertainty: "proposed",
    mechanismDetail:
      "Proposed mechanism: GHK-Cu is described in dermatological literature as a copper-binding tripeptide that can modulate fibroblast behaviour and extracellular-matrix related gene expression in cell and skin models. These are laboratory and cosmetic-grade observations. Mechanism not yet fully established as a registered drug pathway. Injectable use is not an approved cosmetic route.",
    researchAreasDetail: [
      {
        label: "Topical skin appearance",
        topic: "skin",
        evidence: "C",
        summary: "Early human and cosmetic studies have examined wrinkle appearance and skin parameters in leave-on formulas. This is not a pharmaceutical indication.",
        citationKeys: ["pickart2015"],
      },
      {
        label: "Hair appearance",
        topic: "hair",
        evidence: "E",
        summary: "Mechanistic/theoretical and supplier-adjacent claims exist; independent pharmaceutical-grade hair-growth RCTs were not identified as a labelled indication.",
        citationKeys: ["pickart2015"],
      },
    ],
    humanStudies: [
      {
        id: "cosmetic-skin",
        population: "Adults in cosmetic dermatology settings (study quality varies)",
        n: "Typically small cosmetic panels",
        studyType: "Cosmetic / open or vehicle-controlled skin-appearance studies",
        compound: "Topical GHK-Cu",
        dose: "Leave-on cosmetic concentrations (formula-specific; not a drug dose)",
        route: "Topical",
        duration: "Weeks (study-specific)",
        primaryOutcome: "Appearance metrics (wrinkles, elasticity photography)",
        findings: "Some cosmetic studies report appearance changes. These are not Phase 3 drug results.",
        limitations: "Industry studies, combination formulas, and small samples are common.",
        citationKey: "pickart2015",
      },
    ],
    preclinicalStudies: [
      {
        id: "fibroblast",
        model: "Human dermal fibroblasts / skin explants",
        studyType: "In-vitro",
        findings: "Preclinical studies suggest gene-expression changes related to matrix proteins. In-vitro findings are not clinical outcomes.",
        limitations: "Culture conditions do not equal in-vivo dosing.",
        citationKey: "pickart2015",
      },
    ],
    researchDosesHuman: [
      {
        study: "Cosmetic GHK-Cu leave-on products (literature / formula reports)",
        model: "Adults, topical cosmetics",
        dose: "Formula-specific (often low-percentage leave-on)",
        unit: "% w/w in finished cosmetic",
        route: "Topical",
        frequency: "Once or twice daily in typical cosmetic protocols",
        duration: "Study-specific",
        purpose: "Skin-appearance endpoints",
        citationKey: "pickart2015",
      },
    ],
    pharmacokinetics: {
      notes: "Systemic human PK after cosmetic application is not characterised like a registered injectable drug. Reliable systemic half-life data were not identified.",
    },
    safetyDetail: {
      adverseEffects: "Topical irritation or copper-related staining is possible. Do not inject cosmetic serums.",
      unknowns: "Unregulated injectable GHK-Cu is a different risk profile from leave-on cosmetics.",
    },
    regulatoryDetail: {
      tga: "Permitted in cosmetics when formulated and advertised within cosmetic rules. Not an ARTG injectable medicine.",
      fda: "Cosmetic ingredient use is not an NDA drug approval for injection.",
      ema: "Cosmetic ingredient, not a centralised peptide drug for systemic use.",
    },
    citations: [
      cite("pickart2015", "GHK Peptide as a Natural Modulator of Multiple Cellular Pathways in Skin Regeneration", {
        authors: "Pickart L, Margolina A",
        journal: "Biomed Res Int",
        year: 2015,
        pmid: "25960412",
        doi: "10.1155/2015/648108",
      }),
    ],
  },
};
