import type {
  OilTabletCategory,
  OilTabletEntry,
  OilTabletForm,
  RegulatoryBadge,
} from "./types";
import { OIL_TABLET_CATEGORY_LABELS, OIL_TABLET_FORM_LABELS } from "./types";

const auSteroid =
  "Anabolic–androgenic steroids are prescription-only (typically Schedule 4) in Australia. Unlicensed importation, supply or advertising as a bodybuilding product is unlawful. Longevity Protocol does not sell oils, tablets, or blends of this class.";

const auResearch =
  "Not a registered sports or anti-ageing medicine in this presentation. Research-chemical and grey-market tablets are not sold here.";

const auMedicine =
  "Licensed brands exist for specific medical indications. Unlabelled catalogue tablets are not those products and are not sold by Longevity Protocol.";

function item(opts: {
  slug: string;
  name: string;
  aliases?: string[];
  forms: OilTabletForm[];
  category: OilTabletCategory;
  chemicalClass: string;
  presentations: string[];
  what: string;
  risks: string;
  reg: string;
  au: string;
  kind: "steroid" | "research" | "medicine" | "poison";
  terms?: string[];
  peptideHref?: string;
}): OilTabletEntry {
  const badges: RegulatoryBadge[] =
    opts.kind === "medicine"
      ? ["APPROVED_MEDICINE"]
      : opts.kind === "poison"
        ? ["NOT_APPROVED_FOR_HUMAN_USE"]
        : ["RESEARCH_ONLY", "NOT_APPROVED_FOR_HUMAN_USE"];
  return {
    slug: opts.slug,
    name: opts.name,
    alternativeNames: opts.aliases ?? [],
    forms: opts.forms,
    category: opts.category,
    chemicalClass: opts.chemicalClass,
    cataloguePresentations: opts.presentations,
    whatItIs: opts.what,
    risks: opts.risks,
    regulatoryStatus: opts.reg,
    australianRegulatoryStatus: opts.au,
    badges,
    searchTerms: opts.terms ?? [],
    peptideHref: opts.peptideHref,
  };
}

const aasRisk =
  "Androgenic and anabolic effects, suppression of natural testosterone, infertility, dyslipidaemia, hypertension, hepatotoxicity (especially 17α-alkylated orals), psychiatric change, and injection-site infection for oils. Sport-banned.";

/** Unique parent compounds from oil and tablet wholesale lists. No prices, SKUs, or dosing protocols. */
export const oilTabletEntries: OilTabletEntry[] = [
  item({
    slug: "testosterone",
    name: "Testosterone",
    aliases: ["Sustanon-type blends", "testosterone no ester", "TNE"],
    forms: ["oil"],
    category: "anabolic-steroid",
    chemicalClass: "Endogenous androgen / anabolic–androgenic steroid",
    presentations: [
      "Cypionate",
      "Enanthate",
      "Undecanoate",
      "Propionate",
      "Acetate",
      "Phenylpropionate",
      "Isocaproate",
      "Decanoate",
      "Aqueous suspension",
      "No-ester (TNE)",
      "Multi-ester mixes (Sustanon-style, ‘supertest’, high-mg blends)",
    ],
    what: "The primary male sex hormone. Licensed replacement products exist as specific brands. Underground multi-ester oils are not TRT clinic stock.",
    risks: aasRisk,
    reg: "Approved as specific prescription presentations; grey-market oils are unlicensed.",
    au: auSteroid,
    kind: "steroid",
    terms: ["cypionate", "enanthate", "sustanon", "tne", "propionate"],
  }),
  item({
    slug: "trenbolone",
    name: "Trenbolone",
    aliases: ["Finaplix-related 19-nor androgen"],
    forms: ["oil"],
    category: "anabolic-steroid",
    chemicalClass: "19-nortestosterone-derived AAS",
    presentations: [
      "Acetate",
      "Enanthate",
      "Hexahydrobenzyl carbonate",
      "Base (no ester)",
      "Acetate/enanthate mixes",
      "Tri-ester mixes",
      "Blends with testosterone and drostanolone",
    ],
    what: "A veterinary-origin androgen with no legitimate bodybuilding indication. Not a peptide.",
    risks: `${aasRisk} Night sweats, insomnia, prolactin-related sexual dysfunction, and marked lipid harm are commonly discussed clinically.`,
    reg: "Not an approved human bodybuilding medicine.",
    au: auSteroid,
    kind: "steroid",
    terms: ["tren", "trenmix", "tritren"],
  }),
  item({
    slug: "nandrolone",
    name: "Nandrolone",
    aliases: ["Deca", "NPP"],
    forms: ["oil"],
    category: "anabolic-steroid",
    chemicalClass: "19-nortestosterone AAS",
    presentations: ["Decanoate", "Phenylpropionate (NPP)", "Decanoate/NPP mixes"],
    what: "A 19-nor androgen. Licensed nandrolone exists in limited medical contexts; catalogue ‘deca’ oils are not that product.",
    risks: aasRisk,
    reg: "Prescription androgen class; unlicensed oils are not sold here.",
    au: auSteroid,
    kind: "steroid",
    terms: ["deca", "npp", "decanoate"],
  }),
  item({
    slug: "boldenone",
    name: "Boldenone",
    aliases: ["Equipoise", "EQ"],
    forms: ["oil"],
    category: "anabolic-steroid",
    chemicalClass: "1,4-diene AAS (veterinary-origin)",
    presentations: ["Undecylenate", "Cypionate"],
    what: "A veterinary androgen historically marketed as Equipoise. Not a human sports medicine.",
    risks: aasRisk,
    reg: "Not a legitimate consumer hormone product.",
    au: auSteroid,
    kind: "steroid",
    terms: ["equipoise", "undecylenate"],
  }),
  item({
    slug: "drostanolone",
    name: "Drostanolone",
    aliases: ["Masteron"],
    forms: ["oil"],
    category: "anabolic-steroid",
    chemicalClass: "DHT-derived AAS",
    presentations: ["Propionate", "Enanthate", "Propionate/enanthate mixes"],
    what: "A dihydrotestosterone-derived androgen. Not a cutting peptide.",
    risks: aasRisk,
    reg: "Unlicensed bodybuilding oils are not approved medicines here.",
    au: auSteroid,
    kind: "steroid",
    terms: ["masteron", "mast"],
  }),
  item({
    slug: "metenolone",
    name: "Metenolone",
    aliases: ["Methenolone", "Primobolan", "Primo"],
    forms: ["oil", "tablet"],
    category: "anabolic-steroid",
    chemicalClass: "DHT-derived AAS",
    presentations: ["Enanthate (oil)", "Acetate (tablets)"],
    what: "A milder-marketed AAS still in the steroid class. Oil and oral acetate appear on separate lists.",
    risks: aasRisk,
    reg: "Prescription androgen class where licensed; grey-market primo is unlicensed.",
    au: auSteroid,
    kind: "steroid",
    terms: ["primobolan", "methenolone"],
  }),
  item({
    slug: "stanozolol",
    name: "Stanozolol",
    aliases: ["Winstrol"],
    forms: ["oil", "tablet"],
    category: "anabolic-steroid",
    chemicalClass: "17α-alkylated AAS",
    presentations: ["Oral tablets", "Oil solution", "Aqueous suspension"],
    what: "A 17α-alkylated androgen sold as tablets and as injectable oil or water-based suspension.",
    risks: `${aasRisk} Oral 17α-alkylation adds particular liver strain.`,
    reg: "Prescription androgen where licensed historically; catalogue winstrol is unlicensed here.",
    au: auSteroid,
    kind: "steroid",
    terms: ["winstrol", "winny"],
  }),
  item({
    slug: "methandienone",
    name: "Methandienone",
    aliases: ["Dianabol", "Methandrostenolone"],
    forms: ["oil", "tablet"],
    category: "anabolic-steroid",
    chemicalClass: "17α-alkylated AAS",
    presentations: ["Oral tablets", "Injectable oil"],
    what: "Classic oral AAS, also listed as an injectable oil on some catalogues.",
    risks: `${aasRisk} Hepatotoxicity is a leading oral-AAS concern.`,
    reg: "Not a legitimate over-the-counter muscle tablet.",
    au: auSteroid,
    kind: "steroid",
    terms: ["dianabol", "dbol", "methandrostenolone"],
  }),
  item({
    slug: "oxymetholone",
    name: "Oxymetholone",
    aliases: ["Anadrol"],
    forms: ["oil", "tablet"],
    category: "anabolic-steroid",
    chemicalClass: "17α-alkylated AAS",
    presentations: ["Oral tablets", "Injectable oil"],
    what: "A highly hepatotoxic oral androgen, also appearing as an oil on some lists.",
    risks: `${aasRisk} Marked liver and lipid effects.`,
    reg: "Prescription haematology history in some markets; grey-market anadrol is unlicensed here.",
    au: auSteroid,
    kind: "steroid",
    terms: ["anadrol", "adrol"],
  }),
  item({
    slug: "oxandrolone",
    name: "Oxandrolone",
    aliases: ["Anavar"],
    forms: ["tablet"],
    category: "anabolic-steroid",
    chemicalClass: "17α-alkylated AAS",
    presentations: ["Oral tablets"],
    what: "An oral DHT-derived AAS. Licensed wasting indications exist in some countries as specific brands.",
    risks: `${aasRisk} Still liver-active despite ‘mild’ marketing.`,
    reg: "Prescription androgen where licensed; catalogue anavar is unlicensed here.",
    au: auSteroid,
    kind: "steroid",
    terms: ["anavar", "var"],
  }),
  item({
    slug: "fluoxymesterone",
    name: "Fluoxymesterone",
    aliases: ["Halotestin"],
    forms: ["tablet"],
    category: "anabolic-steroid",
    chemicalClass: "17α-alkylated AAS",
    presentations: ["Oral tablets"],
    what: "A potent oral androgen. Not a strength supplement.",
    risks: aasRisk,
    reg: "Prescription androgen class; not sold here.",
    au: auSteroid,
    kind: "steroid",
    terms: ["halotestin", "halo"],
  }),
  item({
    slug: "chlorodehydromethyltestosterone",
    name: "Chlorodehydromethyltestosterone",
    aliases: ["Turinabol", "Tbol"],
    forms: ["tablet"],
    category: "anabolic-steroid",
    chemicalClass: "17α-alkylated AAS",
    presentations: ["Oral tablets"],
    what: "Oral AAS associated with historical state doping programmes. Not a peptide.",
    risks: aasRisk,
    reg: "Not a consumer medicine here.",
    au: auSteroid,
    kind: "steroid",
    terms: ["turinabol", "cdmt"],
  }),
  item({
    slug: "mesterolone",
    name: "Mesterolone",
    aliases: ["Proviron"],
    forms: ["tablet"],
    category: "anabolic-steroid",
    chemicalClass: "DHT-derived oral androgen",
    presentations: ["Oral tablets"],
    what: "An oral DHT analogue sometimes used in specialist androgen protocols. Not an anti-oestrogen peptide.",
    risks: "Androgenic effects, DHT-related skin/prostate issues; not a PCT supplement.",
    reg: "Prescription androgen where licensed.",
    au: auSteroid,
    kind: "steroid",
    terms: ["proviron"],
  }),
  item({
    slug: "methasterone",
    name: "Methasterone",
    aliases: ["Superdrol", "Methyldrostanolone"],
    forms: ["oil", "tablet"],
    category: "anabolic-steroid",
    chemicalClass: "Designer 17α-alkylated AAS",
    presentations: ["Oral tablets", "Injectable oil"],
    what: "A designer oral AAS later listed as an injectable. High hepatotoxicity reputation.",
    risks: `${aasRisk} Severe liver injury reports in the designer-steroid literature.`,
    reg: "Not an approved medicine.",
    au: auSteroid,
    kind: "steroid",
    terms: ["superdrol", "methyldrostanolone"],
  }),
  item({
    slug: "methylstenbolone",
    name: "Methylstenbolone",
    forms: ["tablet"],
    category: "anabolic-steroid",
    chemicalClass: "Designer 17α-alkylated AAS",
    presentations: ["Oral tablets"],
    what: "A designer oral androgen on research-chemical tablet lists.",
    risks: aasRisk,
    reg: "Not approved.",
    au: auSteroid,
    kind: "steroid",
    terms: ["ultradrol"],
  }),
  item({
    slug: "methyl-1-testosterone",
    name: "17α-Methyl-1-testosterone",
    aliases: ["M1T"],
    forms: ["tablet"],
    category: "anabolic-steroid",
    chemicalClass: "Designer 17α-alkylated AAS",
    presentations: ["Oral tablets"],
    what: "A methylated 1-testosterone analogue. Not a peptide.",
    risks: aasRisk,
    reg: "Not approved.",
    au: auSteroid,
    kind: "steroid",
    terms: ["m1t"],
  }),
  item({
    slug: "dihydroboldenone",
    name: "1-Testosterone (dihydroboldenone)",
    aliases: ["DHB", "1-testosterone cypionate"],
    forms: ["oil", "tablet"],
    category: "anabolic-steroid",
    chemicalClass: "1-testosterone AAS",
    presentations: ["Cypionate oil", "Oral tablets on some lists"],
    what: "A 1-testosterone / DHB androgen, not the same as testosterone cypionate.",
    risks: aasRisk,
    reg: "Not a consumer hormone product.",
    au: auSteroid,
    kind: "steroid",
    terms: ["dhb", "1-test"],
  }),
  item({
    slug: "trestolone",
    name: "Trestolone",
    aliases: ["MENT", "Trestolone acetate"],
    forms: ["oil"],
    category: "anabolic-steroid",
    chemicalClass: "7α-methyl-19-nortestosterone",
    presentations: ["Acetate oil"],
    what: "An experimental androgen (MENT). Not male-contraceptive DIY.",
    risks: aasRisk,
    reg: "Investigational/unlicensed as a bodybuilding oil.",
    au: auSteroid,
    kind: "steroid",
    terms: ["ment"],
  }),
  item({
    slug: "androstanolone",
    name: "Androstanolone (DHT)",
    aliases: ["Stanolone"],
    forms: ["oil"],
    category: "anabolic-steroid",
    chemicalClass: "Dihydrotestosterone",
    presentations: ["Injectable oil"],
    what: "Dihydrotestosterone itself. Not a hair-loss treatment in this form.",
    risks: "Potent androgenic effects including prostate and skin; suppression of HPG axis.",
    reg: "Androgen class; not sold here.",
    au: auSteroid,
    kind: "steroid",
    terms: ["dht", "stanolone"],
  }),
  item({
    slug: "metribolone",
    name: "Metribolone",
    aliases: ["Methyltrienolone", "R1881"],
    forms: ["oil"],
    category: "anabolic-steroid",
    chemicalClass: "Extremely potent 19-nor AAS / research androgen",
    presentations: ["Low-mg injectable oil on catalogues"],
    what: "One of the most potent synthetic androgens, used as a research ligand. Not a cycle drug.",
    risks: "Severe hepatotoxicity and androgen toxicity in the literature. Not for human use.",
    reg: "Research androgen. Not approved.",
    au: auSteroid,
    kind: "steroid",
    terms: ["methyltrienolone", "r1881"],
  }),
  item({
    slug: "estradiol-cypionate",
    name: "Estradiol cypionate",
    forms: ["oil"],
    category: "endocrine-accessory",
    chemicalClass: "Oestrogen ester",
    presentations: ["Injectable oil"],
    what: "An oestradiol ester. Licensed hormone products exist; underground oils are not HRT clinic stock.",
    risks: "Thrombosis, breast tenderness, mood change; inappropriate in unsupervised androgen cycles.",
    reg: "Prescription hormone where licensed.",
    au: auMedicine,
    kind: "medicine",
    terms: ["estradiol", "oestradiol"],
  }),
  item({
    slug: "ligandrol",
    name: "Ligandrol (LGD-4033)",
    aliases: ["LGD-4033"],
    forms: ["tablet"],
    category: "sarm-secretagogue",
    chemicalClass: "Selective androgen receptor modulator (investigational)",
    presentations: ["Oral tablets"],
    what: "An investigational SARM. Sport-banned. Not a mild steroid alternative that is legal to sell as a supplement.",
    risks: "Testosterone suppression, lipid changes, liver-test abnormalities in reports.",
    reg: "Not an approved medicine or listed supplement for muscle building.",
    au: auResearch,
    kind: "research",
    terms: ["lgd", "lgd-4033"],
  }),
  item({
    slug: "ostarine",
    name: "Ostarine (MK-2866)",
    aliases: ["Enobosarm", "MK-2866"],
    forms: ["tablet"],
    category: "sarm-secretagogue",
    chemicalClass: "Investigational SARM",
    presentations: ["Oral tablets"],
    what: "An investigational SARM. Not a peptide. Not sold.",
    risks: "Axis suppression and lipid/liver signals in the class.",
    reg: "Not approved for bodybuilding.",
    au: auResearch,
    kind: "research",
    terms: ["mk-2866", "enobosarm"],
  }),
  item({
    slug: "rad140",
    name: "RAD140 (testolone)",
    aliases: ["Testolone"],
    forms: ["tablet"],
    category: "sarm-secretagogue",
    chemicalClass: "Investigational SARM",
    presentations: ["Oral tablets"],
    what: "Investigational SARM. Sport-banned.",
    risks: "Androgen-class suppression and hepatotoxicity case reports.",
    reg: "Not approved.",
    au: auResearch,
    kind: "research",
    terms: ["testolone"],
  }),
  item({
    slug: "andarine",
    name: "Andarine (S4)",
    aliases: ["S4"],
    forms: ["tablet"],
    category: "sarm-secretagogue",
    chemicalClass: "Investigational SARM",
    presentations: ["Oral tablets"],
    what: "Early SARM associated with visual-disturbance reports.",
    risks: "Night vision / yellow-tint visual effects in anecdotal and some study reports; axis suppression.",
    reg: "Not approved.",
    au: auResearch,
    kind: "research",
    terms: ["s4"],
  }),
  item({
    slug: "yk11",
    name: "YK-11",
    forms: ["tablet"],
    category: "sarm-secretagogue",
    chemicalClass: "Steroidal myostatin-pathway research agent",
    presentations: ["Oral tablets"],
    what: "A steroidal compound marketed as a SARM. Not a peptide follistatin substitute.",
    risks: "Limited human data; androgen and liver risk assumed.",
    reg: "Not approved.",
    au: auResearch,
    kind: "research",
    terms: ["yk11"],
  }),
  item({
    slug: "cardarine",
    name: "Cardarine (GW-501516)",
    aliases: ["GW-501516", "GW1516"],
    forms: ["tablet"],
    category: "sarm-secretagogue",
    chemicalClass: "PPARδ agonist (not a SARM, not a peptide)",
    presentations: ["Oral tablets"],
    what: "A metabolic research agent abandoned after rodent cancer signals. Still sold on SARM lists.",
    risks: "Carcinogenicity signal in animals; not a fat-loss supplement.",
    reg: "Development halted. Not approved.",
    au: auResearch,
    kind: "research",
    terms: ["gw501516", "endurobol"],
  }),
  item({
    slug: "sr9009",
    name: "SR9009 (stenabolic)",
    aliases: ["Stenabolic"],
    forms: ["tablet"],
    category: "sarm-secretagogue",
    chemicalClass: "Rev-Erbα agonist (research)",
    presentations: ["Oral tablets"],
    what: "An experimental circadian/metabolic ligand, not a SARM and not a peptide.",
    risks: "Unknown long-term human safety; poor oral pharmacokinetics in literature.",
    reg: "Not approved.",
    au: auResearch,
    kind: "research",
    terms: ["stenabolic"],
  }),
  item({
    slug: "clomifene",
    name: "Clomifene",
    aliases: ["Clomiphene", "Clomid"],
    forms: ["tablet"],
    category: "endocrine-accessory",
    chemicalClass: "Selective oestrogen receptor modulator",
    presentations: ["Oral tablets"],
    what: "A prescription fertility SERM. Catalogue ‘PCT’ bottles are not clinic stock.",
    risks: "Visual symptoms, mood change, multiple pregnancy in people with ovaries, thromboembolism class risk.",
    reg: "Approved prescription medicine as specific brands.",
    au: auMedicine,
    kind: "medicine",
    terms: ["clomid", "clomiphene"],
  }),
  item({
    slug: "enclomifene",
    name: "Enclomifene",
    aliases: ["Androxal", "Enclomiphene"],
    forms: ["tablet"],
    category: "endocrine-accessory",
    chemicalClass: "Trans-isomer of clomifene (investigational / limited licensing)",
    presentations: ["Oral tablets"],
    what: "The trans isomer of clomifene, marketed on grey lists as a testosterone tablet. Not a peptide.",
    risks: "SERM-class risks; not a TRT substitute from a research bottle.",
    reg: "Not an approved Australian consumer medicine in this form.",
    au: auResearch,
    kind: "research",
    terms: ["androxal", "enclomiphene"],
  }),
  item({
    slug: "tamoxifen",
    name: "Tamoxifen",
    aliases: ["Nolvadex"],
    forms: ["tablet"],
    category: "endocrine-accessory",
    chemicalClass: "SERM (breast-cancer medicine class)",
    presentations: ["Oral tablets"],
    what: "A prescription oncology/endocrine medicine. Not gynaecomastia chewing gum.",
    risks: "Thrombosis, endometrial changes, hot flushes — follow product information.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["nolvadex"],
  }),
  item({
    slug: "letrozole",
    name: "Letrozole",
    aliases: ["Femara"],
    forms: ["tablet"],
    category: "endocrine-accessory",
    chemicalClass: "Aromatase inhibitor",
    presentations: ["Oral tablets"],
    what: "A prescription aromatase inhibitor for breast cancer. Catastrophic oestradiol collapse if misused.",
    risks: "Bone loss, lipid change, joint pain, profound hypo-oestrogenism.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["femara", "letrazole"],
  }),
  item({
    slug: "anastrozole",
    name: "Anastrozole",
    aliases: ["Arimidex"],
    forms: ["tablet"],
    category: "endocrine-accessory",
    chemicalClass: "Aromatase inhibitor",
    presentations: ["Oral tablets"],
    what: "Prescription AI. Not an on-cycle accessory from a research bottle.",
    risks: "Bone density and lipid harm; hypo-oestrogen symptoms.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["arimidex"],
  }),
  item({
    slug: "exemestane",
    name: "Exemestane",
    aliases: ["Aromasin"],
    forms: ["tablet"],
    category: "endocrine-accessory",
    chemicalClass: "Steroidal aromatase inhibitor",
    presentations: ["Oral tablets"],
    what: "Prescription irreversible AI.",
    risks: "Hypo-oestrogenism, bone and lipid effects.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["aromasin"],
  }),
  item({
    slug: "cabergoline",
    name: "Cabergoline",
    aliases: ["Dostinex"],
    forms: ["tablet"],
    category: "endocrine-accessory",
    chemicalClass: "Dopamine agonist",
    presentations: ["Oral tablets"],
    what: "A prescription prolactin-lowering medicine. Not a trenbolone side-effect chew.",
    risks: "Valvular heart disease, impulse-control disorders, syncope — specialist medicine.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["dostinex"],
  }),
  item({
    slug: "clenbuterol",
    name: "Clenbuterol",
    forms: ["tablet"],
    category: "thyroid-stimulant",
    chemicalClass: "β2-agonist (anabolic-adjacent stimulant)",
    presentations: ["Oral tablets (microgram strengths on catalogues)"],
    what: "A veterinary/selected-human bronchodilator misused for fat loss. Cardiac toxicity is the story, not ‘cutting’.",
    risks: "Tachycardia, arrhythmia, hypokalaemia, tremor, sudden death reports in misuse.",
    reg: "Not a weight-loss medicine. Restricted/prescription where it exists.",
    au: "Not a lawful slimming tablet. Not sold.",
    kind: "research",
    terms: ["clen"],
  }),
  item({
    slug: "salbutamol",
    name: "Salbutamol",
    aliases: ["Albuterol"],
    forms: ["tablet"],
    category: "thyroid-stimulant",
    chemicalClass: "β2-agonist bronchodilator",
    presentations: ["Oral tablets on catalogues (licensed products are usually inhalers)"],
    what: "A prescription asthma medicine. High-dose oral ‘fat burner’ tablets are not Ventolin.",
    risks: "Tachycardia, hypokalaemia, tremor.",
    reg: "Approved as specific inhaled/oral brands — not research bottles.",
    au: auMedicine,
    kind: "medicine",
    terms: ["albuterol", "ventolin"],
  }),
  item({
    slug: "liothyronine",
    name: "Liothyronine (T3)",
    aliases: ["T3"],
    forms: ["tablet"],
    category: "thyroid-stimulant",
    chemicalClass: "Thyroid hormone",
    presentations: ["Oral tablets"],
    what: "Prescription T3. Catalogue cutting doses are not endocrinology.",
    risks: "Arrhythmia, bone loss, thyrotoxicosis.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["t3", "cytomel"],
  }),
  item({
    slug: "levothyroxine",
    name: "Levothyroxine (T4)",
    aliases: ["T4"],
    forms: ["tablet"],
    category: "thyroid-stimulant",
    chemicalClass: "Thyroid hormone",
    presentations: ["Oral tablets"],
    what: "Standard T4 replacement as licensed brands. Research T4 is not that product.",
    risks: "Iatrogenic thyrotoxicosis if misused.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["synthroid", "t4"],
  }),
  item({
    slug: "tesofensine",
    name: "Tesofensine",
    forms: ["tablet"],
    category: "thyroid-stimulant",
    chemicalClass: "Triple monoamine reuptake inhibitor (investigational)",
    presentations: ["Oral tablets"],
    what: "An investigational appetite agent, not a peptide incretin.",
    risks: "Cardiovascular and psychiatric class concerns; not approved.",
    reg: "Not approved as a weight-loss tablet here.",
    au: auResearch,
    kind: "research",
    terms: ["teso"],
  }),
  item({
    slug: "sildenafil",
    name: "Sildenafil",
    aliases: ["Viagra"],
    forms: ["tablet"],
    category: "sexual-health",
    chemicalClass: "PDE5 inhibitor",
    presentations: ["Oral tablets"],
    what: "Prescription ED medicine. Unlabelled ‘cock bomb’ mixes are not Viagra.",
    risks: "Hypotension with nitrates, visual change, priapism.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["viagra"],
  }),
  item({
    slug: "tadalafil",
    name: "Tadalafil",
    aliases: ["Cialis"],
    forms: ["tablet"],
    category: "sexual-health",
    chemicalClass: "PDE5 inhibitor",
    presentations: ["Oral tablets"],
    what: "Prescription PDE5 inhibitor. Catalogue spelling variants are still not licensed stock.",
    risks: "Same class as sildenafil; long half-life.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["cialis", "tadanafil"],
  }),
  item({
    slug: "dapoxetine",
    name: "Dapoxetine",
    aliases: ["Priligy"],
    forms: ["tablet"],
    category: "sexual-health",
    chemicalClass: "Short-acting SSRI (PE medicine in some markets)",
    presentations: ["Oral tablets"],
    what: "A short-acting SSRI licensed for premature ejaculation in some countries.",
    risks: "Syncope, SSRI class effects; not a gym tablet.",
    reg: "Prescription where licensed.",
    au: auMedicine,
    kind: "medicine",
    terms: ["priligy"],
  }),
  item({
    slug: "flibanserin",
    name: "Flibanserin",
    aliases: ["Addyi"],
    forms: ["tablet"],
    category: "sexual-health",
    chemicalClass: "5-HT modulator (HSDD medicine in some markets)",
    presentations: ["Oral tablets"],
    what: "A prescription medicine for acquired hypoactive sexual desire in specific labelled populations. Alcohol interaction is boxed in some labels.",
    risks: "Hypotension, syncope, CNS depression.",
    reg: "Approved in some jurisdictions as a specific brand.",
    au: auMedicine,
    kind: "medicine",
    terms: ["addyi"],
  }),
  item({
    slug: "finasteride",
    name: "Finasteride",
    aliases: ["Propecia", "Proscar"],
    forms: ["tablet"],
    category: "other-medicine",
    chemicalClass: "5α-reductase inhibitor",
    presentations: ["Oral tablets (1 mg and 5 mg strengths appear on lists)"],
    what: "Prescription medicine for BPH and male-pattern hair loss as licensed brands.",
    risks: "Sexual dysfunction, mood change; teratogenicity if handled in pregnancy.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["propecia", "proscar"],
  }),
  item({
    slug: "dutasteride",
    name: "Dutasteride",
    aliases: ["Avodart"],
    forms: ["tablet"],
    category: "other-medicine",
    chemicalClass: "Dual 5α-reductase inhibitor",
    presentations: ["Oral tablets"],
    what: "Prescription BPH medicine. Not a hair-loss supplement bottle.",
    risks: "Similar class to finasteride; longer persistence.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["avodart"],
  }),
  item({
    slug: "minoxidil",
    name: "Minoxidil",
    aliases: ["Loniten (oral)"],
    forms: ["tablet"],
    category: "other-medicine",
    chemicalClass: "Vasodilator / hair-growth agent",
    presentations: ["Oral tablets on catalogues (licensed hair products are often topical)"],
    what: "Oral minoxidil is a blood-pressure drug with hair-growth use under supervision. Not a peptide.",
    risks: "Fluid retention, tachycardia, unwanted hair.",
    reg: "Prescription / specific presentations.",
    au: auMedicine,
    kind: "medicine",
    terms: ["loniten"],
  }),
  item({
    slug: "prednisone",
    name: "Prednisone",
    forms: ["tablet"],
    category: "other-medicine",
    chemicalClass: "Systemic corticosteroid",
    presentations: ["Oral tablets"],
    what: "A glucocorticoid anti-inflammatory. Not an anabolic steroid, despite sitting on ‘steroid’ invoices.",
    risks: "Infection, hyperglycaemia, adrenal suppression, osteoporosis.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["pred"],
  }),
  item({
    slug: "isotretinoin",
    name: "Isotretinoin",
    aliases: ["Roaccutane"],
    forms: ["tablet"],
    category: "other-medicine",
    chemicalClass: "Systemic retinoid",
    presentations: ["Oral tablets"],
    what: "A tightly controlled acne medicine. Pregnancy prevention programmes exist for a reason.",
    risks: "Teratogenicity, mood, lipids, dryness — specialist only.",
    reg: "Approved prescription medicine with extra controls.",
    au: auMedicine,
    kind: "medicine",
    terms: ["roaccutane", "accutane"],
  }),
  item({
    slug: "ivermectin",
    name: "Ivermectin",
    forms: ["tablet"],
    category: "other-medicine",
    chemicalClass: "Anthelmintic",
    presentations: ["Oral tablets"],
    what: "A licensed antiparasitic in specific indications. Not a general antiviral or gym tablet.",
    risks: "Neurotoxicity in overdose; follow labelled use only.",
    reg: "Approved prescription/listed presentations depending on market.",
    au: auMedicine,
    kind: "medicine",
    terms: ["stromectol"],
  }),
  item({
    slug: "telmisartan",
    name: "Telmisartan",
    forms: ["tablet"],
    category: "other-medicine",
    chemicalClass: "Angiotensin-II receptor blocker",
    presentations: ["Oral tablets"],
    what: "A prescription blood-pressure medicine sometimes co-listed on performance invoices. Not a SARM.",
    risks: "Hypotension, renal effects — product information applies.",
    reg: "Approved prescription medicine.",
    au: auMedicine,
    kind: "medicine",
    terms: ["micardis"],
  }),
  item({
    slug: "methylene-blue",
    name: "Methylene blue",
    forms: ["tablet"],
    category: "other-medicine",
    chemicalClass: "Phenothiazinium dye / medicine",
    presentations: ["Oral tablets on catalogues"],
    what: "A licensed diagnostic/antidote dye in specific uses. Biohacking tablets are not those protocols.",
    risks: "Serotonin syndrome with SSRIs, G6PD haemolysis, blue discoloration.",
    reg: "Medicine in specific presentations; research tablets are not sold here.",
    au: auMedicine,
    kind: "medicine",
    terms: ["methylthioninium"],
  }),
  item({
    slug: "orforglipron",
    name: "Orforglipron",
    forms: ["tablet"],
    category: "other-medicine",
    chemicalClass: "Investigational oral non-peptide GLP-1 receptor agonist",
    presentations: ["Oral tablets"],
    what: "A pipeline oral incretin mimetic. Not semaglutide, and not a licensed weight-loss tablet from a research bottle.",
    risks: "GI class effects plus unknown quality.",
    reg: "Investigational. Not approved as a catalogue tablet.",
    au: auResearch,
    kind: "research",
    terms: ["orf", "oral glp-1"],
  }),
  item({
    slug: "bam15",
    name: "BAM15",
    forms: ["tablet"],
    category: "sarm-secretagogue",
    chemicalClass: "Mitochondrial uncoupler (research)",
    presentations: ["Capsules", "Sometimes mixed with SLU-PP-332 on lists"],
    what: "An experimental uncoupler. Same mechanistic family as dangerous agents such as DNP.",
    risks: "Hyperthermia and metabolic catastrophe are class concerns for uncouplers.",
    reg: "Not approved.",
    au: auResearch,
    kind: "research",
    terms: ["uncoupler"],
  }),
  item({
    slug: "dinitrophenol",
    name: "2,4-Dinitrophenol (DNP)",
    aliases: ["DNP"],
    forms: ["tablet"],
    category: "industrial-poison",
    chemicalClass: "Industrial mitochondrial uncoupler",
    presentations: ["Capsules on some ‘tablet’ lists"],
    what: "An industrial chemical that uncouples oxidative phosphorylation. It has killed people who used it for fat loss. This is not a supplement and not a peptide.",
    risks: "Uncontrolled hyperthermia, multi-organ failure, death. There is no safe bodybuilding dose.",
    reg: "Not a medicine. Industrial poison. Possession and supply for human consumption is a public-health emergency.",
    au: "Not a therapeutic good for weight loss. Longevity Protocol will not sell, source, or advise use.",
    kind: "poison",
    terms: ["dnp", "2,4-dnp"],
  }),
];

export const oilTabletPointers: {
  name: string;
  note: string;
  href: string;
  forms: OilTabletForm[];
}[] = [
  { name: "NAD+", note: "Appears on some oil lists. Encyclopaedia entry is not an injectable wellness vial for sale.", href: "/peptides/nad-plus", forms: ["oil"] },
  { name: "Lipo-C / MIC blends", note: "Lipotropic oils are documented with the peptide-adjacent catalogue, not as AAS.", href: "/peptides/lipo-c", forms: ["oil"] },
  { name: "L-carnitine", note: "Amino-acid derivative, not a steroid oil.", href: "/peptides/l-carnitine", forms: ["oil"] },
  { name: "Lemon Bottle", note: "Unlicensed fat-dissolve solution, not AAS.", href: "/peptides/lemon-bottle", forms: ["oil"] },
  { name: "GHK-Cu blends", note: "Cosmetic/research copper peptide — encyclopaedia only.", href: "/peptides/ghk-cu", forms: ["oil"] },
  { name: "Glutathione", note: "Tripeptide antioxidant, not a steroid.", href: "/peptides/glutathione", forms: ["oil"] },
  { name: "Ibutamoren (MK-677)", note: "Non-peptide GH secretagogue, already in the peptide library because it is sold on peptide invoices.", href: "/peptides/ibutamoren", forms: ["tablet"] },
  { name: "AICAR", note: "AMPK research agent — peptide-adjacent encyclopaedia entry.", href: "/peptides/aicar", forms: ["tablet"] },
  { name: "SLU-PP-332", note: "Exercise-mimetic research agent.", href: "/peptides/slu-pp-332", forms: ["tablet"] },
  { name: "Semaglutide / tirzepatide tablets", note: "Incretin medicines belong in the peptide encyclopaedia. Grey-market orals are not licensed Wegovy or Mounjaro.", href: "/peptides/semaglutide", forms: ["tablet"] },
  { name: "BPC-157 / TB-500 tablets", note: "Research peptides, not AAS. Encyclopaedia only.", href: "/peptides/bpc-157", forms: ["tablet"] },
  { name: "KPV tablets", note: "Research tripeptide.", href: "/peptides/kpv", forms: ["tablet"] },
  { name: "Dihexa tablets", note: "Research nootropic peptide.", href: "/peptides/dihexa", forms: ["tablet"] },
  { name: "5-Amino-1MQ", note: "Small-molecule research agent in the peptide-adjacent library.", href: "/peptides/5-amino-1mq", forms: ["tablet"] },
];

export function getOilTablet(slug: string) {
  return oilTabletEntries.find((e) => e.slug === slug);
}

export function searchOilTablets(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return oilTabletEntries.filter((e) => {
    const hay = [
      e.name,
      e.slug,
      ...e.alternativeNames,
      e.chemicalClass,
      e.category,
      OIL_TABLET_CATEGORY_LABELS[e.category],
      ...e.forms.map((f) => OIL_TABLET_FORM_LABELS[f]),
      ...e.cataloguePresentations,
      ...e.searchTerms,
    ]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}

export function oilTabletsByForm(form: OilTabletForm) {
  return [...oilTabletEntries.filter((e) => e.forms.includes(form))].sort((a, b) =>
    a.name.localeCompare(b.name),
  );
}

export function oilTabletsByCategory(category: OilTabletCategory) {
  return [...oilTabletEntries.filter((e) => e.category === category)].sort((a, b) =>
    a.name.localeCompare(b.name),
  );
}

export function oilTabletAzGroups() {
  const sorted = [...oilTabletEntries].sort((a, b) => a.name.localeCompare(b.name));
  const map = new Map<string, OilTabletEntry[]>();
  for (const e of sorted) {
    const letter = /[A-Z]/i.test(e.name[0]) ? e.name[0].toUpperCase() : "#";
    map.set(letter, [...(map.get(letter) ?? []), e]);
  }
  return [...map.entries()];
}
