import type { Peptide, PeptideArea, RegulatoryBadge } from "./types";

type Kind = "cosmetic" | "approved" | "investigational" | "research";

const kindBadges: Record<Kind, RegulatoryBadge[]> = {
  cosmetic: ["COSMETIC"],
  approved: ["APPROVED_MEDICINE"],
  investigational: ["INVESTIGATIONAL", "NOT_APPROVED_FOR_HUMAN_USE"],
  research: ["RESEARCH_ONLY", "NOT_APPROVED_FOR_HUMAN_USE"],
};

function entry(opts: {
  slug: string;
  name: string;
  aliases?: string[];
  kind: Kind;
  peptideClass: string;
  structure: string;
  what: string;
  how: string;
  body: string;
  studied: string[];
  benefits: string[];
  notFor: string[];
  human: string;
  pre: string;
  sides: string;
  contra: string;
  reg: string;
  au: string;
  areas: PeptideArea[];
  terms?: string[];
}): Peptide {
  return {
    slug: opts.slug,
    name: opts.name,
    alternativeNames: opts.aliases ?? [],
    peptideClass: opts.peptideClass,
    structure: opts.structure,
    whatItIs: opts.what,
    howItWorks: opts.how,
    whatItDoesInBody: opts.body,
    studiedFor: opts.studied,
    potentialBenefits: opts.benefits,
    mayNotBeUsefulFor: opts.notFor,
    humanEvidence: opts.human,
    preclinicalEvidence: opts.pre,
    sideEffects: opts.sides,
    contraindications: opts.contra,
    regulatoryStatus: opts.reg,
    australianRegulatoryStatus: opts.au,
    badges: kindBadges[opts.kind],
    areas: opts.areas,
    availableToPurchase: false,
    searchTerms: opts.terms ?? [],
    references: [
      {
        title: "Encyclopaedia note",
        citation:
          "Name inventory from public research and typical wholesale catalogues. Not a certificate of analysis, not a price list, and not an offer to sell unapproved medicines or scheduled substances.",
      },
    ],
  };
}

const noAu =
  "Cellular Sequence does not sell this as a vial, tablet, oil, or injectable. Educational encyclopaedia listing only.";

const researchStd = {
  human: "No registration-quality human programme as a consumer peptide product.",
  pre: "Scattered preclinical or analogue literature; catalogue vials are not the same as published reagents.",
  sides: "Unknown impurities, dose error, and infection risk dominate grey-market injectables.",
  contra: "Not for human use. Not for compounding outside a licensed pharmacy and lawful prescription.",
  reg: "Not an approved finished medicine in typical grey-market vial form.",
  au: noAu,
};

const approvedStd = {
  sides: "See the Australian Product Information for the licensed brand. Grey-market vials are not equivalent.",
  contra: "Follow labelled contraindications. Unlicensed research vials are not a substitute.",
  au: noAu,
};

function bio(name: string, seq: string, organ: string, slug: string, terms: string[]): Peptide {
  return entry({
    slug,
    name,
    aliases: ["Khavinson-type bioregulator (catalogue name)"],
    kind: "research",
    peptideClass: "Short synthetic ‘cytogen / bioregulator’ peptide (research literature)",
    structure: seq,
    what: `A very short peptide sold under the trade-style name ${name}, often marketed as an organ-specific ‘cytogen’. Not an approved ${organ} medicine. Not sold.`,
    how: "Proposed gene-expression or tissue-specific peptide signalling is not established as a registered therapy.",
    body: "Unproven outside experimental literature.",
    studied: [`Experimental ${organ} bioregulator literature`],
    benefits: ["None approved"],
    notFor: [`Self-treating ${organ} disease`],
    areas: ["healthy-ageing"],
    terms,
    ...researchStd,
  });
}

/** Extra encyclopaedia names from 2026 wholesale / COA inventories. Never shop SKUs. */
export const vendorCataloguePeptides: Peptide[] = [
  entry({
    slug: "dulaglutide",
    name: "Dulaglutide",
    aliases: ["Trulicity"],
    kind: "approved",
    peptideClass: "GLP-1 receptor agonist (once-weekly immunoglobulin fusion)",
    structure: "GLP-1 analogue fused to an IgG4 Fc fragment for weekly dosing.",
    what: "A prescription incretin medicine for type 2 diabetes in approved brands. Research-chemical vials labelled dulaglutide are not that product.",
    how: "GLP-1 receptor agonism: glucose-dependent insulin, glucagon suppression, slowed gastric emptying, reduced appetite.",
    body: "Glycaemic and GI effects under medical supervision when a licensed product is used.",
    studied: ["Type 2 diabetes", "Cardiovascular outcomes in labelled populations"],
    benefits: ["Licensed glycaemic control — not a wellness peptide"],
    notFor: ["Cosmetic weight loss vials", "Athletic cutting"],
    human: "Large Phase 3 and outcome programmes exist for licensed dulaglutide, not for anonymous lyophilised vials.",
    pre: "GLP-1 biology is well mapped; translation depends on the licensed formulation.",
    reg: "Approved prescription medicine in multiple jurisdictions as specific branded products.",
    areas: ["metabolic"],
    terms: ["trulicity", "dula"],
    ...approvedStd,
  }),
  entry({
    slug: "teriparatide",
    name: "Teriparatide",
    aliases: ["Forteo", "PTH 1-34"],
    kind: "approved",
    peptideClass: "Parathyroid hormone fragment (anabolic bone medicine)",
    structure: "Recombinant PTH (1–34).",
    what: "A prescription anabolic treatment for selected osteoporosis patients. Grey-market ‘teriparatide / triparatide’ vials are not Forteo.",
    how: "Intermittent PTH-receptor signalling can increase bone formation when used as labelled.",
    body: "Bone turnover and calcium handling; specialist monitoring is required.",
    studied: ["Severe osteoporosis in labelled populations"],
    benefits: ["Licensed bone anabolism — not gym use"],
    notFor: ["Bodybuilding", "Anti-ageing injections"],
    human: "Registration trials exist for licensed teriparatide.",
    pre: "PTH fragment biology is established.",
    reg: "Approved prescription medicine as specific brands; duration limits apply.",
    areas: ["recovery", "healthy-ageing"],
    terms: ["forteo", "pth", "triparatide"],
    ...approvedStd,
  }),
  entry({
    slug: "gonadorelin",
    name: "Gonadorelin",
    aliases: ["GnRH", "LHRH"],
    kind: "approved",
    peptideClass: "Gonadotropin-releasing hormone (decapeptide)",
    structure: "Native hypothalamic GnRH sequence (catalogue ‘gonadorelin acetate’).",
    what: "Used diagnostically or in specialist endocrine protocols as licensed products. Research vials are not a fertility kit.",
    how: "Pulsatile GnRH drives LH/FSH; continuous exposure can desensitise the axis.",
    body: "Pituitary–gonadal axis perturbation.",
    studied: ["Diagnostic GnRH tests", "Selected reproductive-endocrine uses"],
    benefits: ["Specialist endocrine use only"],
    notFor: ["PCT folklore", "Unsupervised hormone cycling"],
    human: "Licensed diagnostic/therapeutic products exist; grey-market acetate is not equivalent.",
    pre: "Classic hypothalamic peptide biology.",
    reg: "Approved in specific presentations; research vials are unapproved.",
    areas: ["metabolic", "performance"],
    terms: ["gnrh", "lhrh", "gnd"],
    ...approvedStd,
  }),
  entry({
    slug: "triptorelin",
    name: "Triptorelin",
    aliases: ["GnRH superagonist"],
    kind: "approved",
    peptideClass: "Long-acting GnRH agonist",
    structure: "Modified GnRH decapeptide used as depot medicines in oncology and gynaecology.",
    what: "A prescription hormone-suppression medicine in licensed depots. Tiny research vials labelled triptorelin are not those products.",
    how: "Initial gonadotropin flare then pituitary desensitisation and sex-steroid suppression.",
    body: "Profound HPG-axis shutdown if bioactive — inappropriate outside specialist care.",
    studied: ["Hormone-sensitive cancers", "Selected gynaecological indications"],
    benefits: ["Licensed specialist indications only"],
    notFor: ["Bodybuilding PCT", "Anti-ageing"],
    human: "Extensive for licensed depots, none for anonymous 2 mg research kits.",
    pre: "GnRH agonist class is well described.",
    reg: "Approved as specific depot medicines.",
    areas: ["metabolic"],
    terms: ["triptorelln", "decapeptyl"],
    ...approvedStd,
  }),
  entry({
    slug: "aprotinin",
    name: "Aprotinin",
    aliases: ["Bovine pancreatic trypsin inhibitor"],
    kind: "approved",
    peptideClass: "Kunitz-type serine-protease inhibitor (protein, not a cosmetic peptide)",
    structure: "58-residue bovine protein historically used to reduce bleeding in surgery.",
    what: "A historical surgical antifibrinolytic with a serious safety history (hypersensitivity, thrombosis). Not a wellness peptide. Not sold.",
    how: "Inhibits plasmin and related proteases.",
    body: "Alters coagulation/fibrinolysis — high-risk class.",
    studied: ["Perioperative blood loss (historical)"],
    benefits: ["None as a consumer product"],
    notFor: ["Research-chemical surgery kits"],
    human: "Licensed use was restricted after safety signals; not a lifestyle drug.",
    pre: "Protease-inhibitor biochemistry.",
    sides: "Anaphylaxis and clotting risk are the reason this is not a DIY peptide.",
    contra: "Not for unsupervised use.",
    reg: "Historically approved then heavily restricted in several markets.",
    au: noAu,
    areas: ["recovery"],
    terms: ["bpti", "trasylol"],
  }),
  entry({
    slug: "acth-1-39",
    name: "ACTH (1–39)",
    aliases: ["Corticotropin", "Adrenocorticotropic hormone"],
    kind: "approved",
    peptideClass: "Pituitary tropic peptide hormone",
    structure: "39-residue ACTH; diagnostic analogues (e.g. tetracosactide) are licensed separately.",
    what: "A hormone that drives adrenal cortisol. Research ‘ACTH 1-39’ vials are not Synacthen tests.",
    how: "MC2 receptor agonism on the adrenal cortex.",
    body: "Acute steroidogenesis; chronic excess is Cushing-like.",
    studied: ["Adrenal diagnostic testing", "Selected inflammatory protocols historically"],
    benefits: ["Specialist diagnostics — not anti-ageing"],
    notFor: ["Tan / energy injections", "Bodybuilding"],
    human: "Licensed corticotropin analogues exist; catalogue ACTH is not equivalent.",
    pre: "Classic pituitary–adrenal axis.",
    sides: "Hypertension, hyperglycaemia, infection risk, mood change if bioactive.",
    contra: "Systemic steroid-axis drugs require specialist oversight.",
    reg: "Approved as specific diagnostic/therapeutic presentations.",
    au: noAu,
    areas: ["metabolic", "healthy-ageing"],
    terms: ["corticotropin", "acth"],
  }),
  entry({
    slug: "insulin",
    name: "Insulin",
    aliases: ["Human insulin", "Research-catalogue insulin"],
    kind: "approved",
    peptideClass: "Peptide hormone (glucose-lowering medicine)",
    structure: "Two-chain peptide hormone; licensed products are characterised biologics.",
    what: "A life-saving prescription medicine for diabetes. Unlabelled research vials sold as ‘insulin’ are extremely dangerous.",
    how: "Insulin-receptor mediated glucose uptake and anabolism.",
    body: "Hypoglycaemia can be fatal within minutes if mis-dosed.",
    studied: ["Diabetes mellitus"],
    benefits: ["Licensed diabetes care only"],
    notFor: ["Bodybuilding ‘insulin slin’ protocols", "Anti-ageing"],
    human: "Among the most studied peptide medicines — for licensed products.",
    pre: "N/A relative to human use.",
    sides: "Severe hypoglycaemia, hypokalaemia.",
    contra: "Never use non-pharmacy insulin. Medical emergency if hypoglycaemia occurs.",
    reg: "Approved prescription biologic.",
    au: noAu,
    areas: ["metabolic"],
    terms: ["isu", "slin"],
  }),
  entry({
    slug: "erythropoietin",
    name: "Erythropoietin (EPO)",
    aliases: ["Epoetin"],
    kind: "approved",
    peptideClass: "Glycoprotein hormone (not a short research peptide)",
    structure: "Recombinant EPO analogues are licensed for anaemia; IU-labelled research vials are not those products.",
    what: "A prescription marrow stimulant. Sport-banned. Grey-market ‘EPO 3000 IU’ kits are not medical care.",
    how: "EPO-receptor signalling increases red-cell mass.",
    body: "Viscosity, thrombosis, and hypertension risk if misused.",
    studied: ["Anaemia of CKD and related licensed indications"],
    benefits: ["Licensed anaemia treatment only"],
    notFor: ["Endurance doping", "Anti-ageing"],
    human: "Licensed epoetins have outcome and safety data; research vials do not.",
    pre: "Erythropoiesis biology.",
    sides: "Thrombosis, hypertension, pure red-cell aplasia (class risk).",
    contra: "Not for unsupervised use. WADA prohibited.",
    reg: "Approved as specific recombinant medicines.",
    au: noAu,
    areas: ["performance"],
    terms: ["epo", "epoetin", "e3k"],
  }),
  entry({
    slug: "menotropins",
    name: "Menotropins (hMG)",
    aliases: ["Human menopausal gonadotropin", "HMG"],
    kind: "approved",
    peptideClass: "FSH/LH glycoprotein mixture (fertility medicine class)",
    structure: "Urinary or recombinant gonadotropin preparations — not a 5 mg lyophilised ‘peptide’.",
    what: "Specialist fertility medicines exist as licensed hMG. Catalogue ‘HMG 75 IU’ vials are not IVF clinic stock.",
    how: "FSH and LH receptor stimulation of gonads.",
    body: "Ovarian hyperstimulation or testosterone/oestradiol swings if bioactive.",
    studied: ["Assisted reproduction under specialist care"],
    benefits: ["Licensed fertility care only"],
    notFor: ["PCT", "Bodybuilding"],
    human: "Licensed products only.",
    pre: "Gonadotropin biology.",
    sides: "OHSS, thromboembolism, multiple pregnancy in people with ovaries.",
    contra: "Specialist-only class.",
    reg: "Approved as specific fertility medicines.",
    au: noAu,
    areas: ["metabolic"],
    terms: ["hmg", "menopur"],
  }),
  entry({
    slug: "botulinum-toxin",
    name: "Botulinum toxin",
    aliases: ["Botox", "OnabotulinumtoxinA"],
    kind: "approved",
    peptideClass: "Bacterial neurotoxin protein (not a cosmetic hexapeptide)",
    structure: "High-molecular-weight toxin; licensed units are not interchangeable with ‘100 IU research vials’.",
    what: "Licensed neuromodulator medicines exist for wrinkles and medical indications. Anonymous toxin vials are a public-health hazard.",
    how: "Cleaves SNARE proteins and blocks acetylcholine release at the neuromuscular junction.",
    body: "Local paralysis; distant spread can be life-threatening.",
    studied: ["Licensed aesthetic and medical indications"],
    benefits: ["Clinic-administered licensed brands only"],
    notFor: ["Mail-order toxin", "‘Botox kits’"],
    human: "Extensive for licensed brands; zero for unnamed vials.",
    pre: "Clostridial toxin mechanism is known — that is why counterfeit toxin is so dangerous.",
    sides: "Dysphagia, respiratory compromise, antibody formation.",
    contra: "Never inject non-licensed toxin.",
    reg: "Approved as specific branded biologics; unlicensed toxin is illegal to supply as a medicine.",
    au: noAu,
    areas: ["skin-hair"],
    terms: ["botox", "xt100", "botlioum"],
  }),
  entry({
    slug: "eloralintide",
    name: "Eloralintide",
    aliases: ["LY-3841136 (investigational amylin analogue — catalogue name)"],
    kind: "investigational",
    peptideClass: "Long-acting amylin receptor agonist (pipeline)",
    structure: "Investigational amylin analogue appearing on 2026 wholesale lists as ‘ELD’.",
    what: "A clinical-stage metabolic peptide, not a consumer vial. Not sold.",
    how: "Amylin-pathway satiety and gastric-emptying effects (class).",
    body: "Would be a prescription-class metabolic drug if ever approved — not a supplement.",
    studied: ["Obesity / metabolic pipeline studies"],
    benefits: ["None approved"],
    notFor: ["Grey-market incretin stacking"],
    human: "Company trials may exist; they do not legitimise research-chemical kits.",
    pre: "Amylin biology.",
    sides: "GI class effects plus unknown quality.",
    contra: "Not for human use outside trials.",
    reg: "Investigational. Not an approved finished medicine as a research vial.",
    au: noAu,
    areas: ["metabolic"],
    terms: ["eld", "amylin analogue"],
  }),
  entry({
    slug: "cagrisema",
    name: "CagriSema (cagrilintide + semaglutide)",
    aliases: ["Cagrilintide/semaglutide combination"],
    kind: "investigational",
    peptideClass: "Investigational amylin + GLP-1 combination",
    structure: "Fixed-ratio research or trial combination; catalogue ‘CS5/CS10’ blends are not licensed CagriSema.",
    what: "A clinical combination concept. Unlicensed mixed vials are not Novo Nordisk trial drug. Not sold.",
    how: "Dual satiety signalling (amylin + GLP-1) in principle.",
    body: "Potent metabolic and GI effects if both actives are present — still unapproved as a DIY blend.",
    studied: ["Obesity pipeline combinations"],
    benefits: ["None approved as a consumer product"],
    notFor: ["Home incretin mixing"],
    human: "Sponsor trials ≠ grey-market CS10 kits.",
    pre: "See cagrilintide and semaglutide.",
    sides: "Stacked GI and hypoglycaemia-adjacent risks with quality unknown.",
    contra: "Not for human use.",
    reg: "Not approved as a finished combination vial from research catalogues.",
    au: noAu,
    areas: ["metabolic"],
    terms: ["cs5", "cs10", "cagri sema"],
  }),
  entry({
    slug: "retatrutide-tirzepatide-blend",
    name: "Retatrutide + tirzepatide blends",
    kind: "research",
    peptideClass: "Unapproved dual incretin mixture",
    structure: "Catalogue mixes (e.g. 20 mg + 40 mg) have no pharmacopoeial identity.",
    what: "Two investigational/approved-class incretins in one unlicensed vial. Not sold.",
    how: "Undefined combined exposure.",
    body: "Dangerous stacking even before quality is considered.",
    studied: ["None as a registered combination"],
    benefits: ["None approved"],
    notFor: ["Faster fat-loss stacks"],
    areas: ["metabolic"],
    terms: ["ret60", "reta tirz"],
    ...researchStd,
  }),
  entry({
    slug: "retatrutide-cagrilintide-blend",
    name: "Retatrutide + cagrilintide blends",
    aliases: ["RC10 catalogue mix"],
    kind: "research",
    peptideClass: "Unapproved triple-agonist + amylin mixture",
    structure: "Grey-market pairing; not a trial product.",
    what: "Uncharacterised metabolic cocktail. Not sold.",
    how: "Unknown combined PK.",
    body: "High GI and quality risk.",
    studied: ["None"],
    benefits: ["None approved"],
    notFor: ["Incretin stacking"],
    areas: ["metabolic"],
    terms: ["rc10"],
    ...researchStd,
  }),
  entry({
    slug: "tesamorelin-ipamorelin-blend",
    name: "Tesamorelin + ipamorelin blends",
    aliases: ["TI 15 mg catalogue mix"],
    kind: "research",
    peptideClass: "Unapproved GHRH analogue + GHS mixture",
    structure: "Common vendor pairing of tesamorelin with ipamorelin.",
    what: "Tesamorelin is a licensed HIV-lipodystrophy medicine in specific brands; this blend is not that product. Not sold.",
    how: "See parent peptides.",
    body: "GH-axis stimulation if bioactive; sport-banned class.",
    studied: ["None as an approved combo vial"],
    benefits: ["None approved"],
    notFor: ["Fat-loss GH stacks"],
    areas: ["metabolic", "performance"],
    terms: ["ti15", "tesa ipa"],
    ...researchStd,
  }),
  entry({
    slug: "n-acetyl-semax-amidate",
    name: "N-acetyl Semax amidate",
    aliases: ["NA-Semax", "NAX"],
    kind: "research",
    peptideClass: "Modified ACTH(4–10) analogue (research only)",
    structure: "N-acetylated, C-amidated Semax analogue sold as a ‘more stable’ nootropic peptide.",
    what: "Unapproved cognitive research chemical. Not sold.",
    how: "Putative melanocortin / BDNF narratives — not a registered nootropic.",
    body: "Unknown.",
    studied: ["Experimental nootropic use — not evidence"],
    benefits: ["None approved"],
    notFor: ["Focus injections"],
    areas: ["cognitive"],
    terms: ["nasemax", "nax30", "na-semax"],
    ...researchStd,
  }),
  entry({
    slug: "n-acetyl-selank-amidate",
    name: "N-acetyl Selank amidate",
    aliases: ["NA-Selank"],
    kind: "research",
    peptideClass: "Modified tuftsin analogue (research only)",
    structure: "Stabilised Selank analogue on some vendor lists.",
    what: "Unapproved anxiolytic-style research peptide. Not sold.",
    how: "See Selank; amidation does not create a medicine.",
    body: "Unknown.",
    studied: ["Experimental"],
    benefits: ["None approved"],
    notFor: ["Anxiety self-injection"],
    areas: ["cognitive"],
    terms: ["naselank", "na-selank"],
    ...researchStd,
  }),
  entry({
    slug: "semax-selank-blend",
    name: "Semax + Selank blends",
    aliases: ["XS10", "XS20"],
    kind: "research",
    peptideClass: "Unapproved nootropic peptide mixture",
    structure: "Equal-mass Semax/Selank cocktails on price lists.",
    what: "Two unapproved ACTH/tuftsin analogues in one vial. Not sold.",
    how: "See parent entries.",
    body: "Uncharacterised combination.",
    studied: ["None"],
    benefits: ["None approved"],
    notFor: ["Nootropic stacks"],
    areas: ["cognitive"],
    terms: ["xs10", "xs20"],
    ...researchStd,
  }),
  entry({
    slug: "tb-500-fragment",
    name: "TB-500 fragment",
    aliases: ["TBFing", "Thymosin β4 fragment"],
    kind: "research",
    peptideClass: "Short thymosin-β4 fragment (research only)",
    structure: "Vendor ‘TB fragment’ is not pharmacopoeial TB-500/Tβ4.",
    what: "Uncharacterised fragment marketed beside TB-500. Not sold.",
    how: "Unknown; do not assume Tβ4 activity.",
    body: "Unknown.",
    studied: ["None as a medicine"],
    benefits: ["None approved"],
    notFor: ["Injury healing injections"],
    areas: ["recovery"],
    terms: ["tbf", "tb fragment"],
    ...researchStd,
  }),
  entry({
    slug: "mgf",
    name: "Mechano growth factor (MGF)",
    aliases: ["IGF-1 Ec isoform peptide"],
    kind: "research",
    peptideClass: "IGF-1 splice-variant peptide (research only)",
    structure: "C-terminal MGF sequence distinct from PEG-MGF conjugates.",
    what: "Unapproved muscle-repair research peptide. Not sold. PEG-MGF is listed separately.",
    how: "Proposed local IGF-related signalling after mechanical load — not a licensed therapy.",
    body: "Would sit on the GH/IGF axis if bioactive.",
    studied: ["Experimental muscle biology"],
    benefits: ["None approved"],
    notFor: ["Injury or hypertrophy injections"],
    areas: ["performance", "recovery"],
    terms: ["fm2", "mechano"],
    ...researchStd,
  }),
  entry({
    slug: "ghk",
    name: "GHK (without copper)",
    aliases: ["Glycyl-L-histidyl-L-lysine"],
    kind: "cosmetic",
    peptideClass: "Matrikine tripeptide (copper-free)",
    structure: "The GHK sequence used in cosmetics; GHK-Cu is the copper complex listed separately.",
    what: "A skin-care peptide fragment. Injectable ‘GHK 50 mg’ vials are not a cosmetic serum and are not sold.",
    how: "Proposed extracellular-matrix signalling; copper complex is the usual cosmetic form.",
    body: "Leave-on skin in cosmetics; systemic injection is not an approved use.",
    studied: ["Cosmetic appearance of skin"],
    benefits: ["Topical cosmetic context only"],
    notFor: ["Injectable ‘glow’ protocols"],
    human: "Cosmetic-grade evidence, not drug trials for injectables.",
    pre: "Matrikine literature.",
    sides: "Topical irritation; do not inject.",
    contra: "Not for injection.",
    reg: "Cosmetic ingredient when used topically. Injectable research GHK is unapproved.",
    au: noAu,
    areas: ["skin-hair"],
    terms: ["glycyl histidyl lysine", "copper-free ghk"],
  }),
  entry({
    slug: "hgh-fragment-176-191",
    name: "HGH fragment 176–191",
    aliases: ["AOD-related C-terminal fragment", "Frag 176-191"],
    kind: "research",
    peptideClass: "Growth-hormone C-terminal fragment (research only)",
    structure: "Residues 176–191 of somatropin; related to AOD-9604 development.",
    what: "Unapproved fat-loss research peptide. Not hGH. Not sold. See also AOD-9604.",
    how: "Proposed lipolytic fragment activity without full GH receptor agonism — not established as a medicine.",
    body: "Unknown in unregulated vials.",
    studied: ["Experimental lipolysis (historical AOD programme)"],
    benefits: ["None approved"],
    notFor: ["Cutting injections"],
    areas: ["metabolic", "performance"],
    terms: ["fr5", "frag 176", "hgh frag"],
    ...researchStd,
  }),
  entry({
    slug: "glutathione",
    name: "Glutathione",
    aliases: ["GSH", "γ-glutamyl-cysteinyl-glycine"],
    kind: "approved",
    peptideClass: "Endogenous tripeptide antioxidant",
    structure: "Glu-Cys-Gly. Licensed uses exist in specific presentations; high-dose IV ‘whitening’ vials are another matter.",
    what: "The body’s main thiol antioxidant. High-dose injectable glutathione sold for skin lightening is not an approved cosmetic here and is not sold.",
    how: "Redox buffering and conjugation reactions.",
    body: "Systemic redox change; IV use has been associated with serious adverse events when unregulated.",
    studied: ["Selected licensed supportive uses", "Unapproved cosmetic IV markets"],
    benefits: ["Physiological antioxidant — not a tan/whitening injection"],
    notFor: ["Skin-lightening drips", "Hangover IV bars"],
    human: "Endogenous biochemistry is known; cosmetic IV evidence is poor and safety is not benign.",
    pre: "Textbook redox biology.",
    sides: "Anaphylactoid reactions and liver injury reports with unregulated IV use.",
    contra: "Do not use unlicensed IV glutathione.",
    reg: "Ingredient/medicine status depends on presentation; research ‘GTT’ vials are not licensed IV therapy.",
    au: noAu,
    areas: ["skin-hair", "healthy-ageing"],
    terms: ["gsh", "gtt600", "gtt1500"],
  }),
  entry({
    slug: "dihexa",
    name: "Dihexa",
    aliases: ["Hexanoic acid–angiotensin IV analogue"],
    kind: "research",
    peptideClass: "Hepatocyte growth factor / angiotensin-IV related small peptide (research only)",
    structure: "N-hexanoic-Tyr-Ile-(6)-aminohexanoic amide class compound.",
    what: "Experimental cognitive research chemical. Not sold.",
    how: "Proposed HGF/c-Met potentiation in models — not a licensed nootropic.",
    body: "Unknown; growth-factor pathways are not casual supplements.",
    studied: ["Preclinical memory models"],
    benefits: ["None approved"],
    notFor: ["DIY Alzheimer’s treatment"],
    areas: ["cognitive"],
    terms: ["dih5", "hexanoic"],
    ...researchStd,
  }),
  entry({
    slug: "humanin",
    name: "Humanin",
    aliases: ["MT-RNR2-derived peptide"],
    kind: "research",
    peptideClass: "Mitochondrial-derived peptide",
    structure: "24-residue mitochondrial peptide (HN).",
    what: "A mitochondrial peptide studied in ageing models. Not a consumer injectable. Not sold.",
    how: "Proposed cytoprotective signalling (FPRL1 and related).",
    body: "Experimental.",
    studied: ["Experimental neurodegeneration and metabolic models"],
    benefits: ["None approved"],
    notFor: ["Longevity injections"],
    areas: ["healthy-ageing", "cognitive"],
    terms: ["hu10", "mt-rnr2"],
    ...researchStd,
  }),
  entry({
    slug: "p21",
    name: "P21 (P021)",
    aliases: ["CNTF-derived peptide P021"],
    kind: "research",
    peptideClass: "Ciliary neurotrophic factor–derived peptide (research only)",
    structure: "Short CNTF analogue used in experimental neurodegeneration papers.",
    what: "Unapproved cognitive/neuro research peptide. Not sold.",
    how: "Proposed neurotrophic signalling — not a medicine.",
    body: "Unknown in vials.",
    studied: ["Experimental Alzheimer-model literature"],
    benefits: ["None approved"],
    notFor: ["Memory injections"],
    areas: ["cognitive"],
    terms: ["p021", "p210"],
    ...researchStd,
  }),
  entry({
    slug: "ptd-dbm",
    name: "PTD-DBM",
    aliases: ["Protein transduction domain–Wnt pathway peptide", "DBM"],
    kind: "research",
    peptideClass: "Cell-penetrating Wnt-modulating peptide (research only)",
    structure: "PTD fused to a CXXC-type zinc-finger / Dishevelled-binding motif in hair-loss research papers.",
    what: "Experimental hair-follicle Wnt research tool. Not an approved hair-loss drug. Not sold.",
    how: "Proposed interference with CXXC5–Dishevelled interaction.",
    body: "Unknown in commercial vials.",
    studied: ["Experimental androgenetic-alopecia models"],
    benefits: ["None approved"],
    notFor: ["Scalp injections from research vendors"],
    areas: ["skin-hair"],
    terms: ["ptd1", "dbm", "cxxc5"],
    ...researchStd,
  }),
  entry({
    slug: "b7-33",
    name: "B7-33",
    aliases: ["Relaxin-2 analogue fragment"],
    kind: "research",
    peptideClass: "Single-chain relaxin mimetic (research only)",
    structure: "Simplified H2-relaxin analogue targeting RXFP1 in fibrosis models.",
    what: "Experimental antifibrotic research peptide. Not sold.",
    how: "Relaxin-receptor signalling in preclinical papers.",
    body: "Unknown clinically.",
    studied: ["Experimental fibrosis / cardiovascular models"],
    benefits: ["None approved"],
    notFor: ["Heart-health injections"],
    areas: ["recovery", "healthy-ageing"],
    terms: ["b733", "relaxin analogue"],
    ...researchStd,
  }),
  entry({
    slug: "gdf-8",
    name: "GDF-8 (myostatin)",
    aliases: ["Myostatin"],
    kind: "research",
    peptideClass: "TGF-β superfamily ligand (protein, not a cosmetic peptide)",
    structure: "Full myostatin protein on some lists — a muscle-inhibitory cytokine, not a ‘cutting peptide’.",
    what: "Selling myostatin as a research vial is not a hypertrophy protocol. Myostatin inhibition is a high-risk drug class. Not sold.",
    how: "GDF-8 limits muscle growth; adding it would not build muscle.",
    body: "Would suppress muscle if bioactive — opposite of gym marketing.",
    studied: ["Myostatin biology; inhibitor drugs are a different product"],
    benefits: ["None as a consumer product"],
    notFor: ["Muscle enhancement"],
    areas: ["performance"],
    terms: ["myostatin", "gdf8"],
    ...researchStd,
  }),
  entry({
    slug: "foxo4",
    name: "FOXO4 (non-DRI)",
    aliases: ["FOXO4 peptide"],
    kind: "research",
    peptideClass: "Forkhead-box related research peptide (distinct from FOXO4-DRI)",
    structure: "Catalogue ‘FOXO4’ is often a shorter or unspecified sequence versus the D-retro-inverso senolytic peptide.",
    what: "Unapproved senolytic-adjacent research chemical. See FOXO4-DRI. Not sold.",
    how: "Putative p53/FOXO4 interference is not a consumer protocol.",
    body: "Senolytic research is high-risk.",
    studied: ["Experimental senescence models"],
    benefits: ["None approved"],
    notFor: ["Anti-ageing injections"],
    areas: ["healthy-ageing"],
    terms: ["f4-2", "foxo"],
    ...researchStd,
  }),
  entry({
    slug: "orexin-a",
    name: "Orexin A",
    aliases: ["Hypocretin-1"],
    kind: "research",
    peptideClass: "Hypothalamic wake-promoting peptide",
    structure: "33-residue orexin-A with disulphides.",
    what: "A brain peptide involved in wakefulness and narcolepsy biology. Not a sleep/stack injectable. Not sold.",
    how: "OX1/OX2 receptor agonism.",
    body: "Would perturb arousal, appetite and autonomic tone if it reached the CNS — inappropriate DIY.",
    studied: ["Narcolepsy / arousal neuroscience"],
    benefits: ["None as a consumer product"],
    notFor: ["Sleep hacks", "Fat-loss"],
    areas: ["cognitive", "metabolic"],
    terms: ["hypocretin", "oxa10"],
    ...researchStd,
  }),
  entry({
    slug: "orexin-b",
    name: "Orexin B",
    aliases: ["Hypocretin-2"],
    kind: "research",
    peptideClass: "Hypothalamic wake-promoting peptide",
    structure: "28-residue orexin-B.",
    what: "Sister peptide to orexin A. Not sold.",
    how: "Preferential OX2 signalling in models.",
    body: "Same class risks as orexin A.",
    studied: ["Arousal neuroscience"],
    benefits: ["None approved"],
    notFor: ["Nootropic vials"],
    areas: ["cognitive"],
    terms: ["oxb5", "hypocretin-2"],
    ...researchStd,
  }),
  entry({
    slug: "ovotransferrin",
    name: "Ovotransferrin",
    kind: "research",
    peptideClass: "Egg-white iron-binding glycoprotein (not a short peptide drug)",
    structure: "Large transferrin-family protein.",
    what: "A food protein sometimes listed beside peptides. Not an injectable medicine. Not sold.",
    how: "Iron binding and antimicrobial motifs in food science.",
    body: "Not characterised as a peptide vial therapy.",
    studied: ["Food-science / in-vitro antimicrobial work"],
    benefits: ["None as an injectable"],
    notFor: ["Immune injections"],
    areas: ["healthy-ageing"],
    terms: ["ovt"],
    ...researchStd,
  }),
  entry({
    slug: "pulmonary-cytogen",
    name: "Pulmonary cytogen",
    aliases: ["Bronchogen-adjacent catalogue name"],
    kind: "research",
    peptideClass: "Unspecified lung ‘cytogen’ (research marketing)",
    structure: "Vendor name without a single pharmacopoeial sequence.",
    what: "Marketing label for a supposed lung bioregulator. Not an approved respiratory drug. Not sold.",
    how: "Unproven.",
    body: "Unproven.",
    studied: ["None of registration quality"],
    benefits: ["None approved"],
    notFor: ["Asthma or COPD self-treatment"],
    areas: ["recovery"],
    terms: ["puc5", "cytogen"],
    ...researchStd,
  }),
  entry({
    slug: "leu-enkephalin",
    name: "[Leu⁵]enkephalin",
    aliases: ["Leu5", "Leucine-enkephalin"],
    kind: "research",
    peptideClass: "Endogenous opioid pentapeptide",
    structure: "Tyr-Gly-Gly-Phe-Leu.",
    what: "An endogenous opioid. Research vials are not pain medicines. Not sold.",
    how: "δ/μ opioid receptor agonism.",
    body: "Opioid-class CNS and GI effects if bioactive.",
    studied: ["Opioid neuroscience"],
    benefits: ["None as a consumer peptide"],
    notFor: ["Pain self-injection", "Mood stacks"],
    areas: ["cognitive"],
    terms: ["leu5", "enkephalin"],
    ...researchStd,
  }),
  entry({
    slug: "melatonin",
    name: "Melatonin",
    aliases: ["N-acetyl-5-methoxytryptamine"],
    kind: "approved",
    peptideClass: "Indoleamine hormone (not a peptide)",
    structure: "Small tryptophan metabolite; listed on peptide price sheets anyway.",
    what: "A circadian hormone available as licensed or listed oral products in some markets. Injectable ‘melatonin 10 mg vials’ are not those products and are not sold here.",
    how: "MT1/MT2 receptor signalling and circadian phase-shifting.",
    body: "Sleepiness, prolactin and temperature effects.",
    studied: ["Jet lag / insomnia in specific licensed presentations"],
    benefits: ["Oral licensed use where indicated — not injections"],
    notFor: ["Peptide stacks", "Anti-ageing vials"],
    human: "Oral melatonin has a mixed evidence base; injectable research stock is unjustified.",
    pre: "Pineal hormone biology.",
    sides: "Next-day sedation, vivid dreams; injection adds infection risk.",
    contra: "Follow labelled oral products; do not inject research melatonin.",
    reg: "Oral products may be listed/registered; injectable research melatonin is unapproved.",
    au: noAu,
    areas: ["cognitive", "healthy-ageing"],
    terms: ["mt10", "pineal"],
  }),
  entry({
    slug: "ibutamoren",
    name: "Ibutamoren (MK-677)",
    aliases: ["MK-677", "MK677"],
    kind: "research",
    peptideClass: "Non-peptide ghrelin-mimetic (small molecule)",
    structure: "Spiropiperidine GH secretagogue — not a peptide, despite sitting on peptide invoices.",
    what: "An unapproved oral GH secretagogue. Sport-banned. Not sold.",
    how: "GHSR agonism increases GH/IGF-1 and appetite.",
    body: "Insulin resistance, oedema, increased appetite.",
    studied: ["Experimental GH-deficiency and sarcopenia programmes — not approved"],
    benefits: ["None approved"],
    notFor: ["Sleep + gains stacks"],
    areas: ["performance", "healthy-ageing"],
    terms: ["mk75", "gh secretagogue"],
    ...researchStd,
  }),
  entry({
    slug: "cerebrolysin",
    name: "Cerebrolysin",
    aliases: ["Porcine brain hydrolysate"],
    kind: "research",
    peptideClass: "Low-molecular-weight neuropeptide mixture (porcine brain)",
    structure: "Complex hydrolysate, not a single sequence. Licensed in some countries; not TGA-registered as a general nootropic here.",
    what: "A brain-derived peptide mixture used as a medicine in some regions. Research-catalogue cerebrolysin is not a clinic infusion. Not sold.",
    how: "Proposed neurotrophic peptide mix — composition varies by manufacturer.",
    body: "Unknown quality in anonymous vials; porcine origin adds immunologic risk.",
    studied: ["Stroke / dementia programmes in selected countries"],
    benefits: ["None as a mail-order nootropic"],
    notFor: ["DIY brain infusions"],
    human: "Regional trials exist for specific brands; they do not validate research vials.",
    pre: "Nerve-growth-factor-adjacent marketing.",
    sides: "Injection reactions; theoretical prion/immunology concerns with neural tissue products.",
    contra: "Not for unsupervised use.",
    reg: "Approved in some jurisdictions as a specific brand; not a research-chemical SKU here.",
    au: noAu,
    areas: ["cognitive"],
    terms: ["cbl60"],
  }),
  bio("Bronchogen", "Short lung ‘cytogen’ sequence on supplier lists (often AEDL-type).", "respiratory", "bronchogen", ["br20"]),
  bio("Cardiogen", "Short cardiac bioregulator sequence in catalogue literature.", "cardiac", "cardiogen", ["ca20"]),
  bio("Cortagen", "Short cortex/CNS bioregulator name.", "neurological", "cortagen", ["cor20"]),
  bio("Livagen", "Short liver bioregulator name.", "hepatic", "livagen", ["li20"]),
  bio("Pancragen", "Short pancreatic bioregulator name.", "pancreatic / metabolic", "pancragen", ["pa20"]),
  bio("Prostamax", "Short prostate bioregulator name.", "prostate", "prostamax", ["max20"]),
  bio("Chonluten", "Short mucous-membrane / lung bioregulator name.", "mucosal", "chonluten", ["ch20"]),
  bio("Crystagen", "Short immune/thymus-adjacent bioregulator name.", "immune", "crystagen", ["cry20"]),
  bio("Ovagen", "Short ovarian/liver-adjacent bioregulator name on extended lists.", "hepatic / reproductive", "ovagen", ["ovagen"]),
  bio("Vesugen", "Short vascular bioregulator name.", "vascular", "vesugen", ["vesugen"]),
  bio("Vilon", "Lys-Glu dipeptide bioregulator.", "immune / ageing", "vilon", ["vi20"]),
  bio("Testagen", "Short testicular bioregulator name.", "gonadal", "testagen", ["tg20"]),
  entry({
    slug: "n-acetyl-epitalon-amidate",
    name: "N-acetyl Epitalon amidate",
    aliases: ["NA-Epitalon"],
    kind: "research",
    peptideClass: "Stabilised Ala-Glu-Asp-Gly analogue (research only)",
    structure: "N-acetyl, C-amide epitalon analogue on some invoices.",
    what: "Modified epithalon analogue. Still unapproved. Not sold.",
    how: "See epithalon; capping chemistry is not approval.",
    body: "Unknown.",
    studied: ["Experimental"],
    benefits: ["None approved"],
    notFor: ["Telomere injections"],
    areas: ["healthy-ageing"],
    terms: ["na-epitalon", "epitalon amidate"],
    ...researchStd,
  }),
  entry({
    slug: "clb-514",
    name: "CLB-514",
    kind: "research",
    peptideClass: "Catalogue metabolic / adipose research code",
    structure: "Vendor code without a public pharmacopoeial monograph.",
    what: "Appears on high-concentration peptide sheets. Not an approved medicine. Not sold.",
    how: "Undisclosed.",
    body: "Unknown.",
    studied: ["None identified as a registered drug"],
    benefits: ["None approved"],
    notFor: ["Fat-dissolving injections"],
    areas: ["metabolic"],
    terms: ["clb514"],
    ...researchStd,
  }),
  entry({
    slug: "pdrn",
    name: "PDRN (polydeoxyribonucleotide)",
    aliases: ["Salmon DNA fragment mixtures"],
    kind: "cosmetic",
    peptideClass: "DNA fragment mixture (not a peptide)",
    structure: "Depolymerised DNA used in some skin procedures and cosmetics.",
    what: "A polynucleotide skin ingredient/procedure class, often listed next to peptides. Not sold as an injectable kit here.",
    how: "Proposed A2A receptor / wound-healing narratives in aesthetic literature.",
    body: "Device/clinic context in some countries; mail-order vials are not that setting.",
    studied: ["Aesthetic dermatology literature of mixed quality"],
    benefits: ["Clinic or cosmetic context only — not a peptide hormone"],
    notFor: ["DIY skin injections"],
    human: "Mostly aesthetic series, not TGA-standard drug approval for anonymous vials.",
    pre: "Nucleic-acid fragment biology.",
    sides: "Injection-site reactions.",
    contra: "Not a home injectable.",
    reg: "Device/cosmetic/medicine status varies; research vials are not sold.",
    au: noAu,
    areas: ["skin-hair"],
    terms: ["polydeoxyribonucleotide", "salmon dna"],
  }),
  entry({
    slug: "hyaluronic-acid",
    name: "Hyaluronic acid",
    aliases: ["Sodium hyaluronate", "HA"],
    kind: "cosmetic",
    peptideClass: "Glycosaminoglycan (not a peptide)",
    structure: "Repeating glucuronic acid / N-acetylglucosamine polymer.",
    what: "A standard humectant in skincare and a component of licensed dermal fillers. Research ‘HA vials’ for injection are not fillers and are not sold.",
    how: "Water binding in the stratum corneum (topical) or space-filling (licensed fillers).",
    body: "Topical cosmetics vs clinic fillers are different products.",
    studied: ["Cosmetic hydration", "Licensed filler devices"],
    benefits: ["Topical hydration in cosmetics"],
    notFor: ["Unlicensed filler injections"],
    human: "Fillers are regulated devices; topical HA is cosmetic.",
    pre: "ECM biology.",
    sides: "Vascular occlusion is a filler emergency — another reason not to buy random HA vials.",
    contra: "Do not inject unlicensed HA.",
    reg: "Cosmetic ingredient or medical device depending on presentation.",
    au: noAu,
    areas: ["skin-hair"],
    terms: ["hyaluronate", "ha"],
  }),
  entry({
    slug: "lemon-bottle",
    name: "Lemon Bottle (catalogue solution)",
    aliases: ["柠檬瓶"],
    kind: "research",
    peptideClass: "Unlicensed injectable ‘fat-dissolve’ cocktail (not a defined peptide)",
    structure: "Vendor solutions typically mix detergents, vitamins and plant extracts — composition is not standardised.",
    what: "A marketed mesotherapy-style fat-dissolve liquid. Not an approved medicine in this shop. Not sold.",
    how: "Detergent-type adipocyte injury is the usual aesthetic-industry claim — not a peptide mechanism.",
    body: "Tissue necrosis and contour irregularity are documented risks of unlicensed fat-dissolve injections.",
    studied: ["Aesthetic marketing, not robust drug approval"],
    benefits: ["None approved"],
    notFor: ["Body-contour injections"],
    areas: ["metabolic", "skin-hair"],
    terms: ["lb10", "fat dissolve"],
    ...researchStd,
  }),
  entry({
    slug: "l-carnitine",
    name: "L-carnitine",
    aliases: ["Levocarnitine"],
    kind: "approved",
    peptideClass: "Amino-acid derivative (not a peptide hormone)",
    structure: "Quaternary ammonium compound involved in fatty-acid transport.",
    what: "Licensed oral/IV carnitine exists for deficiency states. High-dose ‘fat-burner’ vials on peptide lists are not those products and are not sold.",
    how: "Carnitine shuttle for long-chain fatty acids.",
    body: "GI upset orally; injection adds no proven fat-loss indication for healthy people.",
    studied: ["Carnitine deficiency", "Some dialysis/cardiac contexts"],
    benefits: ["Licensed deficiency treatment — not a cutting peptide"],
    notFor: ["Lipo-C bodybuilding drips"],
    human: "Deficiency treatment is real; aesthetic vials are not.",
    pre: "Mitochondrial fatty-acid oxidation.",
    sides: "Fishy odour, GI effects; injection-site issues.",
    contra: "Seizure history caution for high-dose carnitine in some labels.",
    reg: "Approved in specific deficiency presentations.",
    au: noAu,
    areas: ["metabolic"],
    terms: ["lc600", "levocarnitine"],
  }),
  entry({
    slug: "lipo-c",
    name: "Lipo-C / MIC blends",
    aliases: ["Lipotropic injection", "MIC (methionine, inositol, choline)", "Lipo-C + B12"],
    kind: "research",
    peptideClass: "Vitamin/amino ‘lipotropic’ mixture (not a peptide drug)",
    structure: "Variable mixes of carnitine, methionine, choline, inositol, B12, arginine.",
    what: "Wellness-clinic fat-burner injections. Evidence for body-fat reduction is weak. Not sold.",
    how: "One-carbon metabolism and carnitine marketing stories.",
    body: "Unproven fat loss; B12 can still cause acne or rare anaphylaxis.",
    studied: ["Historical ‘lipotropic’ aesthetic practice"],
    benefits: ["None as an approved slimming medicine"],
    notFor: ["Weight-loss injections"],
    areas: ["metabolic"],
    terms: ["lc216", "mic", "fat blaster", "super shred"],
    ...researchStd,
  }),
];
